### ISSUE TITLE
[BUG]: Linux下弹出窗口不在顶层

### ISSUE THREAD

**Issue by Guwalgiyakuan** [pot-app/pot-desktop#100]
### 问题描述

使用 Pot 0.3.3版本+Starry 实现划词后弹出悬浮按钮，点击<悬浮按钮>后的翻译窗口总是在当前窗口之下无法查看。如果划词后使用<快捷键>翻译弹出窗口会在顶层出现。

### 如何复现

在比如 Firefox 等窗口比较大的程序里使用完全看不到弹出窗口
![图片](https://github.com/pot-app/pot-desktop/assets/37359970/9341b637-f990-41c6-82bd-7e2b52132930)
在比较小的窗口里使用大概率可以露出一部分窗体
![图片](https://github.com/pot-app/pot-desktop/assets/37359970/288bd728-7a7d-4083-b97b-fa915c866b14)

### 操作系统

Linux

### 操作系统版本

Ubuntu 22.04.2 LTS Gnome 桌面

### 窗口系统(Linux Only)

X11

### 软件版本

0.3.2-0.3.3

**Comment by Pylogmon** [comment]
第二张图片pot开启了置顶为什么另一个窗口还能在pot前面

**Comment by Guwalgiyakuan** [comment]
> 第二张图片pot开启了置顶为什么另一个窗口还能在pot前面

这就是用悬浮按钮翻译的结果，同一个窗口里如果划词后用快捷键就置顶了

**Comment by Pylogmon** [comment]
找到问题了，下个版本修复，感谢反馈

**Comment by Guwalgiyakuan** [comment]
> 找到问题了，下个版本修复，感谢反馈

感谢 辛苦了⛽

**Comment by Pylogmon** [comment]
已修复
