### ISSUE TITLE
[BUG]: KDE中截图翻译无法工作

### ISSUE THREAD

**Issue by Anivie** [pot-app/pot-desktop#1003]
### Description

在KDE中无法触发截图翻译，按下后没有任何事情发生，控制台也没有任何输出(应用内f12)

### Reproduction

正常注册快捷键，然后按下

### Platform

Linux

### System Version

Kubuntu 24.04 with KDE 5.27.11

### Window System (Linux Only)

X11

### Software Version

3.0.6

**Comment by xtyuns** [comment]
已知问题，解决方案：https://pot-app.com/docs/wayland.html#%E5%BF%AB%E6%8D%B7%E9%94%AE%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8
