### ISSUE TITLE
[BUG]: Win7 x64下点翻译报错...

### ISSUE THREAD

**Issue by wxlg1117** [pot-app/pot-desktop#101]
### 问题描述

#85

> 已修复，下个版本可用，或者可以下载这个 https://github.com/pot-app/pot-desktop/suites/12948945728/artifacts/699953856

该版本win10上可用,但是在win7 x64上,不管根据文档设置代理格式(http: http://{host}:{port}或socks5: socks5://{host}:{port})还是**不用代理**,点击翻译都会报错:

```
Network Error: Tls Error: 接收到的消息异常，或格式不正确。 (os error -2146893018): Tls Error: 接收到的消息异常，或格式不正确。 (os error -2146893018)
```

### 如何复现

设置代理和不设置代理点翻译都报错.

### 操作系统

Windows (Default)

### 操作系统版本

win7 x64

### 窗口系统(Linux Only)

None

### 软件版本

https://github.com/pot-app/pot-desktop/suites/12948945728/artifacts/699953856
最新版0.3.3 (2023-05-18)也一样报错

**Comment by Pylogmon** [comment]
我试过了，只有deepl有问题，有可能是系统兼容性的问题，看起来像是win7不支持某个协议，具体是啥我也不知道，用其他接口吧。

**Comment by Pylogmon** [comment]
不知道，win7已经不再维护了，很多安全更新都没有，我在安装虚拟机的时候就遇到了一些相关的问题，我猜跟这方面有关系。

**Comment by wxlg1117** [comment]
> 不知道，win7已经不再维护了，很多安全更新都没有，我在安装虚拟机的时候就遇到了一些相关的问题，我猜跟这方面有关系。

win7 x64收费安全更新还在继续的.个人用有毛子搞的离线安装包,能直接整合进wim文件.
