### ISSUE TITLE
[Feature]: 直接Fork Bob吧

### ISSUE THREAD

**Issue by hululu1068** [pot-app/pot-desktop#104]
### 需求描述

安装了pot，用了2天，又卸载装回Bob了。。。

直接Fork [Bob](https://github.com/ripperhe/Bob.git) 得了，功能差不多，体验还有很大的优化空间

如果是练手就算了

### 应用场景

[。。。](https://github.com/ripperhe/Bob.git)

**Comment by Pylogmon** [comment]
可惜人家Bob没有开源，再说了人家是Mac原生应用，就算开源我fork了也做不了跨平台。

**Comment by Pylogmon** [comment]
我做这个软件就是想在Windows和Linux下也用上像Bob这么优秀的软件，MacOS只是顺手支持，我甚至没有Mac设备来做测试，而且我这项目才起步两个月，体验肯定不如人家，你乐意用你就用，不乐意用拉到，我也没求着你用，大可不必专门来开个issue嘲讽，不懂开源就不要瞎叫，丢不丢人，你以为Github上有个仓库就是开源了？也不看看人家仓库里放的是啥。

**Comment by keaiye** [comment]
![67cebd5c4dc5a5a196fff5f3e60f452c](https://github.com/pot-app/pot-desktop/assets/43440669/fc5c10fe-b448-49c3-a9d8-6094d586cce3)

**Comment by hululu1068** [comment]
> 我做这个软件就是想在Windows和Linux下也用上像Bob这么优秀的软件，MacOS只是顺手支持，我甚至没有Mac设备来做测试，而且我这项目才起步两个月，体验肯定不如人家，你乐意用你就用，不乐意用拉到，我也没求着你用，大可不必专门来开个issue嘲讽，不懂开源就不要瞎叫，丢不丢人，你以为Github上有个仓库就是开源了？也不看看人家仓库里放的是啥。

现在的年轻人都这么玻璃心啊。。。不好意思，戳到你了

**Comment by lazy0327** [comment]
前排来支持作者~~~

**Comment by zhajiahui** [comment]
下头男滚出克

**Comment by MicroCBer** [comment]
有点逆天的这issue 是我我直接delete了

**Comment by FLIER001** [comment]
人如其头像，现代社会的巨婴

**Comment by 2435043xia** [comment]
遇到问题不提出问题改善开源项目，反而做出让人笑掉大牙地嘲讽，更不要说你会fix issue了，你真是不配。

**Comment by chengnan049** [comment]
> > 我做这个软件就是想在 Windows 和 Linux 下也用上像 Bob 这么优秀的软件，MacOS 只是顺手支持，我甚至没有 Mac 设备来做测试，而且我这项目才起步两个月，体验肯定不如人家，你乐意用你就用，不乐意用拉到，我也没求着你用，大可不必专门来开个 issue 嘲讽，不懂开源就不要瞎叫，丢不丢人，你以为 Github 上有个仓库就是开源了？也不看看人家仓库里放的是啥。
> 
> 现在的年轻人都这么玻璃心啊。。。不好意思，戳到你了

这是玻璃心？没人求着你用，爱用不用，反倒是你这种非 Issues 开 Issues 的行为令人感到恶心。再说了，Bob 也不开源，Fork 什么？

**Comment by oneisall8955** [comment]
滥用issue。哪里有问题请指出需要优化的点和提供哪些feature

**Comment by BrsyRockSs** [comment]
> > 我做这个软件就是想在Windows和Linux下也用上像Bob这么优秀的软件，MacOS只是顺手支持，我甚至没有Mac设备来做测试，而且我这项目才起步两个月，体验肯定不如人家，你乐意用你就用，不乐意用拉到，我也没求着你用，大可不必专门来开个issue嘲讽，不懂开源就不要瞎叫，丢不丢人，你以为Github上有个仓库就是开源了？也不看看人家仓库里放的是啥。
> 
> 现在的年轻人都这么玻璃心啊。。。不好意思，戳到你了

你别这么阴阳怪气的嘛，听我一句劝，ke tui~

**Comment by lxh0508** [comment]
白嫖出了优越感，不要脸，觉得不好不用不就完了

**Comment by aisk** [comment]
@hululu1068 素质暴露出来了

![](https://user-images.githubusercontent.com/38856864/239502888-b6bc356a-e84e-47ce-8aed-3097e988b1d2.png)

**Comment by INTEL-2333** [comment]
![](https://user-images.githubusercontent.com/38856864/239502888-b6bc356a-e84e-47ce-8aed-3097e988b1d2.png)

**Comment by RimuruChan** [comment]
# 慕名前来围观2b
![image](https://github.com/pot-app/pot-desktop/assets/42002296/7e443959-bcec-42e3-a602-eea8ee9542cd)

**Comment by dogxgit** [comment]
什么臭鱼烂虾

**Comment by zcybupt** [comment]
右边给你打的 Label 不错 😁

**Comment by nukemiko** [comment]
> > 我做这个软件就是想在Windows和Linux下也用上像Bob这么优秀的软件，MacOS只是顺手支持，我甚至没有Mac设备来做测试，而且我这项目才起步两个月，体验肯定不如人家，你乐意用你就用，不乐意用拉到，我也没求着你用，大可不必专门来开个issue嘲讽，不懂开源就不要瞎叫，丢不丢人，你以为Github上有个仓库就是开源了？也不看看人家仓库里放的是啥。
> 
> 现在的年轻人都这么玻璃心啊。。。不好意思，戳到你了

没啥，就是慕名前来围观活傻逼长什么批样，纯度超不超。

**Comment by oluceps** [comment]
![](https://user-images.githubusercontent.com/38856864/239502888-b6bc356a-e84e-47ce-8aed-3097e988b1d2.png)

**Comment by Lichenkass** [comment]
围观sb

**Comment by maoabc** [comment]
拿个闭源md项目叫别人去fork🌝

**Comment by NNGTHB** [comment]
> ### 需求描述
> 安装了pot，用了2天，又卸载装回Bob了。。。
> 
> 直接Fork [Bob](https://github.com/ripperhe/Bob.git) 得了，功能差不多，体验还有很大的优化空间
> 
> 如果是练手就算了
> 
> ### 应用场景
> [。。。](https://github.com/ripperhe/Bob.git)
> 
> ### 参考资料
> _No response_

慕名来围观纯傻逼

**Comment by cmj2002** [comment]
慕名前来嘲笑

**Comment by fregie** [comment]
@hululu1068 快出来挨骂了

**Comment by JavaZeroo** [comment]
@hululu1068 
围观
![](https://user-images.githubusercontent.com/38856864/239502888-b6bc356a-e84e-47ce-8aed-3097e988b1d2.png)

**Comment by VirgilClyne** [comment]
慕名前来
参观考察调研

**Comment by ShrBox** [comment]
![image](https://github.com/pot-app/pot-desktop/assets/53301243/48acd553-84e4-4270-99db-9b1cd470d44f)

**Comment by tt67wq** [comment]
慕名围观纯傻逼

**Comment by phierus** [comment]
哪里都有网爆自己的xx啊

**Comment by Lighfer** [comment]
@hululu1068 围观sb
![](https://user-images.githubusercontent.com/53301243/239548342-48acd553-84e4-4270-99db-9b1cd470d44f.png)

**Comment by cweijan** [comment]
真下头

**Comment by leic4u** [comment]
专开 issue 来嘲讽确实不对，不过既然自己是自己不对，那挨打就要立正，题主别被 V 站老哥们搞得玻璃心了哈。
如果受不了建议直接换号，估计你这个号被 V 站老哥们盯上了。

**Comment by AdiEcho** [comment]
![image](https://github.com/pot-app/pot-desktop/assets/30563671/37d6e17b-13a5-450d-8dfc-dff606e8fea1)
