### ISSUE TITLE
[Bug]: 剪切板监听模式无法自动格式化

### ISSUE THREAD

**Issue by BBkinga** [pot-app/pot-desktop#105]
### 需求描述

- [x] 剪切板监听模式下，需手动点击删除换行按钮，希望增加自动格式化功能，目前删除换行功能在开启剪切板监听模式同时在少量复制的情况下，有时会失效，点击删除换行后马上又恢复到原来的状态，可能它又通过监听剪切板恢复到原状了。

2.希望增加仅显示译文功能，有时不需要原文窗口。
3.希望可以调节字体大小

### 应用场景

pdf文献翻译

### 参考资料

https://github.com/CopyTranslator/CopyTranslator

**Comment by Pylogmon** [comment]
仅显示译文窗口还得进行比较大的改动，暂时不打算动

**Comment by Pylogmon** [comment]
要调节字体大小不如支持整体内容的缩放，就像浏览器那样，可惜tauri还没有支持zoom，不过已经在支持过程中，等tauri支持之后我会跟进。
