### ISSUE TITLE
[Feature]: 建议发布到 Windows Store

### ISSUE THREAD

**Issue by leic4u** [pot-app/pot-desktop#107]
### 需求描述

建议发布到 Windows Store ，以支持 Surface 设备的 S 模式 Windows 系统，同时还能后台自动更新。

### 应用场景

建议发布到 Windows Store ，以支持 Surface 设备的 S 模式 Windows 系统，同时还能后台自动更新。

### 参考资料

参考微软官方文档：[为应用创建应用提交](https://learn.microsoft.com/zh-cn/windows/apps/publish/publish-your-app/create-app-submission?pivots=store-installer-msix)

**Comment by Pylogmon** [comment]
没钱买开发者账号🤔

**Comment by Pylogmon** [comment]
可惜了，付款还需要VISA卡，我也没有
