### ISSUE TITLE
[BUG]: 开启 OpenAi 流式输出后，翻译界面变空白

### ISSUE THREAD

**Issue by LIlGG** [pot-app/pot-desktop#108]
### 问题描述

使用 OpenAi 流式翻译后，翻译界面整体会变空白，具体表现是 
1、出现翻译窗口
2、展示默认内容
3、整个窗口变为白色

> GIF 示例
 ![pot-bug](https://github.com/pot-app/pot-desktop/assets/31335418/9c2fafe8-d526-4197-b7c8-5ef807706b61)

另外非常感谢作者提供如此优秀的开源软件。

### 如何复现

1、配置 OpenAi 翻译设置。
2、`翻译设置 - 默认接口` 改为 OpenAi。
3、翻译设置中勾选 `OpenAi 流式输出`
4、选中单词，执行翻译，问题出现。

测试过程中，如果取消勾选 `OpenAi 流式输出`，则 OpenAi 翻译功能能够成功翻译并展示界面。

PS：首次翻译过程中，翻译了比较大量的文本，或许有可能是此原因导致流式输出出现问题，但此猜测未经过验证。另外系统本地并无代理设置。

### 操作系统

Windows (Default)

### 操作系统版本

Windows 11 家庭中文版
版本：22H2 (22621.1702)

### 窗口系统(Linux Only)

None

### 软件版本

pot:0.3.4  
Tauri:1.3.0

Pot 使用了 SnipDo

**Comment by Pylogmon** [comment]
是否使用azure服务?
是否使用的是azure旧版接口？

**Comment by Pylogmon** [comment]
方便的话请把完整的配置文件发我邮箱，或者加群私聊

**Comment by LIlGG** [comment]
> 是否使用azure服务? 是否使用的是azure旧版接口？

hi @Pylogmon 感谢回复。并未使用 azure 服务及其接口。使用 OpenAi 接口，其中修改了自定义域名。

配置已通过邮件进行发送。

**Comment by Pylogmon** [comment]
你的自定义域名看起来很奇怪，是第三方服务还是自己搭建的代理

**Comment by LIlGG** [comment]
> 你的自定义域名看起来很奇怪，是第三方服务还是自己搭建的代理

使用 `vercel` 自行搭建， 不开启 `Open 流式输出` 时将能够正常返回结果。

**Comment by Pylogmon** [comment]
把最后的/删了试试

**Comment by Pylogmon** [comment]
方便的话我需要你提供一下域名和key我来进行测试，因为我这边正常请求出错也不会出现白屏

**Comment by LIlGG** [comment]
> 方便的话我需要你提供一下域名和key我来进行测试，因为我这边正常请求出错也不会出现白屏

已发送至邮箱

**Comment by Pylogmon** [comment]
已复现，等我排查一下问题

**Comment by LIlGG** [comment]
> 已复现，等我排查一下问题

了解，或许是自定义域名的问题，我无法确保使用目标域名功能能否支持 OpenAi 流式输出，但非流式输出确实可行。

**Comment by Pylogmon** [comment]
你的地址不支持跨域

**Comment by Pylogmon** [comment]
白屏问题已经修复，你只要让你的服务支持跨域请求就可以使用stream输出了，因为非流式输出是使用tauri提供的fetch来发送的请求，不存在跨域问题，流式输出使用浏览器的fetch相当于ajax请求，如果不允许跨域的话会被同源策略拦截。

**Comment by LIlGG** [comment]
> 白屏问题已经修复，你只要让你的服务支持跨域请求就可以使用stream输出了，因为非流式输出是使用tauri提供的fetch来发送的请求，不存在跨域问题，流式输出使用浏览器的fetch相当于ajax请求，如果不允许跨域的话会被同源策略拦截。

了解了~ 非常感谢能如此快的解决我的问题。
