### ISSUE TITLE
[BUG]: 无法进行划词翻译

### ISSUE THREAD

**Issue by Eyion** [pot-app/pot-desktop#109]
### 问题描述

无法进行划词翻译（独立翻译窗口也如此）

### 如何复现

在pot的热键设置 - 划词翻译 - 按下ctrl之类的键进行快捷键设置，打开外文网页，选中并按下设置好的快捷键，无响应。

### 操作系统

Windows (Default)

### 操作系统版本

Windows 10 LTSC

### 窗口系统(Linux Only)

None

### 软件版本

pot_0.3.4_x64_portable

### 补充信息

无快捷键冲突，不知是否哪里没有设置或操作不正确。

**Comment by Pylogmon** [comment]
具体的快捷键设置的是什么，输入快捷键之后点击确认了吗

**Comment by Eyion** [comment]
> 具体的快捷键设置的是什么，输入快捷键之后点击确认了吗

ctrl，ctrl+shift，ctrl+alt都试过，最后都确认了的。

**Comment by Pylogmon** [comment]
不支持这样的快捷键，加上一个字母，比如 Alt+D

**Comment by Eyion** [comment]
好的，可以了，谢谢。腾讯交互翻译需要申请API吗？如不需要，建议增加。
下图为某翻译插件接口
![image](https://github.com/pot-app/pot-desktop/assets/26318038/6100eacb-c3fd-4b84-b2a2-dccae7e496f1)

**Comment by Pylogmon** [comment]
需要申请的

**Comment by Cypredar** [comment]
请问可以省去热键，每次选中后直接翻译吗
