### ISSUE TITLE
[BUG]: Windows记事本内划词失效

### ISSUE THREAD

**Issue by yztz** [pot-app/pot-desktop#110]
### 问题描述

在记事本内划取单词使用快捷键翻译，显示的是剪切板中内容的翻译结果。

### 如何复现

1. 打开Windows记事本
2. 输入些许内容，例如“你好世界，hello world”
3. 划取内容
4. 键入快捷键（我设置为 Ctrl + `
5. 显示翻译结果为剪切板中内容的翻译结果 

### 操作系统

Windows (Default)

### 操作系统版本

Windows11

### 窗口系统(Linux Only)

None

### 软件版本

pot:0.3.4  Tauri:1.3.0
windows notepad:11.2112.32.0

### 补充信息

当记事本窗口重获焦点时，翻译效果会生效：

1. 在记事本中先选择要翻译的内容
2. 使用 alt + tab 切换窗口（切出去，再切回来）
3. 按下快捷键，翻译可以生效一次，但重复翻译动作将会失效

另外一种比较方便的方法是当选取完翻译内容后，先按下alt键，再按翻译快捷键，也可以生效。

**Comment by Pylogmon** [comment]
没能复现

**Comment by Pylogmon** [comment]
![image](https://github.com/pot-app/pot-desktop/assets/59004461/e3df46ed-8604-4fb3-a09a-7b3f9c5644cc)

**Comment by yztz** [comment]
记事本似乎不同，我目前的记事本是不支持多窗口的记事本版本

**Comment by yztz** [comment]
![image](https://github.com/pot-app/pot-desktop/assets/42884283/4578d638-e493-4c45-8475-c1d75f3fb807)

**Comment by Pylogmon** [comment]
更新一下试试

**Comment by yztz** [comment]
更新后似乎可以了，另外请问能否支持更多的快捷键姿势，比如“双击Ctrl“这类（快捷键冲突真是太恼人了

**Comment by Pylogmon** [comment]
这个没法支持，全局快捷键我是直接使用tauri提供的方法，没有自己实现，快捷键冲突问题，我觉得用插件调用可以解决大半，插件取不到再按快捷键，我自己是这样用的。

**Comment by yztz** [comment]
好的，非常感谢你，难得的宝藏软件😋

**Comment by Pylogmon** [comment]
感谢支持
