### ISSUE TITLE
[BUG]: 一设置快捷键就闪退了

### ISSUE THREAD

**Issue by yuhan2680** [pot-app/pot-desktop#111]
### 问题描述

设置快捷键为Shift+?，然后后面去划词的时候没出来，然后后面去看了一下发现退出了，点进去重新设置又闪退了

### 如何复现

如上

### 操作系统

Windows (Default)

### 操作系统版本

Win 11

### 窗口系统(Linux Only)

None

### 软件版本

pot_0.3.4_x64_zh-CN.msi

**Comment by Pylogmon** [comment]
会闪退的快捷键就是不能设置的快捷键，按理说这种快捷键你应该输不进去，你是怎么输进去shift+？的，我刚刚试了不行，倒是能输进去shift+/，这个快捷键可以用

**Comment by yuhan2680** [comment]
我刚刚试了一下好像试不出来shift+/，就是在输入法弄成英文之后同时按shift+/它就显示是"Shift+?"了，然后在中文输入法的时候输入了Shift就没法输入其它键了

**Comment by Pylogmon** [comment]
先按shift，松开后再按/

**Comment by Albertyangbu** [comment]
我的mac m2，设置快捷键也闪退

**Comment by Pylogmon** [comment]
具体设置的什么快捷键

**Comment by Albertyangbu** [comment]
可能是存在command的快捷键会闪退，例如，使用command+Y会闪退，但是control+Y就可以

**Comment by Pylogmon** [comment]
还有这问题，我没有MAC没法测试，不过现阶段mac设置快捷键没啥用，快捷键取词还没修好，只能通过popclip使用。

**Comment by Caskia** [comment]
设置 command 为快捷键闪退。闪退后notification的设置也就卡住了。

**Comment by Pylogmon** [comment]
有无视频

**Comment by yeungxing** [comment]
mac 10.15.7也是 好像是那个按键识别不正常的话就闪退，我是alt+d  这个 D 显示的是其他字符不是 D 就闪退 但是我换  shift+d  那个 D 显示正常就没事

**Comment by MrHongping** [comment]
一个一个的按键就没有闪退的问题了

**Comment by ljtnono** [comment]
macos设置任何快捷键然后点确认都会闪退

**Comment by Pylogmon** [comment]
> macos设置任何快捷键然后点确认都会闪退

测试过哪些快捷键

**Comment by ljtnono** [comment]
> > macos设置任何快捷键然后点确认都会闪退

ctrl + alt + 数字或字母，alt + shift + 数字或字母， ctrl + 数字或字母，测了7-8个组合吧，都不行。

inter cpu 操作系统 macos 13.3.1

**Comment by ljtnono** [comment]
> > macos设置任何快捷键然后点确认都会闪退
> 
> 测试过哪些快捷键

ctrl + alt + 数字或字母，alt + shift + 数字或字母， ctrl + 数字或字母，测了7-8个组合吧，都不行。

inter cpu 操作系统 macos 13.3.1

**Comment by bylevel** [comment]
我提了一个PR尝试解决这个问题 #166

**Comment by Pylogmon** [comment]
Tauri更新之后这个问题应该已经不存在了
