### ISSUE TITLE
[Feature]: <增加deepl apikey调用>

### ISSUE THREAD

**Issue by CyshallChan** [pot-app/pot-desktop#113]
### 需求描述

默认的deepl翻译应该是模拟的网页调用吧？我这边经常会遇到to many request的报错，因此最好是能够增加使用自己的apikey进行调用。

### 应用场景

无

### 参考资料
可以参考bob的实现

**Comment by Pylogmon** [comment]
我没有信用卡申请不到key

**Comment by CyshallChan** [comment]
> 我没有信用卡申请不到key

如果你需要key做测试的话我可以提供，留下有邮箱即可。

**Comment by Pylogmon** [comment]
pylogmon@outlook.com

**Comment by CyshallChan** [comment]
> [pylogmon@outlook.com](mailto:pylogmon@outlook.com)

发给你了。

**Comment by Pylogmon** [comment]
感谢配合，已支持
