### ISSUE TITLE
[BUG]: 更新版本后所有的设置都被重置了

### ISSUE THREAD

**Issue by Chaufferdeterra** [pot-app/pot-desktop#115]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 问题描述

更新版本后所有的设置都被重置了

### 如何复现

程序自动更新

### 操作系统

Windows

### 操作系统版本

Win 10 

### 窗口系统(Linux Only)

None

### 软件版本

从0.3.2更新到0.3.6

**Comment by Pylogmon** [comment]
appid变了，请查看0.3.4更新日志
