### ISSUE TITLE
[BUG]: openai服务提供商Azure无相关api选项

### ISSUE THREAD

**Issue by skypoc** [pot-app/pot-desktop#116]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 问题描述

如果使用Azure api的话，应该有如下选项：

- endpoint
- API
- 模型部署名称

这样才能进行api请求。
OpenAI自定义域名不能替代endpoint

### 如何复现

可以参考chatbox中Azure API的配置：https://github.com/Bin-Huang/chatbox

### 操作系统

Windows

### 操作系统版本

Windows 10 22h2

### 窗口系统(Linux Only)

None

**Comment by Pylogmon** [comment]
这些都可以在请求路径中填写的

**Comment by skypoc** [comment]
> 这些都可以在请求路径中填写的

谢谢您的回复，我尝试一下。

**Comment by atmomomo** [comment]
> ### 提交新Issue前请确认一下事项
> * [x]  我已确认以上事项
> 
> ### 问题描述
> 如果使用Azure api的话，应该有如下选项：
> 
> * endpoint
> * API
> * 模型部署名称
> 
> 这样才能进行api请求。 OpenAI自定义域名不能替代endpoint
> 
> ### 如何复现
> 可以参考chatbox中Azure API的配置：https://github.com/Bin-Huang/chatbox
> 
> ### 操作系统
> Windows
> 
> ### 操作系统版本
> Windows 10 22h2
> 
> ### 窗口系统(Linux Only)
> None
> 
> ### 软件版本
> _No response_
> 
> ### 补充信息
> _No response_



> 这些都可以在请求路径中填写的

我遇到一样的问题。Azure需要填 API URL, API URL PATH, 和 Key三项信息，但UI只提供了“请求地址”和“API KEY” 两个输入项目。连不上。
![Clip_20230922_124741](https://github.com/pot-app/pot-desktop/assets/26316925/69bd82b3-8c23-4954-be1b-d4ea83fdfeca)

**Comment by Pylogmon** [comment]
URL和path拼起来不就是完整请求地址吗
