### ISSUE TITLE
[Feature]: 添加记住翻译窗口大小的功能

### ISSUE THREAD

**Issue by oliverustc** [pot-app/pot-desktop#118]
### 提交新Issue前请确认一下事项

- [x] 我已确认以上事项

### 需求描述

能否增加翻译窗口大小自定义的功能，或者将上次窗口的大小设置为窗口默认大小？

### 应用场景

如果要翻译的部分比较长，比如一篇paper的abstract，就会因为文本过长导致输出窗口出现滚动条。
要想把窗口拉大，必须先将窗口固定，否则鼠标点击就会让翻译窗口直接消失。

**Comment by Pylogmon** [comment]
有设置大小的选项啊

**Comment by oliverustc** [comment]
抱歉抱歉，竟然没看到，叨扰了。
