### ISSUE TITLE
[Feature]: 可否根据文字数量自动调整窗口大小？

### ISSUE THREAD

**Issue by micturkey** [pot-app/pot-desktop#121]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 需求描述

根据文字数量自动调整窗口大小

### 应用场景

现有的pot是通过设置中固定窗口大小的，如果设置的太小，对于pdf等文字较多的场景就会不够显示，如果设置较大，很短的句子也会占用较大的屏幕空间

### 参考资料

可以参考Bob中自动调整高度的方案。

**Comment by Pylogmon** [comment]
bob是Mac应用，pot是基于Tauri框架，相当于窗口里面跑的是web应用，实现这个有点困难。

**Comment by micturkey** [comment]
> bob是Mac应用，pot是基于Tauri框架，相当于窗口里面跑的是web应用，实现这个有点困难。

谢谢回复，不是很了解这个框架，如果比较困难的话就只能先这样用着了😂
