### ISSUE TITLE
[BUG]: Linux 弹出窗口始终置顶

### ISSUE THREAD

**Issue by linsui** [pot-app/pot-desktop#123]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 问题描述

即使置顶没有启用，窗口仍然置顶。只有启用再取消置顶后才会在焦点不在窗口上之后消失。但似乎窗口直接关闭了。

### 如何复现

翻译，然后点击其他窗口，翻译窗口始终置顶。

### 操作系统

Linux

### 操作系统版本

NixOS

### 窗口系统(Linux Only)

Wayland

### 软件版本

0.3.6

### 补充信息

我希望不置顶的时候窗口仍然在桌面上。这样翻译的时候不需要重新打开一个窗口。似乎 tauri 创建新窗口非常慢。

**Comment by Pylogmon** [comment]
gnome还是kde？

**Comment by linsui** [comment]
GNOME

**Comment by Pylogmon** [comment]
这个不知道是gnome的问题还是tauri的问题，tauri仓库有相关issue，在gnome下窗口无法捕获焦点，所以无法触发焦点丢失关闭窗口的事件

**Comment by Pylogmon** [comment]
> 我希望不置顶的时候窗口仍然在桌面上。这样翻译的时候不需要重新打开一个窗口。

gnome下如果默认不让窗口置顶的话窗口是不会到达最前端的，会被其他窗口挡住，因为无法捕获焦点，只能通过置顶来确保在最前端出现。

> 似乎 tauri 创建新窗口非常慢。

你遇到出现窗口很慢的情况了吗，我没有遇到过这个问题

**Comment by Pylogmon** [comment]
> 我重新测试了一下，似乎问题不是这个，而是设置和显示同步的问题。置顶按钮有时不能正确反应当前设置。我在启用默认置顶之后打开的翻译窗口是置顶的，但按钮是灰色的。而且设置窗口和翻译窗口之间还会相互影响。

是啊，对于划词窗口来说，无论是否启用，窗口都是置顶的，请认真阅读我上面的回复。

**Comment by linsui** [comment]
> 让其捕获焦点，然后再点击其他地方就可以自动关闭了。

这个问题也存在。测试起来有点复杂，有点摸不着头脑了。

**Comment by linsui** [comment]
我又重新测试了，现在我认为问题除了 tauri 的那个问题之外，另一个问题是用 pot translate 打开的窗口没有遵守设置默认置顶。从 tray 打开的窗口正确置顶了。

> 你遇到出现窗口很慢的情况了吗，我没有遇到过这个问题

我这里打开窗口需要两秒，相比 crow translate (Qt) 要慢一些。

**Comment by linsui** [comment]
我明白了，如果需要置顶要用 pot persistent。谢谢！

**Comment by Pylogmon** [comment]
pot translate 启动的是划词窗口，他会获取选中的文本

pot persistent 启动的是独立翻译窗口，他是用来输入翻译的，并不会获取选中的文本

两种窗口的pin按钮默认行为是根据其用途分别设计的

**Comment by Pylogmon** [comment]
但是没有办法，gnome下不置顶就没法用了，就是因为gnome才让划词窗口默认置顶的。

我自己使用过程中窗口出现速度很快的，你这个应该不是tauri创建窗口慢的问题，应该是Wayland下使用系统快捷键调用pot导致的速度慢，这个暂时也没有办法，因为tauri的全局快捷键还没有支持wayland，如果你在x11下在应用内设置快捷键你就会发现启动速度是很快的。

**Comment by linsui** [comment]
我对比了 pot 和 crow translate。crow translate 是使用系统快捷键和 dbus 的方式调用的。Qt 创建窗口会比 tauri 快一点。大部分情况下我只是点击其他窗口，这样划词的时候 crow 的窗口出现非常快。crow 能做到大概是因为它用的是 xwayland 不受 wayland 的限制。

我认为系统快捷键调用 pot 并不是速度慢的原因，因为 pot 置顶的时候用快捷键调用响应是很快的，可以看到翻译内容会立即更新。

**Comment by Pylogmon** [comment]
虽然测试是这样，但是我在x11下测试对比后也发现，同样是创建新的窗口，使用软件内置快捷键创建窗口就是很快，使用命令行来调用pot创建的窗口就是要慢很多，我觉得也不是tauri的问题。

**Comment by Pylogmon** [comment]
现在也需要先启动pot，已经修好了，试了下速度差不多。

**Comment by linsui** [comment]
用 dbus 的好处是可以直接向运行的实例发送命令，但没有运行的实例就不起作用。

**Comment by Pylogmon** [comment]
现在这样也有好处啊，没有运行还能直接启动🤣

**Comment by linsui** [comment]
如果 pot 支持 dbus 的话，可以先用 dbus-send，如果返回错误再调用 pot translate。

**Comment by Pylogmon** [comment]
有点麻烦，没必要支持dbus

**Comment by linsui** [comment]
确实，命令行和单例检测的部分基本感知不到。
