### ISSUE TITLE
[BUG]: 当指明待翻译文本的语种时，翻译结果中有不相关字符（某些标签）出现

### ISSUE THREAD

**Issue by cmy2019** [pot-app/pot-desktop#125]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 问题描述

不太会描述，不好意思，看图就明白了。

![01](https://github.com/pot-app/pot-desktop/assets/16515420/0d2c3e63-edef-4d4a-b091-95b78e7bbb9c)
![02](https://github.com/pot-app/pot-desktop/assets/16515420/3875a51a-fe19-4276-87a5-ec3f8efef6a8)

### 如何复现

当指明待翻译文本的语种时

### 操作系统

Windows

### 操作系统版本

WIN10 LTSC 2021

### 窗口系统(Linux Only)

None

### 软件版本

0.3.6

**Comment by Pylogmon** [comment]
只有bing和lingva有这个问题吗？

**Comment by cmy2019** [comment]
@Pylogmon 不确定，其他的一些接口因为需要自定义设置，我一时不好测试

**Comment by Pylogmon** [comment]
已修复，感谢反馈

**Comment by cmy2019** [comment]
> 已修复，感谢反馈

这也太效率了，辛苦了
