### ISSUE TITLE
[BUG]: 托盘单击事件不起作用

### ISSUE THREAD

**Issue by linsui** [pot-app/pot-desktop#126]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 问题描述

GNOME 上托盘单击事件不起作用，单击和右键都是打开菜单。大部分应用的托盘都是这个行为，我目前安装的应用里，只有 jami 是单击打开主程序。

### 如何复现

单击托盘，打开菜单。

### 操作系统

Linux

### 操作系统版本

NixOS

### 窗口系统(Linux Only)

Wayland

**Comment by linsui** [comment]
那可以在 linux 上去掉这项设置吗？

**Comment by Pylogmon** [comment]
Ok

**Comment by linsui** [comment]
谢谢 :+1:
