### ISSUE TITLE
[BUG]: 标题Google翻译和open AI翻译都显示「Network Error: Io Error: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (os error 10060): Io Error: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (os error 10060)」

### ISSUE THREAD

**Issue by chen12zhi** [pot-app/pot-desktop#127]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 问题描述

Google翻译和open AI翻译都显示「Network Error: Io Error: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (os error 10060): Io Error: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (os error 10060)」

我已经登了梯子，open AI的key也是正确的（key在Open AI translator能够正常使用），之前POT的旧版本谷歌翻译和open AI翻译都是正常的，不知为何更新到近期的几次新版本就不能使用了。

### 如何复现

近期的新版本谷歌翻译和open AI翻译都不能使用，都出现「Network Error: Io Error: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (os error 10060): Io Error: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (os error 10060)」

### 操作系统

Windows

### 操作系统版本

Windows 10家庭版19045.2965

### 窗口系统(Linux Only)

None

### 软件版本

0.4.0

**Comment by Pylogmon** [comment]
pot不会走系统代理，请在软件内设置代理

**Comment by chen12zhi** [comment]
请问我这个问题是不是由于没有在pot软件内设置代理导致的？谢谢

**Comment by Pylogmon** [comment]
是的

**Comment by Sakuraj0606** [comment]
> 是的

您好，我也碰到这个问题了，请问在pot软件里怎么设置代理呢？

**Comment by Pylogmon** [comment]
输入你的代理地址后点应用
![image](https://github.com/pot-app/pot-desktop/assets/59004461/ca8f9e12-8f45-4d91-84a4-e41352abcbdf)

**Comment by Sakuraj0606** [comment]
> 输入你的代理地址后点应用 ![image](https://user-images.githubusercontent.com/59004461/242484280-ca8f9e12-8f45-4d91-84a4-e41352abcbdf.png)



> 输入你的代理地址后点应用 ![image](https://user-images.githubusercontent.com/59004461/242484280-ca8f9e12-8f45-4d91-84a4-e41352abcbdf.png)

代理地址是这个吗？这是我加速器上面的信息，我按这个http://127.0.0.1:54210输的，还是用不了谷歌翻译和openai（如图红字连接失败）。而且图上的这个代理地址一直在变......
![1685596103686](https://github.com/pot-app/pot-desktop/assets/48174042/304cc91f-c23d-48e9-b786-1e6f28be6777)
![8322a4862180634fbf9914388cbc977](https://github.com/pot-app/pot-desktop/assets/48174042/88e59cb4-2163-4468-bfe8-d92254869380)

**Comment by Pylogmon** [comment]
那个地址不是你的代理地址，那是你电脑上请求代理的应用的端口号，你的代理端口看你使用的代理软件的文档

**Comment by Sakuraj0606** [comment]
> 那个地址不是你的代理地址，那是你电脑上请求代理的应用的端口号，你的代理端口看你使用的代理软件的文档

好的，我看了下，是这个地址，谷歌翻译可以用了，但是openai还是不行，如图，请问是什么问题呢？
![d1c593794c9334b0003305050361d4f](https://github.com/pot-app/pot-desktop/assets/48174042/6beee66c-ec33-4ea5-a567-3430f802572d)
![ca87e38b2ac14a5ec657f037e772cf7](https://github.com/pot-app/pot-desktop/assets/48174042/e7ccf4f1-5094-4942-876f-1c176202974e)
![de80aa1cf69a02da59e6e3d17e5e79c](https://github.com/pot-app/pot-desktop/assets/48174042/81b7908b-86d2-4dd1-a6e8-fb2c3a0cae0e)

**Comment by Pylogmon** [comment]
没钱了，你的免费额度过期了

**Comment by Sakuraj0606** [comment]
好的，感谢！

**Comment by Sakuraj0606** [comment]
> 没钱了，你的免费额度过期了

你好，我换了个openai账号拿到一个新的钥匙，但是还是不行，出现一样的错误，我看它这个钥匙从未用过，怎么就不能用了呢？
![39332cc99cc94adf920595034690f08](https://github.com/pot-app/pot-desktop/assets/48174042/9935f0eb-95b0-4c63-bc96-0c12393a44a4)
