### ISSUE TITLE
[BUG]: 苹果M2安装显示pot.app已损坏无法打开。

### ISSUE THREAD

**Issue by guancn** [pot-app/pot-desktop#128]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 问题描述

安装pot_0.4.0_aarch64.dmg,提示"pot.app"已损坏，无法打开。

### 如何复现

下载安装就会出现。

### 操作系统

MacOS

### 操作系统版本

Mac OS Ventura 13.3.1(a)

### 窗口系统(Linux Only)

None

### 软件版本

0.4.0 aarch64

**Comment by Pylogmon** [comment]
请认真查阅官网安装指南
