### ISSUE TITLE
[BUG]: deepL接口翻译结果报错

### ISSUE THREAD

**Issue by cmy2019** [pot-app/pot-desktop#129]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 问题描述

deepL接口有概率遇到http请求错误问题，返回：

Http请求错误
Http Status: 429
{"jsonrpc":"2.0","error":{"code":1042912,"message":"Too many requests"}}

截图：
![2023-05-23_110257](https://github.com/pot-app/pot-desktop/assets/16515420/638d8a91-8716-4249-b037-d0389f1aebe3)

### 如何复现

不稳定出现，有可能是用户操作太频繁导致，或者deepL接口本身有限制

### 操作系统

Windows

### 操作系统版本

WIN10 LTSC 2021

### 窗口系统(Linux Only)

None

### 软件版本

0.4.0

**Comment by Pylogmon** [comment]
没有配置key的接口是这样的，频繁请求就会这样，正常。
