### ISSUE TITLE
[BUG]: 同时打开监听剪贴板和翻译后自动复制到剪贴板会开始自产自销

### ISSUE THREAD

**Issue by InitialXKO** [pot-app/pot-desktop#130]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 问题描述

监听剪贴板和翻译后自动复制这两个选项可以同时开启，然后就变成一个成熟的自言自语机器了

### 如何复现

-在设置里打开翻译后自动复制
-开始翻译任意内容
-点击打开剪贴板监听模式

### 操作系统

Windows

### 操作系统版本

Windows11 家庭版 22621.1702

### 窗口系统(Linux Only)

None

### 软件版本

pot:0.4.0  Tauri:1.3.0

**Comment by Pylogmon** [comment]
这个问题以当前的逻辑我还没有办法解决，只能是避免在开启自动复制的同时使用剪切板监听模式。
