### ISSUE TITLE
[BUG]: 0.4.0 无法读取选中内容

### ISSUE THREAD

**Issue by linsui** [pot-app/pot-desktop#131]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 问题描述

更新到 0.4.0 后翻译窗口无法读取选中内容。

### 如何复现

用快捷键或者托盘调用 pot 翻译，文本框是空的。

### 操作系统

Linux

### 操作系统版本

NixOS

### 窗口系统(Linux Only)

Wayland

### 补充信息

我改了 XDG_SESSION_TYPE 之后仍然无法工作。

**Comment by Pylogmon** [comment]
我早上也发现了，gnome的Wayland并没有实现primary selection

**Comment by linsui** [comment]
GNOME 的 wayland 实现很怪异...

**Comment by Integral-Tech** [comment]
我试了 KDE Wayland 可以正常取词

**Comment by linsui** [comment]
另外现在所有窗口都不能置顶了，也是因为 GNOME 吗？传入 GDK_BACKEND=x11 之后独立窗口可以置顶但翻译窗口不置顶。

**Comment by Pylogmon** [comment]
我觉得是tauri的问题，我测试过程中发现在Wayland下tauri提供的窗口置顶是无效的，这个在kde和gnome下都是一样，应该是tauri没有支持

**Comment by Pylogmon** [comment]
#147
