### ISSUE TITLE
[Feature]: 查词结果增加音标朗读功能

### ISSUE THREAD

**Issue by peiyuanix** [pot-app/pot-desktop#133]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 需求描述

查词结果会显示不同的音标，对于词典类翻译结果来说，希望可以在音标旁边添加朗读按钮，点击按钮朗读指定的音标。

![](https://cdn.jsdelivr.net/gh/lpypl/picgo-repo/data/20230523202636.png)

### 应用场景

查词的时候显然不是想听整个结果的朗读，而是音标和例句的朗读。

**Comment by xtyuns** [comment]
@Pylogmon 感觉这个需要修改文本翻译的返回结果来实现
返回结果对象的格式类似于：
```json
{
  voices: [{tooltip: ‘英’, url: ''}, {tooltip: ‘美’, url: ''}],
  target: '翻译结果'
}
```

**Comment by Pylogmon** [comment]
界面部分也需要改，因为当时并没有考虑这种情况，只留了文本框
