### ISSUE TITLE
[BUG]: 能否关闭自动弹出更新提示

### ISSUE THREAD

**Issue by ubidone** [pot-app/pot-desktop#134]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 问题描述

提示4.0版本更新，点了是以后，自动安装到C盘不说，还没更新成功，打开还是3.6

### 如何复现

1

### 操作系统

Windows

### 操作系统版本

win10

### 窗口系统(Linux Only)

None

**Comment by Pylogmon** [comment]
便携版不要使用应用内更新

**Comment by ubidone** [comment]
所以恳请请作者增加一个取消更新提示的开关，谢谢

**Comment by Pylogmon** [comment]
没有吗
