### ISSUE TITLE
[Feature]: 剪贴板监听模式加入快键键启动

### ISSUE THREAD

**Issue by 5starvip** [pot-app/pot-desktop#135]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 需求描述

剪贴板监听模式加入快键键启动，这样可以快速启用/禁用监听模式，非常有用

### 应用场景

平时可以ctrl+c,快速复制文本，同时监听模式自动翻译，并复制译文，效率提高。但不需要复制监听翻译时，可以快速禁用，不需要重新打开软件界面点击禁用监听

**Comment by Pylogmon** [comment]
我觉得只有在需要多次快速取词的时候才需要用到剪切板监听模式，这个时候打开窗口启动监听即可使用，这并不是一个需要频繁打开关闭的操作，没必要单独加一个快捷键。
