### ISSUE TITLE
[Feature]: 建议“润色”和“代码解释”功能添加单独的操作逻辑

### ISSUE THREAD

**Issue by mingchau** [pot-app/pot-desktop#136]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 需求描述

很多时候选中的是普通文本并不是代码，只是想看一下翻译结果，pot也会自动润色和进行解释，浪费了api token。
所以建议对这两个功能添加单独的操作逻辑，只有在需要“润色”和“代码解释”的时候才执行。

### 应用场景

只有在需要“润色”和“代码解释”的时候

**Comment by Pylogmon** [comment]
这几个你别默认开启呗，需要的时候再切换

**Comment by mingchau** [comment]
> 这几个你别默认开启呗，需要的时候再切换

因为选中一段文字的目的是明确的（翻译 or 润色 or 代码解释），你提出的做法可以解决问题，不过，每次都需要在弹出窗口之后再去切换想要的功能，感觉多少有些浪费……

**Comment by qcts33** [comment]
可以考虑给润色翻译等不同类型的任务分配不同的快捷键？

**Comment by Pylogmon** [comment]
pot本质上只是一个翻译软件，OpenAI的这几个只是个扩展应用，我不打算因为这一个接口添加其他逻辑，相比于常用的翻译，这几个用到的时候再手动切换我觉得没什么不好。
