### ISSUE TITLE
[BUG]: 托盘图标显示异常

### ISSUE THREAD

**Issue by wuzhaohui100** [pot-app/pot-desktop#137]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 问题描述

使用自己编译的0.4.0版本，在麒麟V10SP1上运行，托盘图标没有正常加载。

### 如何复现

https://cowtransfer.com/s/0b9d098a85a447 点击链接查看 [ pot_0.4.0_amd64.deb ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 u24spq 查看；
下载上面的包，在麒麟系统运行即可复现。

### 操作系统

Linux

### 操作系统版本

麒麟V10SP1
镜像地址：https://distro-images.kylinos.cn:8802/web_pungi/download/share/2V7UqoC0Kez3syJR4unX6Ojw1hMNHdTk/Kylin-Desktop-V10-SP1-HWE-Release-2303-X86_64.iso.torrent

### 窗口系统(Linux Only)

X11

### 软件版本

pot:0.4.0  Tauri:1.3.0

**Comment by Pylogmon** [comment]
我编译的包不能用吗

**Comment by Pylogmon** [comment]
托盘相关的依赖装全了吗

**Comment by wuzhaohui100** [comment]
> 我编的包不能用吗

您编译的包应该是基于ubuntu22的吧，麒麟系统是基于ubuntu20的，安装您编译的那个包会有缺少libssl的报错。

**Comment by Pylogmon** [comment]
还有一个用debian10编译的，那个能用

**Comment by wuzhaohui100** [comment]
> 托盘相关的依赖装全了吗

软件里面写的依赖都安装了
libxdo-dev, libayatana-appindicator3-1, libwebkit2gtk-4.0-37, libgtk-3-0

**Comment by Pylogmon** [comment]
下载 universal.deb那个包

**Comment by Pylogmon** [comment]
> 软件里面写的依赖都安装了 libxdo-dev, libayatana-appindicator3-1, libwebkit2gtk-4.0-37, libgtk-3-0

那就奇怪了，确定程序运行了但是只有托盘没有出现吗？

**Comment by wuzhaohui100** [comment]
> > 软件里面写的依赖都安装了 libxdo-dev, libayatana-appindicator3-1, libwebkit2gtk-4.0-37, libgtk-3-0
> 
> 那就奇怪了，确定程序运行了但是只有托盘没有出现吗？

只是托盘图标没有显示出来，托盘功能正常

**Comment by wuzhaohui100** [comment]
> 下载 universal.deb那个包

试了这个包，托盘图标也没有显示，是不是需要刷新图标机制呢？
https://zhuanlan.zhihu.com/p/548270127

**Comment by Pylogmon** [comment]
安装linuxqq了吗，QQ的托盘图标正常吗

**Comment by Pylogmon** [comment]
> 下载 universal.deb那个包

安装这个再看看

**Comment by wuzhaohui100** [comment]
> 安装linuxqq了吗，QQ的托盘图标正常吗

QQ正常，QQ是基于electron的吧。
![f6612cd447a2d324d00b4d971cdcac0](https://github.com/pot-app/pot-desktop/assets/108720447/1043ab9f-30a2-42e7-b08c-44abf1ad4ff0)

**Comment by Pylogmon** [comment]
但是托盘都是通过`libayatana-appindicator3-1`实现的，应该是你编译的问题，你的依赖装全了没，

```bash
sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
```

**Comment by wuzhaohui100** [comment]
> 但是托盘都是通过`libayatana-appindicator3-1`实现的，应该是你编译的问题，你的依赖装全了没，
> 
> ```shell
> sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
> ```

这些编译依赖我安装了。

**Comment by Pylogmon** [comment]
> > 下载 universal.deb那个包
> 
> 安装这个再看看

安装这个也有问题吗

**Comment by wuzhaohui100** [comment]
> > > 下载 universal.deb那个包
> > 
> > 
> > 安装这个再看看
> 
> 安装这个也有问题吗

是的

**Comment by Pylogmon** [comment]
![f6612cd447a2d324d00b4d971cdcac0](https://github.com/pot-app/pot-desktop/assets/108720447/1043ab9f-30a2-42e7-b08c-44abf1ad4ff0)

从你这个图片上看，这不像是没有图标，而是一个其他图标，你去手动编辑desktop文件，把图标改成绝对路径试试

**Comment by lblbk** [comment]
解决了吗 我在ubuntu20也会报这个问题 libssl.so.3缺少

**Comment by Pylogmon** [comment]
> 解决了吗 我在ubuntu20也会报这个问题 libssl.so.3缺少

你这不是一个问题，Ubuntu20 下这个 `Linux x64 universal(.deb)`

**Comment by lblbk** [comment]
> > 解决了吗 我在ubuntu20也会报这个问题 libssl.so.3缺少
> 
> 你这不是一个问题，Ubuntu20 下这个 `Linux x64 universal(.deb)`

好的 多谢 多问一句 Linux x64 universal(.deb)这个包的编译是基于libssl的1.0版本？

**Comment by Pylogmon** [comment]
是在debian10编译的，基于 glibc-2.28 和 openssl-1.1

**Comment by lblbk** [comment]
> 是在debian10编译的，基于 glibc-2.28 和 openssl-1.1

好的 多谢 clash-verge一直有这个问题 这下应该能解决了 哈哈哈
