### ISSUE TITLE
[Feature]: 亮色模式下翻译窗口和背景常常难以被区分，希望能加个边框，或者更改亮色模式的窗口背景为非全白色。

### ISSUE THREAD

**Issue by yusanshi** [pot-app/pot-desktop#138]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 需求描述

亮色模式下，最边缘的颜色是纯白（`#FFFFFF`）的，而纯白的颜色在其他应用中很常见，于是，翻译窗口和背景常常难以被区分。

![2023-05-24_19-39](https://github.com/pot-app/pot-desktop/assets/36265606/33ebaa1e-14ef-4d40-b032-ee9243fa7dad)

可能的解决方案：
- 加个边框（比如灰色边框）
- 更改亮色模式的最外层背景色为非全白色（比如偏白的灰色）

### 应用场景

亮色模式下，最边缘的颜色是纯白（`#FFFFFF`）的，而纯白的颜色在其他应用中很常见，于是，翻译窗口和背景常常难以被区分。

**Comment by Pylogmon** [comment]
是linux吗？Windows和MacOS都会有窗口阴影，这样的效果比单纯的边框要好，linux因为不同的窗口管理器实现不同，所以tauri并没有支持，你可以试着手动去设置，如果没法设置那就只能是加个边框了。

![image](https://github.com/pot-app/pot-desktop/assets/59004461/829a4883-3030-4db0-85fd-a3e936a44399)

**Comment by Pylogmon** [comment]
我记得这个插件在添加窗口圆角的同时还会添加窗口阴影，你可以试试
https://extensions.gnome.org/extension/5237/rounded-window-corners/

**Comment by yusanshi** [comment]
牛的！感谢作者推荐！
那我把这个 issue close，后续有类似问题的用户可以 refer 下~

![2023-05-24_20-12](https://github.com/pot-app/pot-desktop/assets/36265606/b054e37e-b2c9-417a-9743-47398a590bcf)

**Comment by yusanshi** [comment]
(Just a thank-you letter) 话说我在 pot 一开始出来的时候试用了下，当时因为做的还不够完善就退回到 crow translate 了。今天重新用了下体验已经很好了，已经从 crow 切过来了。谢谢作者！

**Comment by Pylogmon** [comment]
X11下现在确实可用性挺高了，但是Wayland下体验还不是很好，感谢支持

**Comment by detiam** [comment]
@Pylogmon @yusanshi 
> 是linux吗？Windows和MacOS都会有窗口阴影，这样的效果比单纯的边框要好，linux因为不同的窗口管理器实现不同，所以tauri并没有支持，你可以试着手动去设置，如果没法设置那就只能是加个边框了。

其实 [tauri-apps/window-shadows](https://github.com/tauri-apps/window-shadows) 不支持linux是因为X标准下混成器没有那么多功能，不是因为碎片化。比如kde的kwin，这个混成器只有两种模式，`SSD（服务端装饰）` 和 `CSD（客户端装饰）`，SSD模式就是 [tauri-apps/window-shadows](https://github.com/tauri-apps/window-shadows) README上说的

> Shadows are controlled by the compositor installed on the end-user system.

会给窗口围一圈系统装饰，没有一点修改的权限。或者CSD模式，就是tauri设置decorations为false的样子。没有标题没有阴影，也没办法单独打开阴影，那 [tauri-apps/window-shadows](https://github.com/tauri-apps/window-shadows) 达不到效果就直接不支持linux了。

linux上的大部分CSD应用解决方法也很直接，不考虑不同的窗口管理器实现相不相同，是直接在界面上画阴影，然后把阴影那部分做成半透明和不响应鼠标点击，比如下面视频里的火狐，用快捷键 `shift`+`alt`+`f12` 关掉混成器（kwin）后SSD应用都没阴影了但它还有（虽然因为kwin的半透明效果没了变成一团黑），因为就是主界面的一部分，如果点击就点到下面的应用程序了

https://github.com/pot-app/pot-desktop/assets/44510779/4996b9fb-5d67-4ded-ab11-fdea54956b3b


这么做的应用：Firefox<sub>`GTK`</sub>，Telegram<sub>`Qt`</sub>，[HMCL](https://github.com/huanghongxun/HMCL)<sub>`Java`</sub>，[洛雪音乐助手](https://github.com/lyswhut/lx-music-desktop)<sub>`Electron`</sub>......

所以我建议重开这个iuess >_<

ps 感谢作者做出这么好用的软件，我是从划词翻译浏览器插件关浏览器窗口后不能呼出独立翻译窗口了后切换来的，感觉这个应用是linux上最好用的划词翻译软件了

**Comment by Pylogmon** [comment]
2.0版本给窗口加了个边框，一定程度上解决了这个问题，如果要在外部手动画阴影的话，内部的界面尺寸也会受到影响，因为界面的布局大量使用了100vh这种单位，如果外部加一圈阴影的话，窗口尺寸不变，但实际展示窗口的区域变小了，内部的布局也会受到影响，而且考虑到要跨平台，我不打算为Linux单独绘制窗口阴影。

**Comment by detiam** [comment]
如果你也用kde然后找到这个地方，plasma还是有个方法可以加上阴影的：

1. 窗口上点击 `alt+f3` - 更多操作 - 配置特殊应用程序设置
2. 点击左下角 添加属性，添加 无标题栏和边框
3. 更改 无标题栏和边框 为 强制 否，边框和阴影都将被添加到窗口上
4. 到 设置 - 外观 - 窗口装饰元素 - 现在正在用的窗口装饰，比如默认的“Breeze 微风”，点击设置图标
5. 特定窗口优先规则 - 添加规则 - 检测窗口属性 - 选择 pot 窗口
6. 勾选 隐藏窗口标题栏，确认 - 确认

本质是强制加上服务端窗口标题，装饰，然后到对应窗口装饰的设置里隐藏标题栏部分
