### ISSUE TITLE
[BUG]: 翻译失败不应当写入剪贴板，翻译结果写入剪贴板不应当响应在剪贴板监听中读取并响应

### ISSUE THREAD

**Issue by kihlh** [pot-app/pot-desktop#140]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 问题描述

如图所示
![动画2](https://github.com/pot-app/pot-desktop/assets/62889891/ddffa449-534a-4813-b8c8-1045de0cbbcc)

### 如何复现

每次复现 开启剪贴板监听 和 自动剪贴板写入 时 

### 操作系统

Windows

### 操作系统版本

Windows10 专业版

### 窗口系统(Linux Only)

None

### 软件版本

pot:0.4.0  Tauri:1.3.0

**Comment by Pylogmon** [comment]
另一个问题见 #130
