### ISSUE TITLE
[Feature]: 希望pot拥有 DeepL 的 Ctrl+C +C 响应的快捷键应用于划词快捷键

### ISSUE THREAD

**Issue by kihlh** [pot-app/pot-desktop#141]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 需求描述

第一遍Ctrl的时候是复制  在600ms内没有释放Ctrl键 再执行一次C则响应划伺翻译  直接从剪贴板读取

### 应用场景

DeepL 此功能真的很好用 可惜他的翻译API 很容易因为网络问题调用失败

### 参考资料

DeepL桌面端默认的快捷键
![image](https://github.com/pot-app/pot-desktop/assets/62889891/f414e74d-ae32-4cad-976c-2c1b20433dbb)

**Comment by Pylogmon** [comment]
不打算实现非标准的快捷键
