### ISSUE TITLE
[BUG]: Wayland 划词窗口无法读取选中的文本

### ISSUE THREAD

**Issue by FlysoftBeta** [pot-app/pot-desktop#147]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 问题描述

使用[文档中的教程](https://pot.pylogmon.com/docs/tutorial/config/shortcut_config#%E4%BD%BF%E7%94%A8%E7%B3%BB%E7%BB%9F%E5%BF%AB%E6%8D%B7%E9%94%AE)设置了快捷键，但弹出的划词窗口无法读取到选中的文本
快捷键配置：
![图片](https://github.com/pot-app/pot-desktop/assets/49718840/26d7b34b-7fcc-405a-853c-1870d867a61f)
效果：
![图片](https://github.com/pot-app/pot-desktop/assets/49718840/a7749f15-9384-41cf-a1a8-e53c3f127077)

### 如何复现

使用[文档中的教程](https://pot.pylogmon.com/docs/tutorial/config/shortcut_config#%E4%BD%BF%E7%94%A8%E7%B3%BB%E7%BB%9F%E5%BF%AB%E6%8D%B7%E9%94%AE)设置快捷键，选择文本并按下快捷键弹出一个空白的划词窗口。

### 操作系统

Linux

### 操作系统版本

Ubuntu 23.04
GNOME 44

### 窗口系统(Linux Only)

Wayland

### 软件版本

pot:0.4.2  Tauri:1.3.0

**Comment by Pylogmon** [comment]
已知问题，虽然说软件已经支持了Wayland取词，但是经过测试发现，只有KDE的Wayland支持了Primary剪切板，所以在Gnome下还没法使用。

暂时的解决办法：

添加环境变量以在xwayland下运行

```bash
XDG_SESSION_TYPE=x11 GDK_BACKEND=x11 pot
```

注意，是在pot启动是时候添加这两个变量来启动，设置快捷键的时候不需要添加变量。

**Comment by FlysoftBeta** [comment]
感谢，添加参数后已经可以使用

**Comment by linsui** [comment]
我目前打包 pot 的时候加了[这个](https://github.com/NixOS/nixpkgs/pull/232836/files#diff-4be8b3b2e02d5c41d976db81110fa364614afbb4d3c2e8c4e162544f7baaadefR116)。

**Comment by Pylogmon** [comment]
不熟悉nix，这个加上之后是只对这个软件包起作用的吗？

**Comment by linsui** [comment]
是的，这个是加到 wrapper 里的，只对这个文件起作用

**Comment by Pylogmon** [comment]
好的，感谢

**Comment by linsui** [comment]
我是想，是不是可以检测 GNOME 然后默认用 xorg？就和 https://github.com/pot-app/pot-desktop/blob/0.3.6/src-tauri/src/main.rs#L34 差不多

**Comment by Pylogmon** [comment]
用`XDG_CURRENT_DESKTOP`判断不是KDE会不会好一点，目前测试其实只有KDE可用

**Comment by linsui** [comment]
https://superuser.com/questions/96151/how-do-i-check-whether-i-am-using-kde-or-gnome 里有不少判断方法，我只是随便选了个能用的，没有在其他桌面上测试

**Comment by Pylogmon** [comment]
> 我是想，是不是可以检测 GNOME 然后默认用 xorg？就和 [`0.3.6`/src-tauri/src/main.rs#L34](https://github.com/pot-app/pot-desktop/blob/0.3.6/src-tauri/src/main.rs?rgh-link-date=2023-05-27T07%3A32%3A54Z#L34) 差不多

我可以试试，实际上我是可以判断是否支持primary clipboard的，最近一直没来得及加。

**Comment by linsui** [comment]
那样确实更优雅，这只是个临时解决方案。

**Comment by Pylogmon** [comment]
我不确定能不能行，因为我觉得GDK_BACKEND只在第一行加有效，一旦tauri跑在原生Wayland下，我觉得加他其实没啥用了。

**Comment by Pylogmon** [comment]
已修复，Ubuntu虚拟机测试了一下，应该很完美。

**Comment by linsui** [comment]
我测试了一下 0.4.3，遇到了一个奇怪的问题，但我不知道怎么复现。输出是

```
$ pot
get_selection_text_on_wayland
Check Primary Selection Support Failed
get_selection_text_on_x11
```

在使用快捷键之前窗口可以显示。使用快捷键之后翻译窗口不显示，设置窗口是空的。

**Comment by Pylogmon** [comment]
快捷键是系统快捷键吗，设置窗口是空的是什么意思

**Comment by linsui** [comment]
![image](https://github.com/pot-app/pot-desktop/assets/36977733/5a730aef-3574-4df2-a742-fab451cacf8b)
快捷键是绑定的 pot translate，在终端里运行也是一样的。

**Comment by Pylogmon** [comment]
奇怪了，把配置文件删了试试

**Comment by linsui** [comment]
没有变化。

**Comment by Pylogmon** [comment]
删了之后重启试试吧，我在arch 和 ubuntu下都没遇到这问题。

**Comment by linsui** [comment]
XDG_SESSION_TYPE=x11 GDK_BACKEND=x11 pot 是没有问题的，我重启一下试试

**Comment by linsui** [comment]
重启之后还是同样的问题...

**Comment by linsui** [comment]
似乎是这个问题 https://github.com/tauri-apps/tauri/issues/5143。WEBKIT_DISABLE_COMPOSITING_MODE=1 pot 可以工作。

**Comment by Pylogmon** [comment]
0.4.2没有这个问题吗

**Comment by linsui** [comment]
之前没有遇到这个问题，不知道是怎么触发的。

**Comment by Pylogmon** [comment]
修了，感谢🙏

**Comment by linsui** [comment]
我这里 pot 0.4.4 一切正常，谢谢！
