### ISSUE TITLE
[Feature]: 删除多余空格空行可以增加一个一直开启的选项吗

### ISSUE THREAD

**Issue by Beacon0219** [pot-app/pot-desktop#148]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 需求描述

删除多余空格空行可以增加一个一直开启的选项吗，读pdf论文有时候经常跨行选中翻译，需要一个一个按删除空格空行

### 应用场景

读pdf论文会高血压(

**Comment by Pylogmon** [comment]
有设置项了
