### ISSUE TITLE
[BUG]: 辅助功能勾选后打开pot仍弹出辅助功能访问

### ISSUE THREAD

**Issue by stbcdv** [pot-app/pot-desktop#149]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 问题描述

pot需要访问辅助功能以控制电脑，但是勾选后并不起效，再次打开pot后仍弹出 pot需要访问辅助功能以控制电脑, 勾选

### 如何复现

4.3和4.4出现该问题，4.2 正常，只要更新或者安装4.3和4.4版本，第一次启动就会出现

### 操作系统

MacOS

### 操作系统版本

系统 macos 12.6.6，2020年13英寸intel

### 窗口系统(Linux Only)

None

**Comment by Pylogmon** [comment]
去设置辅助功能页面把pot删了然后手动添加

**Comment by stbcdv** [comment]
问题解决了
