### ISSUE TITLE
[BUG]: 划词翻译窗口无法拖动

### ISSUE THREAD

**Issue by shang-zhen** [pot-app/pot-desktop#150]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 问题描述

调出划词翻译窗口后，拖动状态栏，界面就会消失。

### 如何复现

快捷键调用-》拖动界面

### 操作系统

Windows

### 操作系统版本

win10

### 窗口系统(Linux Only)

None

### 软件版本

0.4.4

**Comment by Pylogmon** [comment]
行，算你关的快😂

**Comment by shang-zhen** [comment]
> 行，算你关的快😂

😁
