### ISSUE TITLE
是否可以新增几个国家语言，我可以付费增加！

### ISSUE THREAD

**Issue by yingzi006688** [pot-app/pot-desktop#151]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 需求描述

是否可以新增几个国家语言，我可以付费增加！我想要增加泰语 越南语 印尼语 葡萄牙语

### 应用场景

是否可以新增几个国家语言，我可以付费增加！我想要增加泰语 越南语 印尼语 葡萄牙语

**Comment by Pylogmon** [comment]
好的，会支持的，刚开始的时候为了方便就先放了一部分常用的，不过如果说你是要把这些语言翻译为中文，使用自动检测->中文目前其实是可以翻译的，如果要翻译成这些语言那就得等我更新一下语言列表了。
