### ISSUE TITLE
[BUG]: 接口设置拉到最下，别的 tab 位置也上去下不来了。

### ISSUE THREAD

**Issue by wuyudi** [pot-app/pot-desktop#152]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 问题描述

RT

### 如何复现

现在正常

![image](https://github.com/pot-app/pot-desktop/assets/30024051/a065f843-b466-447a-989b-f34e7584d79d)

把接口设置拉到最下

![image](https://github.com/pot-app/pot-desktop/assets/30024051/1e6af6e3-e8d7-4d48-a18d-8bcafb4ebe0a)

然后

![image](https://github.com/pot-app/pot-desktop/assets/30024051/4741d497-e6ba-462e-84a0-24321d0104bf)

就没了，修复方法是把接口设置拉回最上。

观察了下发现是用了同一个位置。但是前几个没有右边的拉动条，界面就在上面下不来了。

### 操作系统

Linux

### 操作系统版本

OS: Arch Linux x86_64

### 窗口系统(Linux Only)

Wayland

### 软件版本

0.4.4

**Comment by wuyudi** [comment]
[pot_0.4.4_amd64.deb](https://github.com/pot-app/pot-desktop/releases/download/0.4.4/pot_0.4.4_amd64.deb)
[pot_0.4.4_amd64_universal.deb](https://github.com/pot-app/pot-desktop/releases/download/0.4.4/pot_0.4.4_amd64_universal.deb)

以及这两个的区别是？

**Comment by Pylogmon** [comment]
> [pot_0.4.4_amd64.deb](https://github.com/pot-app/pot-desktop/releases/download/0.4.4/pot_0.4.4_amd64.deb)
> [pot_0.4.4_amd64_universal.deb](https://github.com/pot-app/pot-desktop/releases/download/0.4.4/pot_0.4.4_amd64_universal.deb)
> 
> 以及这两个的区别是？

glibc和openssl版本不同，universal是用debian10编译的，基于glibc2.28和openssl1.1，另一个是ubuntu22.04编译的glibc版本要高一些openssl使用3.0版本
