### ISSUE TITLE
[Feature]: 窗口和文字太大了，可以调小一号就好了

### ISSUE THREAD

**Issue by pheotry** [pot-app/pot-desktop#154]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 需求描述

目前窗口显示太大，感觉太占地方了，字体以及窗口图标小一号就好了

### 应用场景

笔记本屏幕实在太小了

### 参考资料

![image](https://github.com/pot-app/pot-desktop/assets/43376740/44ae387c-1460-47a4-ab1c-424a929e54be)

**Comment by Pylogmon** [comment]
有人觉得大，有人觉得小，我打算等tauri支持zoom之后添加一个更改缩放的选项

**Comment by pheotry** [comment]
> 有人觉得大，有人觉得小，我打算等tauri支持zoom之后添加一个更改缩放的选项

大佬，这里好像是说支持缩放了，但需要自己实现一下
https://github.com/tauri-apps/wry/issues/569#issuecomment-1118668839

**Comment by Pylogmon** [comment]
https://github.com/tauri-apps/tauri/issues/3310#issuecomment-1251626389

> even though it landed in upstream, tauri still needs to expose it.

**Comment by Dolphin4mi** [comment]
是否可以增加改变字体大小的选项，dpi和缩放不一样需求太多了。

**Comment by Pylogmon** [comment]
调整字体大小，只能调整源文本和翻译文本的字体大小，其他字体如果不整体缩放直接改字体大小会很丑的
