### ISSUE TITLE
[Feature]: 增加更多词典

### ISSUE THREAD

**Issue by NNGTHB** [pot-app/pot-desktop#155]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 需求描述

增加有道词典、剑桥词典、沪江小D、MOJi辞書（日）、句酷等词典

### 应用场景

虽然翻译的接口很丰富，但目前只有bing词典，查词的需求有点满足不了，需要更多优秀和经典的词典。

**Comment by Pylogmon** [comment]
其实Google翻译也能查词的

**Comment by Pylogmon** [comment]
你说的这些词典都有开放的API吗？

**Comment by NNGTHB** [comment]
> 你说的这些词典都有开放的API吗？

有的，因为我看沙拉查词能调用这些词典

**Comment by Pylogmon** [comment]
除了有道，其他的我都没有找到开放的api

**Comment by NNGTHB** [comment]
> 除了有道，其他的我都没有找到开放的api

试了一下沪江小D和句酷已经用不了了，忽略。剑桥和MOJi辞書在沙拉查词中还能用

剑桥词典：https://dictionary-api.cambridge.org/

MOJi辞書确实没找到API，只能看看下面的能不能作为参考...
https://github.com/Yukaii/mojidict-helper
https://www.shareintelli.com/mojidict-help/
https://blog.csdn.net/tomatohust/article/details/113904081
