### ISSUE TITLE
[Feature]: 语境中翻译

### ISSUE THREAD

**Issue by NNGTHB** [pot-app/pot-desktop#157]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 需求描述

不知道能不能做到划单个词的时候提取上下文，并同时给出单词和所在句子的翻译。

### 应用场景

用ChatGPT分析单词所在句子的语境并给出更贴切的翻译

**Comment by Pylogmon** [comment]
软件定位只是一个翻译工具，并不是学习软件，OpenAI只是其中一个接口而已，不打算做太过深入的绑定，建议给隔壁 [OpenAI-Translator](https://github.com/openai-translator/openai-translator) 提issue
