### ISSUE TITLE
[BUG]: pot translate 启动时不翻译

### ISSUE THREAD

**Issue by linsui** [pot-app/pot-desktop#158]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 问题描述

运行 pot translate 如果没有已经在运行的实例，不会开始翻译。再次运行才会开始翻译。

### 如何复现

关闭正在运行的实例。运行 pot translate。没有弹窗。再次运行正常翻译。

### 操作系统

Linux

### 操作系统版本

NixOS

### 窗口系统(Linux Only)

Wayland

### 软件版本

0.4.4

**Comment by Pylogmon** [comment]
正常

**Comment by Pylogmon** [comment]
设计之初就是让pot在运行时通过单例检测拿命令行参数的，这个并不是启动参数

**Comment by linsui** [comment]
就是说 `translate` 在启动时并不会被读取吗？我明白了

**Comment by Pylogmon** [comment]
是的
