### ISSUE TITLE
[BUG]: 提示病毒

### ISSUE THREAD

**Issue by zhl111** [pot-app/pot-desktop#159]
### 提交新Issue前请确认一下事项

- [X] 我已确认以上事项

### 问题描述

![image](https://github.com/pot-app/pot-desktop/assets/29135984/127e7376-3bf0-4816-8fe8-101c4cbc8b11)

### 如何复现

安装版和portable的都报毒

### 操作系统

Windows

### 操作系统版本

Windows11 家庭版 22621.1702

### 窗口系统(Linux Only)

None

**Comment by Pylogmon** [comment]
误报，忽略就好，我也遇到过，不知道为啥
