### ISSUE TITLE
[BUG]: Windows多屏幕下，弹窗显示位置错误

### ISSUE THREAD

**Issue by AlphaBoom** [pot-app/pot-desktop#175]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### 弹窗位置向上偏移，现象如下：
![image](https://github.com/pot-app/pot-desktop/assets/30779939/8e5822fe-ad11-48e3-b22b-36c2b33f2fdd)
### 原因是我的屏幕设置如下，出问题位置是箭头指向：
![image](https://github.com/pot-app/pot-desktop/assets/30779939/7b750a81-723b-47e5-b01b-9cd0056349ef)
### 问题原因：
可以看到屏幕1是主显示器并且屏幕1要比屏幕2高，然后通过WINAPI获取的y坐标是按照屏幕1为基准计算的，所以导致处理屏幕2边界情况的代码出现了问题。
相关代码在这里：
```rust
fn convert_mouse_location(
    location: (f64, f64),
    monitor: tauri::Monitor,
) -> Result<(f64, f64), String> {
    let (mut x, mut y) = location;
    let (width, height) = get_window_size();
    let monitor_size = monitor.size();
    let dpi = monitor.scale_factor();
    x /= dpi;
    y /= dpi;
    if x + width > monitor_size.width as f64 / dpi {
        x -= width;
        if x < 0.0 {
            x = 0.0;
        }
    }
    // 这里限制y导致了问题，去掉后显示正常
    if y + height > monitor_size.height as f64 / dpi {
        y -= height;
        if y < 0.0 {
            y = 0.0;
        }
    }

    Ok((x, y))
}
```

### Reproduction

见Description

### Platform

Windows

### System Version

Windows11

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
实际上和 #94 是同一个问题

**Comment by AlphaBoom** [comment]
嗯嗯，可以考虑参考下AutoHotKey的实现？我这用的脚本是能正确找到各个屏幕中心位置的。
https://github.com/AutoHotkey/AutoHotkey/blob/df84a3e902b522db0756a7366bd9884c80fa17b6/source/lib/env.cpp
