### ISSUE TITLE
[BUG]: deepl interface doesn't work only when target language is Korean

### ISSUE THREAD

**Issue by colababa** [pot-app/pot-desktop#181]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

When using deepl, I get "Unsupported Language" error when target language is Korean, it does not occur when target language is not Korean (Chinese / Japanese)
(Maybe deepl target language parameter is wrong?)

### Reproduction

1. In settings, set target language to Korean, and add DeepL to default interface.
2. Launch translation window and translate.
3. See "Unsupported Language" error.
4. You can check other languages are working well by changing target language and translate again

### Platform

Windows

### System Version

Windows 10 Pro 19045.3031

### Window System(Linux Only)

None

### Software Version

pot:0.5.0  Tauri:1.3.0

**Comment by Pylogmon** [comment]
Thanks for the feedback, I just checked the code and I did miss Korean in the language list, I will fix this in the next release.

**Comment by colababa** [comment]
Thanks for the quick response!
