### ISSUE TITLE
[BUG]: title MAC的翻译小窗口关闭最小化和功能性按钮重叠

### ISSUE THREAD

**Issue by yeungxing** [pot-app/pot-desktop#185]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

![image](https://github.com/pot-app/pot-desktop/assets/44627884/0a398f9b-2022-4c42-a9d4-3c156f18f281)
如图所示， MAC 因为关闭刚好跟 win 反过来，这个功能按钮能不能给整到右侧，或者出个设置可以调位置呀，从 BOB 过来了，因为家里都是 win ，由于习惯原因自己也转投 POT 了

### Reproduction

快捷翻译窗口

### Platform

MacOS

### System Version

mac 10.15.7

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
这个问题我处理过，在高版本MacOS上应该是正常的，你使用的是最新版pot吗，如果是的话我只能试着去修，因为我没有设备去测试。后续有问题欢迎继续反馈。

**Comment by yeungxing** [comment]
> <img alt="@Pylogmon" width="20" height="20" src="https://avatars.githubusercontent.com/u/59004461?s=40&amp;u=1d2d5972a833cbda224caf07c52c40dd6e3df9d4&amp;v=4">

是最新的 0.51，不耽搁用反正，我一会用朋友m1 的 mac 看看是不是再给您反馈
