### ISSUE TITLE
[BUG]: snipDo插件问题

### ISSUE THREAD

**Issue by gc89925** [pot-app/pot-desktop#188]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

使用下来软件本身没问题，但是装了snipDo插件开启以后，玩英雄联盟卡顿，掉帧，闪屏。关掉snipDo以后恢复正常。其实不应该提交到这里，只是想让更多人看到

### Reproduction

开启snipDo插件，即使不启动，也会这样

### Platform

Windows

### System Version

版本	Windows 11 专业版
版本	22H2
安装日期	‎2023/‎4/‎25
操作系统版本	22621.1778
体验	Windows Feature Experience Pack 1000.22642.1000.0

### Window System(Linux Only)

None

**Comment by jlduu** [comment]
不可以在pot实现点击图标的划词翻译吗？必须借助snipDo，装了后发现这个软件好几百兆

**Comment by Pylogmon** [comment]
> 不可以在pot实现点击图标的划词翻译吗？必须借助snipDo，装了后发现这个软件好几百兆

这个问题我在小众的论坛上回答过一次，我直接复制过来：

如果我只是搞一个Windows软件或者Linux软件，我肯定就实现了，但是我要考虑跨平台，同时在三个平台实现这个与桌面深度交互的功能还是有些难度的，就算我实现了，体验也未必有这些现成的软件好。就比如MacOS，我甚至没有Mac设备来进行开发，而popclip作为一个知名的Mac软件他在这方面的体验是非常棒的，所以我想要在三个平台下都以这样的形式来支持。

**Comment by Pylogmon** [comment]
SnipDo会监听鼠标事件，这没办法，游戏的时候最好还是关了吧
