### ISSUE TITLE
[BUG]: OCR 功能首次使用载入数据集失败

### ISSUE THREAD

**Issue by Guwalgiyakuan** [pot-app/pot-desktop#189]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

装上新版试用OCR功能载入数据集超时提示：TypeError: Load failed

### Reproduction

退出重启pot还是出现同样错误

### Platform

Linux

### System Version

OS: Ubuntu 22.04.2 LTS x86_64 
DE: GNOME 42.5 

### Window System(Linux Only)

X11

### Software Version

1.0.0

### Additional Information

![截图 2023-06-06 21-15-41](https://github.com/pot-app/pot-desktop/assets/37359970/dc21722a-8547-454f-9b88-6c5ee26aaca1)

**Comment by Pylogmon** [comment]
确实下载很慢，甚至会下载失败，开全局代理就可以了，后续我也会想办法来解决

**Comment by Guwalgiyakuan** [comment]
国内这环境难道逼得每个软件都要加个代理设置选项？

**Comment by Pylogmon** [comment]
没办法🙃，提醒一下嗷，下载这个软件内代理不起作用的，得开全局代理，再不行就tun

**Comment by Guwalgiyakuan** [comment]
> 没办法upside_down_face，提醒一下嗷，下载这个数据集，软件内代理是不起作用的，得开全局代理，再不行就tun

难住了..... Linux下全局代理方法还没学会 😒 可否给个关键词我去找找

**Comment by Pylogmon** [comment]
ubuntu在系统设置里面设置手动代理就可以了呀

**Comment by Guwalgiyakuan** [comment]
![图片](https://github.com/pot-app/pot-desktop/assets/37359970/4f174b6d-ce2f-40ea-b04b-facc4474c2b9)
还是翻译好用，OCR不行

**Comment by Pylogmon** [comment]
不好意思，格式有误

**Comment by Guwalgiyakuan** [comment]
> 不好意思，格式有误

没问题  等修复。辛苦了。

**Comment by Pylogmon** [comment]
我发现除了下载慢在Linux下还有其他问题，tessseract.js的fetch会触发跨域，在Windows下没有这个问题，据tauri的相关issue来看，应该是webkit2gtk的问题，所以tesseract接口在Linux下不可用。

**Comment by Pylogmon** [comment]
> 我发现除了下载慢在Linux下还有其他问题，tessseract.js的fetch会触发跨域，在Windows下没有这个问题，据tauri的相关issue来看，应该是webkit2gtk的问题，所以tesseract接口在Linux下不可用。

已修复
