### ISSUE TITLE
[Feature]: OCR能否支持在线的api

### ISSUE THREAD

**Issue by a15355447898a** [pot-app/pot-desktop#191]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

OCR目前使用的是本地的Tesseract OCR,存在准确度底下,速度较慢以及占用本地cpu等问题,而且首次使用下载训练集对国内用户来说不太友好.

### Application Scenario

在线的ocr准确率比本地的ocr高很多,可以带来更棒的使用体验

**Comment by Pylogmon** [comment]
会添加的，这个只是一个不需要配置的拿来作为默认的
