### ISSUE TITLE
[BUG]: 截图OCR对于多屏幕用户来说存在问题

### ISSUE THREAD

**Issue by a15355447898a** [pot-app/pot-desktop#192]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

在托盘点击了"截图OCR",然后只在其中一个屏幕上面出现了OCR截图框

https://github.com/pot-app/pot-desktop/assets/62456287/5ae9573e-03de-43c8-8b6f-300ee1211577

### Reproduction

多屏幕,然后"截图OCR"

### Platform

Windows

### System Version

windows 11 专业版 22621.1702

### Window System(Linux Only)

None

### Software Version

1.0.0

**Comment by Pylogmon** [comment]
这不算bug吧，你在哪个屏幕上使用，鼠标不应该就在哪个屏幕上吗，我是根据鼠标位置来判断的

**Comment by a15355447898a** [comment]
> 这不算bug吧，你在哪个屏幕上使用，鼠标不应该就在哪个屏幕上吗，我是根据鼠标位置来判断的

问题就在于为什么我在左边的屏幕上面点了"截图OCR",但是OCR框选在右边的屏幕上

**Comment by Pylogmon** [comment]
啊，是我没看明白，用快捷键调用的时候正常吗

**Comment by a15355447898a** [comment]
> 啊，是我没看明白，用快捷键调用的时候正常吗

不正常,一样

**Comment by Pylogmon** [comment]
是无论在哪块屏幕上启动都会到右边还是说是交叉的

**Comment by a15355447898a** [comment]
> 是无论在哪块屏幕上启动都会到右边还是说是交叉的

使用快捷键时,无论鼠标在哪个屏幕上,都是在右边屏幕启动
