### ISSUE TITLE
[BUG]: Azure OpenAI 接口怎么填写调用呢？一直调用失败，OpenAI API倒是很容易成功。

### ISSUE THREAD

**Issue by TuningZhou** [pot-app/pot-desktop#194]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

Azure OpenAI 接口怎么填写调用呢？一直调用失败，OpenAI API倒是很容易成功。

### Reproduction

Azure OpenAI 接口怎么填写调用呢？一直调用失败，OpenAI API倒是很容易成功。

### Platform

Windows

### System Version

Windows 11 家庭中文版 22H2
操作系统版本为：22621.170

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
自定义域名写你的endpoint，不要加协议头
请求路径参照Azure文档填写，类似这样：`/openai/deployments/{YOUR-DEPLOYMENT_NAME_HERE}/chat/completions?api-version=2023-05-15`
OpenAI服务选择Azure

**Comment by TuningZhou** [comment]
OK。谢谢大佬。已经成功使用到Azure OpenAI了。
