### ISSUE TITLE
[BUG]: linux下面ocr的框选区域显示不对

### ISSUE THREAD

**Issue by a15355447898a** [pot-app/pot-desktop#195]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

选择截图OCR,框选区域显示问题(只显示了一条线)

### Reproduction

https://github.com/pot-app/pot-desktop/assets/62456287/8384cd94-7c51-434a-a037-32a8ed797fc1

### Platform

Linux

### System Version

arch linux

### Window System(Linux Only)

X11

### Software Version

1.1.1

**Comment by Pylogmon** [comment]
archlinux KDE没能复现

**Comment by Guwalgiyakuan** [comment]
Ubuntu 22.04 gnome 下无论是点击截图OCR还是截图翻译都是截取整个屏幕，无法选择区域。
![图片](https://github.com/pot-app/pot-desktop/assets/37359970/1b1f1f09-8f09-46f9-8f31-64b4ee41a717)

**Comment by Pylogmon** [comment]
> Ubuntu 22.04 gnome 下无论是点击截图OCR还是截图翻译都是截取整个屏幕，无法选择区域。
>

Wayland暂不支持，因为获取到的DPI是错的，x11的问题修复了，下个版本就好了。

**Comment by Guwalgiyakuan** [comment]
> > Ubuntu 22.04 gnome 下无论是点击截图OCR还是截图翻译都是截取整个屏幕，无法选择区域。
> 
> Wayland暂不支持，因为获取到的DPI是错的，x11的问题修复了，下个版本就好了。

我使用的是X11，Wayland 因为不支持 wine 应用没使用。

**Comment by Guwalgiyakuan** [comment]
升级到1.6.1版本问题都解决了在我这里

**Comment by Pylogmon** [comment]
请问问题是否仍然存在 @a15355447898a

**Comment by a15355447898a** [comment]
> 请问问题是否仍然存在 @a15355447898a

还是一样,在archlinux下面,kde(x11)环境下,笔记本双屏幕环境,主屏幕核显,副屏幕nvidia独显,使用nvidia-dkms驱动,内核是linux-clear
使用pot-translation-bin这个包

**Comment by Pylogmon** [comment]
麻烦反馈一下，问题是否依然存在。

**Comment by a15355447898a** [comment]
在kde+wayland下面测试,工作已经正常
