### ISSUE TITLE
[Feature]: 快捷键建议

### ISSUE THREAD

**Issue by shang-zhen** [pot-app/pot-desktop#198]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

快捷键打开界面 能不能设置成打开软件界面后，再次按快捷键为隐藏？
不用每次打开后需要鼠标点击一次关闭按钮。。。

### Application Scenario

lasted

**Comment by Pylogmon** [comment]
esc可以关闭

**Comment by hu3rror** [comment]
虽然已经 Close Issue，但这个 Esc 退出体验确实不佳。

常见的快捷键都是 Ctrl/Alt/Super 来作为修饰键，搭配某个字母按键。手的位置会在左下角，而 Esc 在左上角。

若搭配自动检测剪切板内容翻译，当获知翻译内容，我的手部可以完全停留在左下角，马上再按一次快捷键便可关闭。这个操作流我认为是合理且流畅的。希望作者可以再考虑一下这个 issue 的提议。

**Comment by Pylogmon** [comment]
Esc关闭窗口，基本上是大部分软件的共识了，并不是我设置了一个另类的快捷键用来关闭窗口。

对于划词窗口来说，失去焦点就会自动关闭，也并不需要手动关闭。

另外，目前窗口打开时再次按下快捷键，窗口会聚焦，还会再次取词，跟这相关的还有增量翻译功能。

这一操作是为了明确的功能需求而设计的，不可能把它改成关闭窗口。
