### ISSUE TITLE
[BUG]: portable 版本更新会默认安装在 C 盘而不是覆盖

### ISSUE THREAD

**Issue by powerpuffaks** [pot-app/pot-desktop#200]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

使用的是 portable 的版本，版本更新只会在C盘重新安装，而不会覆盖 portable 的版本

### Reproduction

1. 启动低版本的 portable 文件
2. 检查更新
3. 执行更新
4. portable 版本不会更新，C 盘被安装了最新的版本

### Platform

Windows

### System Version

![图片](https://github.com/pot-app/pot-desktop/assets/122727212/7afc71d4-6201-4d86-a62a-5251b8086013)

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
便携版不要使用应用内更新，我官网说了的
![image](https://github.com/pot-app/pot-desktop/assets/59004461/788e9e10-6810-41b4-9388-18247cb7fc25)
