### ISSUE TITLE
[BUG]: 百度OCR接口调用错误

### ISSUE THREAD

**Issue by CarlSmith6688** [pot-app/pot-desktop#210]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

在升级到1.3版本后原有的【百度OCR】接口调用时提示Unsupported Language，使用相同的api密钥和key填入【百度OCR(高精度)】选项时调用成功，多次尝试问题复现率100％

### Reproduction

![复现过程](https://github.com/pot-app/pot-desktop/assets/105553213/96dc90d3-c46a-4a55-930b-d3dd1c5c5500)

### Platform

Windows

### System Version

Windows 10 Professional 19043.1826

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
百度OCR标准版是不支持自动检测的，高精度版可以的，上个版本实际上用的是高精度版

**Comment by CarlSmith6688** [comment]
好的感谢解答
