### ISSUE TITLE
[Feature]: 添加图片翻译功能

### ISSUE THREAD

**Issue by softmetal66** [pot-app/pot-desktop#211]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

目前已经有了截屏翻译，希望能在此基础上添加图片翻译功能，就是截屏后不提取文字，而是直接输出翻译好的图片

### Application Scenario

目前已经有了截屏翻译，希望能在此基础上添加图片翻译功能，就是截屏后不提取文字，而是直接输出翻译好的图片，这样排版不会乱，特别适合听讲座、看论文时使用
目前已有的多为上传本地图片翻译，如果能截屏后直接翻译，那软件就无敌了

预期效果图：
![image](https://github.com/pot-app/pot-desktop/assets/112331657/d30715a3-7baf-456c-99fe-012190a20c52)

目前能直接使用的网站（上传图片翻译）：
谷歌 https://translate.google.com/?hl=zh-CN&tab=TT&sl=auto&tl=zh-CN&op=images
搜狗 https://fanyi.sogou.com/picture

有免费API的：
百度图片翻译 https://ai.baidu.com/ai-doc/MT/dkifdqg54
腾讯图片翻译 https://bobtranslate.com/service/ocr/tencentimagetranslate.html#_0-%E6%94%B6%E8%B4%B9%E6%A8%A1%E5%BC%8F

**Comment by Pylogmon** [comment]
在现有的交互逻辑上，这个功能应该加到哪里呢，放到翻译接口里面的话，他和其他翻译接口输入参数不同，划词翻译的时候他没法用，放到截图翻译里面，最终的效果就是源文本变成了图片翻译的结果，后续又会调用其他翻译接口对这个结果进行翻译，看起来好像只能是放到ocr接口里面，作为一个特殊的ocr接口。

**Comment by Pylogmon** [comment]
![image](https://github.com/pot-app/pot-desktop/assets/59004461/63baf3e6-b43c-4633-af6d-c77f80e2e6a1)
![image](https://github.com/pot-app/pot-desktop/assets/59004461/395f4280-422b-4e18-9c2e-4a4c36ba38ab)

也只能是这样了，因为上面所说的比较矛盾的原因，用腾讯图片翻译接口进行截图翻译操作的时候，我是将识别后但未翻译的文本放在了原文区域，然后交给其他翻译接口来翻译的。

**Comment by Pylogmon** [comment]
> 就是截屏后不提取文字，而是直接输出翻译好的图片

刚刚看到你说的这句话，图片翻译api的输出结果也只是翻译后的文本，以及坐标信息，并没有返回翻译后的图片，网页上的效果是把翻译后的文字叠加到图片上对应坐标后的效果

**Comment by Pylogmon** [comment]
我前面说了，图片翻译的接口返回的也只是文本和坐标，这种效果是把文字覆盖到图片上层实现的

**Comment by Pylogmon** [comment]
基本上所有的接口都会返回坐标，后续我可能会做一个把文字覆盖到图片上的功能，也可能不做，看实现难度怎么样。

**Comment by Eyion** [comment]
这个跟将图片上的文字先ocr，然后翻译，再回填译文，是一样的吗？
如果是，能导入本地图片进行翻译回填吗？
这个功能还挺不错的。

**Comment by dalefengs** [comment]
> 这个跟将图片上的文字先ocr，然后翻译，再回填译文，是一样的吗？ 如果是，能导入本地图片进行翻译回填吗？ 这个功能还挺不错的。

是这样的，希望3.0能有这个特性
![image](https://github.com/pot-app/pot-desktop/assets/58434904/5b79810a-08b8-4545-a36b-0caba95f4535)
