### ISSUE TITLE
[BUG]: 截图翻译识别不出来内容，但是截图OCR内容是可以正常显示的

### ISSUE THREAD

**Issue by pheotry** [pot-app/pot-desktop#212]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

截图OCR是正常的，说明数据应该是下载下来了
截图翻译：
![image](https://github.com/pot-app/pot-desktop/assets/43376740/7b97b2ce-5d73-4ef7-b447-81bffb1f3170)

截图OCR：
![image](https://github.com/pot-app/pot-desktop/assets/43376740/bc2c8dd5-3f39-44b6-aed9-c46a418f64a9)

### Reproduction

托盘右键菜单或者快捷键触发截屏翻译

### Platform

Windows

### System Version

Windows 11 Pro 22621.1778

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
没有复现

**Comment by pheotry** [comment]
> 没有复现

这会儿又好了，就是这个识别速度有没有提升空间啊

**Comment by Pylogmon** [comment]
在线ocr的速度都很快，这个Tesseract是本地的，他不支持自动检测语言，目前的自动检测我是把所有语言数据都加载上然后识别的，这样就会很慢，如果你指定语言的话还是很快的。

**Comment by pheotry** [comment]
> 在线ocr的速度都很快，这个Tesseract是本地的，他不支持自动检测语言，目前的自动检测我是把所有语言数据都加载上然后识别的，这样就会很慢，如果你指定语言的话还是很快的。

原来是这样啊，我说怎么截图翻译差不多10s，截图OCR差不多一半时间，5s，仅仅指识别字的时间
