### ISSUE TITLE
[Feature]: 希望软件支持翻译并替换功能

### ISSUE THREAD

**Issue by Autumn-one** [pot-app/pot-desktop#215]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

这个功能对应两个场景
场景一：编程中的变量命名，假如想到一个变量名应该叫什么中文，但是不知道对应的英文，这个时候只需要打出中文，然后按一下快捷键即可弹出一个英文命名的列表，选中其中一个可以替换刚刚打出的中文。
场景二：翻译英文文档得到翻译之后希望在弹窗内部增加一个替换按钮，目前还需要先点击复制然后 ctrl v 来替换这个操作相对比较麻烦

### Application Scenario

场景同上

**Comment by Pylogmon** [comment]
不打算做，现在有自动复制功能，在一定程度上可以方便一些，你所描述的这种功能，对于跨平台开发很不友好，肯定会引起各种各样奇怪的问题，如果是单一平台的软件的话还可以逐渐适配，跨平台适配的话坑太多了。
