### ISSUE TITLE
[Feature]: 支持 tabs 布局的切换

### ISSUE THREAD

**Issue by Autumn-one** [pot-app/pot-desktop#216]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

目前的布局和浏览器端的沙拉查词的布局一样，这种布局在设置了多个翻译引擎的时候可能过长了，希望在弹窗内部增加按钮切换布局，从tabs布局和默认的布局中来回切换。

### Application Scenario

有些时候可能不一定需要同时看到那么多翻译引擎的结果，那么tabs布局就更舒适一点。

**Comment by Pylogmon** [comment]
我不知道你说的tabs布局是什么意思，但是你可以试试只设置一个默认翻译接口，然后翻译的时候通过下拉菜单来切换。
