### ISSUE TITLE
[BUG]: Mac 端的ocr不可以状态

### ISSUE THREAD

**Issue by justincnn** [pot-app/pot-desktop#217]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

在添加百度oct的api之后出现如下问题：
1.调出ocr翻译，系统直接出现一个screenshot的窗口，如图
2.在窗口选择需要翻译的内容，在选择**自动判断**，系统无法识别内容，除非选择中文，不让无法识别

![](https://cdn.jsdelivr.net/gh/justincnn/pictures/img/202306111551035.png)

### Reproduction

打开软件，快捷键跳出或者直接点击对应功能

### Platform

MacOS

### System Version

mac OS 13.4 (22F66)

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
1. 截图bug已知，但是我没有mac设备，暂时没有办法修复。
2. 百度通用文字识别不支持自动检测，这是接口的限制，不是bug，如果需要自动识别请切换其他接口，比如百度高精度

**Comment by justincnn** [comment]
> 1. 截图bug已知，但是我没有mac设备，暂时没有办法修复。
> 2. 百度通用文字识别不支持自动检测，这是接口的限制，不是bug，如果需要自动识别请切换其他接口，比如百度高精度

好的，感谢作者的反馈和无私工作，期待你其他作品的出现。

ps：mac其实工作效率蛮高的，可以考虑一下*⁠\⁠0⁠/⁠*
