### ISSUE TITLE
希望OCR识别增加去除换行符（\n)和空格的功能

### ISSUE THREAD

**Issue by ouening** [pot-app/pot-desktop#218]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

希望作者可以对OCR识别结果增加去除换行符（\n）和空格的功能

### Application Scenario

方便复制OCR结果，尤其对一些无法直接复制的图片扫描版PDF

**Comment by Pylogmon** [comment]
已经加了，下个版本见
