### ISSUE TITLE
[BUG]:TypeError: Load failed

### ISSUE THREAD

**Issue by CKevens** [pot-app/pot-desktop#219]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

截图翻译出现    TypeError: Load failed

### Reproduction

TypeError: Load failed

### Platform

Linux

### System Version

ubuntu22.04

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
Linux下Tesseract暂时无法使用，见https://github.com/pot-app/pot-desktop/issues/189#issuecomment-1585445047

**Comment by CKevens** [comment]
> Linux下Tesseract暂时无法使用，见[#189 (comment)](https://github.com/pot-app/pot-desktop/issues/189#issuecomment-1585445047)

thk....
