### ISSUE TITLE
[Feature]: title

### ISSUE THREAD

**Issue by Lcc1ccl** [pot-app/pot-desktop#220]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

能否增加一个翻译结果排序的功能

### Application Scenario

希望能自定义翻译结果的排序，比如我目前仅启用了OpenAI和谷歌翻译，我希望让OpenAI的翻译结果放在第一个显示

**Comment by Pylogmon** [comment]
是按照你设置的时候选择的顺序排序的，你把现在选择的接口取消选择之后按照你想要的顺序重新选择就行。
