### ISSUE TITLE
[Feature]: x86 target support

### ISSUE THREAD

**Issue by liudonghua123** [pot-app/pot-desktop#224]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

I have used some tauri for some personal projects, the most attractive to me including cross-platform, which supporting windows, linux, macos, as well as x64, x86, I see that the project ci currently does not support windows x86 and linux x86, although these targets are currently used less, but it's better than nothing, so I suggest that these targets can be compiled inside the ci.

### Application Scenario

Some old OS, or just want one binary to run on both x86 and x64 systems.

### References

https://github.com/pot-app/pot-desktop/pull/222, https://github.com/pot-app/pot-desktop/pull/223

**Comment by Pylogmon** [comment]
Awesome, welcome PR, it would be great if it could support arm, I just don't have the energy to do cross-compilation.

**Comment by liudonghua123** [comment]
> Awesome, welcome PR, it would be great if it could support arm, I just don't have the energy to do cross-compilation.

I will try to make a pr to support arm in my spare time.

**Comment by liudonghua123** [comment]
> > Awesome, welcome PR, it would be great if it could support arm, I just don't have the energy to do cross-compilation.
> 
> I will try to make a pr to support arm in my spare time.

See https://github.com/pot-app/pot-desktop/pull/234.
