### ISSUE TITLE
[Feature]: paddleocr

### ISSUE THREAD

**Issue by mymitsuha** [pot-app/pot-desktop#228]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

建议增加paddleocr

### Application Scenario

建议增加paddleocr

**Comment by Pylogmon** [comment]
我看过，不太好集成，这么多OCR还不够用吗😂

**Comment by mymitsuha** [comment]
可以增加自定义OCRapi 接口，我们可以自己搭建服务端api,只需要填入远程接口地址，以及返回的json格式
