### ISSUE TITLE
[Feature]: webdav配置同步

### ISSUE THREAD

**Issue by SDUTNB** [pot-app/pot-desktop#231]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

webdav配置同步

### Application Scenario

多设备快速同步

**Comment by deepinsc2020** [comment]
配置就一个文件 让现在的webdav软件指定路径应该暂时能凑合吧
