### ISSUE TITLE
[BUG]: mac arm64版安装后打开，显示已损坏，无法打开

### ISSUE THREAD

**Issue by hwdef** [pot-app/pot-desktop#232]
### Please confirm the following before submitting a new issue.

- [ ] I have carefully reviewed the official website's usage documentation.
- [ ] I have searched through the historical issues but could not find an answer.

### Description

![image](https://github.com/pot-app/pot-desktop/assets/13084946/88ee6913-b2aa-493b-b9dd-35712b3b35b3)

### Reproduction

1. 下载 https://github.com/pot-app/pot-desktop/releases/download/1.4.0/pot_1.4.0_aarch64.dmg
2. 安装
3. 运行

### Platform

MacOS

### System Version

13.4

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
文档都有写的

**Comment by hwdef** [comment]
6
