### ISSUE TITLE
[Feature]: 功能建议

### ISSUE THREAD

**Issue by Samenov-C** [pot-app/pot-desktop#238]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

1. 是否能加入知网CNKI翻译，或提供相应开放接口
2. windows桌面版翻译窗口，输入栏是否可以调整大小，有的文本输入后必须换行才能看全
3. windows桌面版翻译软件，各个翻译器的上下级次序是否可手动进行排序

### Application Scenario

1. 科研🐕希望能够有更专业的术语翻译功能
2. 3. 一些易用性上的建议

**Comment by Layouwen** [comment]
翻译接口的拖拽排序会在下个版本加上
1 2, 我们内部会进行评估后按情况, 开展相关的研发日程~
也欢迎使用者, 实现功能后提 pr.
后续可以关注一下更新说明, 或在相关交流群获取信息

**Comment by Pylogmon** [comment]
1. 看起来cnki的api还没有稳定，这api文档基本没法看 https://fanyi.cnki.net/serviceIntroduce/index.html

**Comment by Pylogmon** [comment]
3. 当前版本是按照你选择的顺序排序的，你可以取消选择后重新选择。
