### ISSUE TITLE
[Feature]: OCR的“写入剪切板”提示换个位置

### ISSUE THREAD

**Issue by willson83** [pot-app/pot-desktop#239]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

如果在设置--OCR设置中打开“自动复制”功能，每次OCR识别成功后，都会弹出“写入剪切板”的提示，这个提示刚好挡住了识别结果，建议在设置中增加一个开关功能，可以关闭这个提示。也建议把这个提示换个位置以防遮挡界面中的内容，谢谢

### Application Scenario

![Snipaste_2023-06-16_17-27-25](https://github.com/pot-app/pot-desktop/assets/50647223/619807e9-3ce4-4966-9c13-021153c328c0)

**Comment by Pylogmon** [comment]
其他位置看起来并不协调，提示很快就会自动关闭，应该不影响使用的吧。

**Comment by willson83** [comment]
能否在设置中增加一个开关功能，可以关闭这个提示。这样不需要这个提示的人就可以自行关闭。

**Comment by 1208041822** [comment]
同意加个开关
