### ISSUE TITLE
[BUG]: title

### ISSUE THREAD

**Issue by Doubleking-1** [pot-app/pot-desktop#241]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

我是win11，为什么安装后打不开，有图标，但点了没反应。

### Reproduction

我是win11，为什么安装后打不开，有图标，但点了没反应。

### Platform

Windows

### System Version

22000.1936

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
#88

**Comment by Pylogmon** [comment]
https://pot.pylogmon.com/docs/tutorial/faq#2-%E8%A2%AB%E6%9D%80%E6%AF%92%E8%BD%AF%E4%BB%B6%E5%88%A0%E9%99%A4windows
