### ISSUE TITLE
[Feature]: 剪切板监听可以永久性开启或者建议直接加入一个新的热键功能“剪切板翻译”

### ISSUE THREAD

**Issue by 1208041822** [pot-app/pot-desktop#246]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

剪切板监听每次打开面板都要手动点击开启，在我使用中是从来不把面板固定显示的，而且每次使用完我都会关闭掉，不是连续性翻译的工作状态。所以我需要实时监听剪切板并在调用快捷键时自动填入。 剪切板监听永久性开启或许会影响其他的翻译功能 所以更加建议出一个新的快捷键功能，就是剪切板翻译（调用快捷键时自动填入剪切板内容并翻译）。

### Application Scenario

非连续录入状态的剪切板翻译

**Comment by Pylogmon** [comment]
你手动复制到剪切板再按翻译快捷键也是一样的

**Comment by 1208041822** [comment]
> 

手动复制到剪切板了的 然后再按快捷键调用独立翻译窗口 还要用鼠标开启剪切板监听/按一次粘贴键

**Comment by 1208041822** [comment]
> 你手动复制到剪切板再按翻译快捷键也是一样的

![概念](https://github.com/pot-app/pot-desktop/assets/28993260/7f87d101-9d67-419d-b6a1-eb97ccd38753)

**Comment by 1208041822** [comment]
> > 你手动复制到剪切板再按翻译快捷键也是一样的
> 
> ![概念](https://user-images.githubusercontent.com/28993260/246604870-7f87d101-9d67-419d-b6a1-eb97ccd38753.png)

或者直接添加到划词翻译选项中 如果目前没有划词 那么调用剪切板翻译

**Comment by Rock-Gentleman** [comment]
确实添加个快捷键更方便点,我也有这个需求

**Comment by Pylogmon** [comment]
按理说能复制就能正常取词，如果不需要多次复制翻译，并不需要剪切板翻译的功能

**Comment by 1208041822** [comment]
> 按理说能复制就能正常取词，如果不需要多次复制翻译，并不需要剪切板翻译的功能

换个思路 如果我想划词但是这个词不能划 只能右键复制到剪切板 我就很需要能直接出剪切板的翻译结果

**Comment by Pylogmon** [comment]
划词翻译的取词方法最后就是模拟复制，不存在这种情况。

**Comment by Pylogmon** [comment]
如果你要说只能右键复制，这种情况太少了，不值得单独给他设置一个快捷键，目前的每个快捷键都对应一个大的功能，我不可能去给一种小的用例单独设置一个快捷键。

**Comment by 1208041822** [comment]
> 如果你要说只能右键复制，这种情况太少了，不值得单独给他设置一个快捷键，目前的每个快捷键都对应一个大的功能，我不可能去给一种小的用例单独设置一个快捷键。

那整合进划词的备用方案里呢

**Comment by Pylogmon** [comment]
现在划词没有取到最后都会读剪切板的呀，没有读吗？

**Comment by 1208041822** [comment]
> 现在划词没有取到最后都会读剪切板的呀，没有读吗？

没有
