### ISSUE TITLE
[Feature]: 能否出个win10 的免安装版，公司电脑不能随便安装软件，只能用免安装版

### ISSUE THREAD

**Issue by xiahounan** [pot-app/pot-desktop#260]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

![image](https://github.com/pot-app/pot-desktop/assets/101793084/2005c8cb-4076-4de9-8085-78386af52449)
公司电脑不能随便安装软件，只能用免安装版，能麻烦大佬出个打开即用的版本，万分感谢

### Application Scenario

![image](https://github.com/pot-app/pot-desktop/assets/101793084/2005c8cb-4076-4de9-8085-78386af52449)
公司电脑不能随便安装软件，只能用免安装版，能麻烦大佬出个打开即用的版本，万分感谢

**Comment by Pylogmon** [comment]
1. 由于软件依赖系统的webview2，pot的安装程序会在安装时检测webview环境自动安装，所以在win10，win7上如果没有安装webview2，便携版将无法运行。
2. 软件使用tauri提供的自动更新逻辑，即下载新的msi安装包自动安装，对于便携版来说如果使用自动更新将会下载一个安装版来安装，所以便携版没有任何意义。

所以为了避免不必要的麻烦，我不会再提供便携版。

如果你确实需要便携版，你可以在个人电脑上安装pot后直接拷贝可执行文件。

**Comment by linzzzzllll** [comment]
> 1. 由于软件依赖系统的webview2，pot的安装程序会在安装时检测webview环境自动安装，所以在win10，win7上如果没有安装webview2，便携版将无法运行。
> 2. 软件使用tauri提供的自动更新逻辑，即下载新的msi安装包自动安装，对于便携版来说如果使用自动更新将会下载一个安装版来安装，所以便携版没有任何意义。
> 
> 所以为了避免不必要的麻烦，我不会再提供便携版。
> 
> 如果你确实需要便携版，你可以在个人电脑上安装pot后直接拷贝可执行文件。

同样是公司安装不上，是不是只要整个文件夹复制过去也是可以用的？

**Comment by linzzzzllll** [comment]
公司还还闪退
