### ISSUE TITLE
每次激活窗口 都不在主屏幕

### ISSUE THREAD

**Issue by lhj5426** [pot-app/pot-desktop#262]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

我最近增量了多个副屏 然后 运行软件 激活软件的窗口时
候 都不会出现在主屏幕上而且飞去第二块副屏
每次都的去从副屏拖拽到主屏  
然后隐藏窗口之后 再激活 又回到 之前的副屏去了

应该算是 BUG把

### Reproduction

我最近增量了多个副屏 然后 运行软件 激活软件的窗口时
候 都不会出现在主屏幕上而且飞去第二块副屏
每次都的去从副屏拖拽到主屏  
然后隐藏窗口之后 再激活 又回到 之前的副屏去了

![image](https://github.com/pot-app/pot-desktop/assets/30548000/4990218c-1134-4bc3-9f33-239deeb66a4c)

应该算是 BUG把

### Platform

Windows

### System Version

win10 1909

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
请问是哪个窗口，划词翻译窗口还是独立翻译窗口，另外麻烦测试一下截图以及OCR的窗口是否正确。

**Comment by lhj5426** [comment]
> 请问是哪个窗口，划词翻译窗口还是独立翻译窗口，另外麻烦测试一下截图以及OCR的窗口是否正确。

主窗口 不是设置窗口 就 可以输入内容的主窗口

**Comment by Pylogmon** [comment]
请问按快捷键的时候鼠标在那块屏幕上，是否和鼠标出现在同一块屏幕上？

**Comment by lhj5426** [comment]
没用过快捷键我就是在任务栏点击 右键菜单翻译 弹出就在副屏
![image](https://github.com/pot-app/pot-desktop/assets/30548000/b1cb13ea-b452-4424-980e-d9a6a1ad8d3e)

**Comment by Pylogmon** [comment]
我大概知道问题原因了，截图窗口有没有这个问题

**Comment by lhj5426** [comment]
没有使用过截图…我就是在需要的时候右键激活窗口手动输入，也没有使用任何额快捷键

**Comment by xtyuns** [comment]
> 没有使用过截图…我就是在需要的时候右键激活窗口手动输入，也没有使用任何额快捷键

你试一下 截图OCR 和 截图翻译 是否也会出现这个问题

**Comment by lhj5426** [comment]
> > 没有使用过截图…我就是在需要的时候右键激活窗口手动输入，也没有使用任何额快捷键
> 
> 你试一下 截图OCR 和 截图翻译 是否也会出现这个问题

![image](https://github.com/pot-app/pot-desktop/assets/30548000/88e9350e-d48c-4b5b-9e1d-29cf606e2eac)

![image](https://github.com/pot-app/pot-desktop/assets/30548000/664cc0c9-83c8-422d-8134-b96bf09c5061)

截图ocr 和截图翻译 会正确出现在主屏幕

**Comment by lhj5426** [comment]
都是通过托盘图标 右键调用的  只有翻译 
![image](https://github.com/pot-app/pot-desktop/assets/30548000/9b472c59-4d19-4f7d-87eb-58c2a03326a5)
会 出现在副屏 而不是主屏幕

**Comment by lhj5426** [comment]
怕你再问快捷键 
我也设置了快捷键
![image](https://github.com/pot-app/pot-desktop/assets/30548000/d66accb7-88d1-4bf1-8b2e-0215f668ae25)
快捷键也会正确出现在主屏幕 
但是突然又发现个问题
![image](https://github.com/pot-app/pot-desktop/assets/30548000/bf4116dd-7f3f-4e85-bf98-e0717fee02af)
我移动到这个位置关闭掉窗口
再用快捷键激活之后
只有任务栏能看到 
![image](https://github.com/pot-app/pot-desktop/assets/30548000/5380dca6-732f-434b-a3de-7dc9fefb0c47)
而4个屏幕上哪个屏幕也没有看到窗口
并且关闭软件重开之后再用快捷键激活
![image](https://github.com/pot-app/pot-desktop/assets/30548000/4071466d-9629-48d6-a39e-f372a8c8f852)

窗口变成了这么一点
![image](https://github.com/pot-app/pot-desktop/assets/30548000/dcc240f5-61d1-4d91-902d-f18c86b47d74)

只能重新拖拽窗口重新展开 界面

然后 如果 又拖拽到屏幕的右边一点 
就死循环了

关闭窗口→快捷键激活→ 只能看到任务栏显示已经打开窗口时间上看不到窗口→ 关闭软件重开→快捷键激活→只有不点小窗口→拖拽恢复窗口大小→偏移屏幕中心关闭窗口→快捷键激活窗口→ 只能看到任务栏显示已经打开窗口时间上看不到窗口→ 关闭软件重开→快捷键激活→只有不点小窗口→拖拽恢复窗口大小→无限循环

**Comment by lhj5426** [comment]
1.7.0 刚试过 问题依旧。。。。。。

**Comment by Pylogmon** [comment]
我今天才修的，1.7是昨天发布的。

**Comment by lhj5426** [comment]
嗯抱歉 误会了 171 确实修正了 不过 还有点问题 不会记录关闭窗口的位置
![image](https://github.com/pot-app/pot-desktop/assets/30548000/76aa777b-c539-4890-beb2-e8324192c048)
![image](https://github.com/pot-app/pot-desktop/assets/30548000/5b3197fa-9f8c-4cbf-9833-76adcf728392)

**Comment by Pylogmon** [comment]
没这功能，也不打算做。
