### ISSUE TITLE
[Feature]: 人机交互的ui是否有优化的计划，大神？

### ISSUE THREAD

**Issue by justincnn** [pot-app/pot-desktop#264]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

随着大神的频繁更新，目前这个工具已经开始成为我的首选工具了，感谢大神的付出，并不断的和身边人安利，

有个小小的希望，目前的ui对话窗体，感觉有点不友好，是否可以优化下，

类似于这样的：
![](https://cdn.jsdelivr.net/gh/justincnn/pictures/img/202306211959602.png)

这种窗体看着很轻便和简洁，目前的窗体感觉很厚重复杂的样子

### Application Scenario

美化也是生产力，😄

**Comment by Layouwen** [comment]
感谢你的建议
页面的审美因人而异, 团队暂时没有专业的 ui 设计人员
对于 ui 优化方面短期暂时没有计划
后续等功能开发差不多后, 时间多会考虑来个重构
届时会重新设计系统页面, 可以先关注一下相关社群
后续如果对 ui 做调整会在社群发布讨论主题, 期待到时候你的参与讨论
如果有相关设计专业的同学, 并且愿意提供较为完整的页面设计图, 与我们讨论将会十分欢迎👏🏻
