### ISSUE TITLE
[Feature]：隐藏托盘图标

### ISSUE THREAD

**Issue by ycp666** [pot-app/pot-desktop#268]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

希望增加可以关闭菜单栏图标和更改状态栏图标的功能

### Application Scenario

状态栏方寸大小的地方，左边的应用菜单占用了一半，右边自带的图标占了一部分，留给其他图标的空间愈加减少。

### References

做的比较好的是 bob 可是它主要是收费，当然对于 macOS12 以上调用系统的翻译不要钱，但也有很多人停留在 11 和以下的系统
<img width="1280" alt="截屏2023-06-22 上午10 42 17" src="https://github.com/pot-app/pot-desktop/assets/68799511/ddc46573-e0cc-49b9-9d83-3a0c3b96d989">

**Comment by Layouwen** [comment]
首先感谢你提的建议
看了一下, 这个功能的的确是有需求的
因为项目是属于业余时间开发的, 我们会内部先评估一下相关工作量
后续会将此功能安排进开发计划, 你可以加入相关社群了解最新消息
也欢迎有研发基础的, 可以 fork 项目后协助我们开发功能, 提 pr 合并

不过你目前看起来需要的不是某个 app 的隐藏, 应该需要菜单栏管理工具
后面我们实作后, 其实你这个空间还是有点紧改善情况不大, 可以了解一下 Bartender 之类的软件~

<img width="1322" alt="image" src="https://github.com/pot-app/pot-desktop/assets/60692794/7c9e05ef-746b-4bd2-87c3-3be0df6730a4">
<img width="927" alt="image" src="https://github.com/pot-app/pot-desktop/assets/60692794/f93915ac-7723-4735-af83-7c24afbf8756">

**Comment by Pylogmon** [comment]
试试这个吧 https://github.com/dwarvesf/hidden

我觉得这种事情不应该由软件来解决。
