### ISSUE TITLE
[Feature]: title

### ISSUE THREAD

**Issue by yangchen158158** [pot-app/pot-desktop#273]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

选中文字点击动作，进行划词翻译（建议搭配快捷键使用。）；

未选中文字点击动作，进行截图翻译（调用“基础OCR模块”）；

大佬，可以这样实现吗？可以节省下快捷键呢。POT超级好用的翻译

### Application Scenario

节省下快捷键操作快捷，只需要一键即可。

### References

https://getquicker.net/Sharedaction?code=04393db9-f4bc-4871-7fb6-08db2506d1ed

**Comment by Pylogmon** [comment]
这种功能自定义quicker动作就行，不需要我来实现。

**Comment by yangchen158158** [comment]
> 这种功能自定义quicker动作就行，不需要我来实现。

POT甚至可以自定义文本润色等，目前看过全部翻译，最叼的1个。
