### ISSUE TITLE
输入框增强功能。

### ISSUE THREAD

**Issue by yangchen158158** [pot-app/pot-desktop#275]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

请问这个功能容易实现吗？就是先划词选中：中文段落，就自动翻译成英文，如果划词选中的：英文段落，能自动翻译中文。2种语言之间无障碍翻译。

### Application Scenario

有些客户使用英语进行交流沟通，这时只需将中文划词一下即可输出英文供其查看，非常方便快捷。如果能够实现沉浸式全局输入框增强，那就更加完美了。

### References

参考沉浸式翻译，浏览器插件：输入框增强功能。

**Comment by Pylogmon** [comment]
一个issue对应一个问题，请按规范提交issue。
