### ISSUE TITLE
[BUG]: 在kde+wayland下面启动时显示快捷键注册失败,选择截图ocr时闪退

### ISSUE THREAD

**Issue by a15355447898a** [pot-app/pot-desktop#278]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

我现在在使用archlinux,桌面是kde,使用wayland
我已经确认pot更新到最新版本了

### Reproduction

选择截图ocr时闪退

### System Version

archlinux

### Window System(Linux Only)

Wayland

### Software Version

pot-1.7.1

### Additional Information

使用命令行启动pot,在点击截图ocr时闪退,会输出如下日志
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: 没有那个文件或目录 (os error 2)', src/utils.rs:49:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Pylogmon** [comment]
1. wayland下无法使用应用内快捷键，请情况快捷键设置后通过系统自定义快捷键来设置。
2. 截图功能暂不支持Wayland，因为tauri在Wayland下无法获取到正确的dpi，所以无法截图(不过你说的这个问题我之前kde测试的时候没有出现，倒是在gnome的Wayland下有过这个问题，我会想办法修复，但是暂时还没啥办法)

**Comment by a15355447898a** [comment]
> 1. wayland下无法使用应用内快捷键，请清空快捷键设置后通过系统自定义快捷键来设置。
> 2. 截图功能暂不支持Wayland，因为tauri在Wayland下无法获取到正确的dpi，所以无法截图(不过你说的这个问题我之前kde测试的时候没有出现，倒是在gnome的Wayland下有过这个问题，我会想办法修复，但是暂时还没啥办法)

关于1,我这里发现在wayland下面不能清空快捷键(表现为"热键设置",设置框点击后没显示光标),只有切换到x11下面才可以清除

然后,可以提供一下各个热键对应的命令吗?

另,为什么有两个关闭按钮?软件设置部分似乎有两个边框
![image](https://github.com/pot-app/pot-desktop/assets/62456287/f408b739-04f1-4f4a-ad04-322b5b38035a)

**Comment by Pylogmon** [comment]
pot使用的是自绘的标题栏，系统标题栏是隐藏了的，x11下是正常的，但是在kde Wayland下隐藏没有生效，这是tauri的bug，现在只能手动添加窗口规则来隐藏标题栏

**Comment by Pylogmon** [comment]
> 我这里发现在wayland下面不能清空快捷键(表现为"热键设置",设置框点击后没显示光标),只有切换到x11下面才可以清除

是的，Wayland下应用内的快捷键输入框是禁用了，不考虑不同窗口系统切换的情况。

**Comment by Pylogmon** [comment]
截图功能我在KDE+Wayland和KDE+X11都已经测试可用，如果测试没有问题请关闭这个issue。

**Comment by a15355447898a** [comment]
> 截图功能我在KDE+Wayland和KDE+X11都已经测试可用，如果测试没有问题请关闭这个issue。

kde+wanyland测试,选择截图ocr依旧闪退(就在刚刚,滚的更新)

**Comment by Pylogmon** [comment]
贴一下报错，还有看一下`~/.cache/com.pylogmon.pot` 目录的内容。

**Comment by a15355447898a** [comment]
> 贴一下报错，还有看一下`~/.cache/com.pylogmon.pot` 目录的内容。

选择截图ocr后出现报错如下

![image](https://github.com/pot-app/pot-desktop/assets/62456287/4d38e5c2-3fc9-4976-b153-aa0b185857cf)

`~/.cache/com.pylogmon.pot`目录下面是两张图片

![image](https://github.com/pot-app/pot-desktop/assets/62456287/07f02477-302a-4e30-b47f-d591d6576815)

**Comment by Pylogmon** [comment]
```bash
RUST_BACKTRACE=1 pot
```
看看

**Comment by a15355447898a** [comment]
![image](https://github.com/pot-app/pot-desktop/assets/62456287/61391b1a-8dcf-41ce-934e-6cf2a663a17c)

一样闪退

> ```shell
> RUST_BACKTRACE=1 pot
> ```
> 
> 看看

**Comment by Pylogmon** [comment]
找到问题了，应该是跟你的这些文件夹是中文有关
![image](https://github.com/pot-app/pot-desktop/assets/59004461/0e06a179-11e4-41ac-9b30-841a8379520f)

**Comment by Pylogmon** [comment]
问题已经修复，麻烦升级最新版测试。

**Comment by a15355447898a** [comment]
工作正常了,谢谢!
