### ISSUE TITLE
[BUG]: 开机自启动不稳定

### ISSUE THREAD

**Issue by lb-fes** [pot-app/pot-desktop#281]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

~~很多天了，每天重新打开电脑，pot 都不会自己启动~~

这几天就失败了两次，有点儿不稳定，希望能改进一下

### Reproduction

1.重启电脑
2.没法自启动，只能手动运行

### Platform

Windows

### System Version

Windows 10 专业版 19045.3086

### Window System(Linux Only)

None

### Software Version

1.7.1

**Comment by Pylogmon** [comment]
pot设置里面关闭开机启动选项后重新打开

**Comment by lb-fes** [comment]
> pot设置里面关闭开机启动选项后重新打开

感谢！已解决

**Comment by Pylogmon** [comment]
开机启动需要时间，请等待一段时间，Windows会依次启动开机自启项目。

**Comment by lb-fes** [comment]
> 开机启动需要时间，请等待一段时间，Windows会依次启动开机自启项目。

不是等待的问题，我早上启动的电脑，中午才用 pot ，按快捷键翻译没反应才发现的

**Comment by lb-fes** [comment]
可能是偶发事件，最近运行良好，关闭 issue
