### ISSUE TITLE
[Feature] 增加垂直邻域翻译功能

### ISSUE THREAD

**Issue by learningdog1** [pot-app/pot-desktop#282]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

虽然软件中已有百度翻译，但还是希望能增加百度的垂直领域翻译接口，以满足特定领域的翻译需求，如计算机、金融经济和生物医学等。

### Application Scenario

满足特定领域的翻译需求

### References

灵感来自zotero插件，可在以下链接查看并参考：https://zotero.yuque.com/staff-gkhviy/pdf-trans/wewaia

**Comment by Pylogmon** [comment]
Ok，待办
