### ISSUE TITLE
[BUG]: 在M1的macbook上编译后安装，右上边栏的图标白色，另外代理是否不支持IPv6的socks5？

### ISSUE THREAD

**Issue by tguhanyeluo** [pot-app/pot-desktop#283]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

使用的tag 1.7.1 进行编译的

M1 的macbook pro，菜单栏的图标显示白色，并且代理配置socks5无效

ps：使用releases1.7.1 版本的arm安装包可以正常显示图标，但是代理依旧无效。

### Reproduction

按照readme指示：
pnpm install
pnpm tauri build
编译后的pot安装包进行安装后打开应用程序，右上角图标白色

并且使用自己的shadowsocksX开启的http和socks5代理后，配置到代理配置中均无法访问google服务。

### Platform

MacOS

### System Version

macOS Monterey 12.6.1

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
mac所用的图标跟windows不一样，我在编译的时候是有改图标的。

**Comment by Pylogmon** [comment]
代理暂不支持socks，请使用http

**Comment by tguhanyeluo** [comment]
您说的编译时候改图标是什么意思？需要我这边在编译的时候做什么处理才能让右上角图标显示出来呀？
另外http的代理使用shadowsocksX开启的http代理可用么？因为我现在电脑的shadowsocks的代理没问题，但是就是配置到pot里不生效，dns解析需要做特殊处理么？

**Comment by Pylogmon** [comment]
在src-tauri/tauri.conf.json最后改成这样
```json
        "systemTray": { 
             "iconPath": "icons/tray.ico", 
             "iconAsTemplate": true 
         }
```

代理得在应用内设置，不会走系统代理，检查地址和端口号是否设置正确。

**Comment by tguhanyeluo** [comment]
好的，根据您的提示修改问题fix
