### ISSUE TITLE
[BUG]: 托盘图标tooltip为空

### ISSUE THREAD

**Issue by amalaccs** [pot-app/pot-desktop#284]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

win11 任务栏托盘，鼠标悬停没文字，有点不美观

![image](https://github.com/pot-app/pot-desktop/assets/42665196/945e9466-af0b-4394-ac3e-49ce80d5c53e)

### Reproduction

win11 任务栏托盘，鼠标悬停

### Platform

Windows

### System Version

Windows 11 专业工作站版 22621.1928

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
pot的版本是多少

**Comment by amalaccs** [comment]
> pot的版本是多少

1.7.0
