### ISSUE TITLE
[Feature]: 希望增加账号同步

### ISSUE THREAD

**Issue by happykkAi** [pot-app/pot-desktop#285]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

希望增加账号同步，方便跨电脑使用pot。

### Application Scenario

重新填写api或者token 太麻烦

**Comment by Pylogmon** [comment]
重复issue #231
