### ISSUE TITLE
[BUG]: error in deepl translate

### ISSUE THREAD

**Issue by ElmTran** [pot-app/pot-desktop#286]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

The first language is set to English and the second language is set to Chinese. The English to Chinese translation will report an error if the deepl token is set.

### Reproduction

![image](https://github.com/pot-app/pot-desktop/assets/34189785/69c2ef6e-8c79-4f96-a90b-cc3c6b4aa5f3)

### Platform

Windows

### System Version

Windows 11 Pro N 22H2

### Window System(Linux Only)

None

### Software Version

[1.7.1](pot:1.7.1  Tauri:1.4.0)

**Comment by Pylogmon** [comment]
Sorry I didn't reproduce this error.

**Comment by ElmTran** [comment]
pot info:
![image](https://github.com/pot-app/pot-desktop/assets/34189785/5aac712b-f559-477b-8970-3d1053f80b2e)
translate settings:
![image](https://github.com/pot-app/pot-desktop/assets/34189785/3980c98c-2bf3-4c01-a347-830e10e9a710)
api config:
![image](https://github.com/pot-app/pot-desktop/assets/34189785/1b6b36a2-71bc-4506-85a3-5cd42d44491b)
system info:
![image](https://github.com/pot-app/pot-desktop/assets/34189785/bd51d77c-ec3c-4e88-9631-6f2705f4d92a)
operation:
![image](https://github.com/pot-app/pot-desktop/assets/34189785/16586545-b246-4a71-ae8b-86dd32916408)
deepl plan:
![image](https://github.com/pot-app/pot-desktop/assets/34189785/14e29bc0-52ad-4d75-a3cd-449fab5227a3)

**Comment by Pylogmon** [comment]
Thank you for your feedback, it has been fixed.
