### ISSUE TITLE
[BUG]: 应用内下载新版本失败

### ISSUE THREAD

**Issue by lb-fes** [pot-app/pot-desktop#287]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

在应用内更新版本一直显示下载中
![Snipaste_2023-07-09_19-12-44](https://github.com/pot-app/pot-desktop/assets/51531901/37540b7f-5113-4b96-ba7a-345d87f0133c)

### Reproduction

1.检查更新
2.点**下载**
3.一直显示在下载中

### Platform

Windows

### System Version

Windows 10 专业版 19045.3086

### Window System(Linux Only)

None

### Software Version

1.7.1

### Additional Information

开没开代理都一样

**Comment by Pylogmon** [comment]
这是Tauri的bug，后续会修复，暂时的解决办法是管理员权限运行pot后检查更新。
