### ISSUE TITLE
[BUG]: windows 10上无法安装

### ISSUE THREAD

**Issue by binglin1009** [pot-app/pot-desktop#290]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

系统版本win10 22H2.

之前还可以用绿色版，后来绿色版就被下架了。
我为什么用绿色版，因为x64版本无法安装啊。
双击都是一闪而过，用管理员权限也是。
不管是之前的1.4版本，还是现在的1.8版本，都是这样。
我就好奇，难道就我一个人遇到这个问题吗？

我更加纳闷的，其他软件都安装的好好的，唯独这个pot这么特别？

### Reproduction

在我电脑上直接双击就是一闪而过，这个必现的。

### Platform

Windows

### System Version

19045.2965

### Window System(Linux Only)

None

**Comment by lb-fes** [comment]
升级一下系统版本？

我 19045.3086 没出现这个问题

**Comment by Pylogmon** [comment]
确实这个问题你是第一个反馈的，其他人没有问题，请检查系统是否是企业版，是否有某些策略阻止了安装，检查Windows的smartscreen弹窗是否在后台显示，另外要不录个视频展示一下你所说的一闪而过是什么样。

**Comment by magicGina** [comment]
我的也是..

**Comment by magicGina** [comment]
<img width="496" alt="image" src="https://github.com/pot-app/pot-desktop/assets/88796282/8ad03ebe-6883-4d8e-93dd-b9b34b732ad1">
从windows defender里关闭检查应用和文件，才能出现安装窗口，我现在已经安装成功
