### ISSUE TITLE
[BUG]: 划屏翻译模式下，翻译结果被强制删除所有换行

### ISSUE THREAD

**Issue by PercivalTang** [pot-app/pot-desktop#291]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

划屏翻译模式下，翻译结果被强制删除换行。
我确定我已经在设置中取消了“自动删除换行”，但在划屏翻译时，出来的结果依然是自动删除了所有换行的。
这导致当我选中好几段文字进行划屏翻译时，翻译结果全部缩成一团，对照起来很不方便。

在输入模式下，并没有出现类似的情况，复制好几段文字，粘贴到输入框，翻译出来的文字同样是分段的。
但在划屏翻译模式下，翻译出来的文字始终是删除了所有换行，全部缩成一团的。

### Reproduction

![微信截图_20230710150328_结果](https://github.com/pot-app/pot-desktop/assets/108387483/af2c2451-e352-4ba1-a3f9-4ea6f31d1c76)
![微信截图_20230710150359_结果](https://github.com/pot-app/pot-desktop/assets/108387483/946c4372-b9fd-4f92-94c1-cb5511c5e556)

### Platform

Windows

### System Version

Windows 10 2H22

### Window System(Linux Only)

None

### Software Version

1.8

**Comment by PercivalTang** [comment]
我发现这个bug可能并不一定是pot的问题……
我中文、英文网站随机测试了十几个，发现不管是中文，还是英文，大部分翻译都是正常的，原来是分段的，翻译结果也是分段，但个别网站就不行，比如知乎，还有我上面截图的LRG。
LRG的商品页面和文章页面我都测试过了，划屏翻译模式全部都会删除所有换行，翻译结果挤成一团，但另外几个外国网站都正常，LRG的手动复制粘贴到输入模式也正常，原因不明。
至于知乎，出现过和LRG一样的翻译结果没有分段情况，但知乎更复杂，更多的情况是，选中好几段进行划屏翻译，但只翻译了最后一段……

所以其实这个可能并不是pot的bug，是我错怪了pot，抱歉。
只能说可能是个别网站兼容性问题吧……可能……

**Comment by Pylogmon** [comment]
确实有个别网站会有这样的问题，这个我也发现了，这也没啥办法。
