### ISSUE TITLE
[BUG]: M1 macbook 无法打开

### ISSUE THREAD

**Issue by zhouhuan327** [pot-app/pot-desktop#292]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

m1 mac 安装后无法打开

### Reproduction

下载的官网的1.8.0  macos aarch64包安装后提示： 
“pot”已损坏，无法打开。 你应该将它移到废纸篓。

### Platform

MacOS

### System Version

13.2.1

### Window System(Linux Only)

None

### Software Version

1.8.0

**Comment by zhouhuan327** [comment]
我自己跑`yarn tauri build --target universal-apple-darwin` 构建了一份，打开时会一直提示我申请“辅助功能”权限，但是即使给他加了权限打开应用时还是一直提出申请权限的弹窗

**Comment by Pylogmon** [comment]
官网和readme都说了的![Screenshot_2023-07-11-11-31-26-497_com.lemurbrowser.exts.jpg](https://github.com/pot-app/pot-desktop/assets/59004461/15fba6ef-ed76-4c8e-9482-c9f12e60432d)

**Comment by Pylogmon** [comment]
![Screenshot_2023-07-11-11-33-24-639_com.github.android-edit.jpg](https://github.com/pot-app/pot-desktop/assets/59004461/a11a2060-3da6-4d83-aedf-34de24b8e8f6)

**Comment by zhouhuan327** [comment]
感谢，这两个问题解决了。但是现在打开后应用图标出现一瞬间就消失了，也没出现任何界面，但是看pot那个进程是在的
