### ISSUE TITLE
[Feature]: 增加记住翻译窗口位置功能

### ISSUE THREAD

**Issue by souththzz** [pot-app/pot-desktop#294]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

记住上次关闭翻译窗口时的位置，下次打开就不用手动调整了

### Application Scenario

我读文档时，习惯把翻译窗口放在屏幕边缘的位置，边看文档边翻译；而目前每次打开窗口总是处在正中心位置，不太方便。

**Comment by Pylogmon** [comment]
划词翻译是跟随鼠标位置的，而输入翻译默认居中，你这种使用场景，你可以把窗口置顶放在屏幕一侧。

**Comment by Lovening** [comment]
我觉的可以加个选项，窗口位置是否要跟随鼠标位置，比如有的人双屏使用，屏幕是上下放的，下面的是主屏幕，那么就希望翻译的窗口每次都在主屏幕上，不要再副屏幕上, 这个记住窗口位置选项要是容易加可以加 要是麻烦也可以不加，看工作量了。
