### ISSUE TITLE
[BUG]: 安装后产生了很多临时安装程序

### ISSUE THREAD

**Issue by lb-fes** [pot-app/pot-desktop#296]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

1.8.0 32位产生了很多，1.8.1 64位产生了 1 个

![Snipaste_2023-07-12_22-37-04](https://github.com/pot-app/pot-desktop/assets/51531901/86b35a78-9fd9-4d75-b851-9560400530d5)

### Reproduction

如题

### Platform

Windows

### System Version

Windows 10 专业版 19045.3086

### Window System(Linux Only)

None

### Software Version

1.8.1

**Comment by Pylogmon** [comment]
应该是在非管理员权限下多次尝试更新导致的

**Comment by lb-fes** [comment]
> 应该是在非管理员权限下多次尝试更新导致的

应该是，之前试了很多次更新，今天试了一次

看来这个 https://github.com/pot-app/pot-desktop/issues/287 是下载成功了，但是更新不了

**Comment by Pylogmon** [comment]
是的，这个问题已经修复了，就等tauri发版了。
