### ISSUE TITLE
PDF translate.

### ISSUE THREAD

**Issue by burrinhoMAC** [pot-app/pot-desktop#298]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

When we copy the PDF content and paste it into the webpage translation, there may be extra line breaks that lead to garbled translation, and the translation does not match the text reading meaning.

### Application Scenario

Correct the line breaks in PDF text copy.

### References

https://github.com/CopyTranslator/CopyTranslator

https://camo.githubusercontent.com/fd39fcd1241c6e66a13c5f083bdc6bf4ce0386f264c331a598437a179acc2b69/68747470733a2f2f73312e617831782e636f6d2f323031382f31312f33302f466d724e46532e676966

[https://camo.githubusercontent.com/fd39fcd1241c6e66a13c5f083bdc6bf4ce0386f264c331a598437a179acc2b69/68747470733a2f2f73312e617831782e636f6d2f323031382f31312f33302f466d724e46532e676966](url)

**Comment by Pylogmon** [comment]
I think I've solved this problem. There is currently a button on the translation panel to remove the extra Newline characters. You can also enable automatic deletion of Newline characters in your settings, which should be enough to solve your problem.

**Comment by burrinhoMAC** [comment]
Excellent.
You are great!!!
