### ISSUE TITLE
[Feature]: Hide translate window

### ISSUE THREAD

**Issue by RYSKZ** [pot-app/pot-desktop#300]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

Currently, when using the Clipboard Listening Mode in the app, the translation window is displayed whenever the designated hotkey is pressed. While this feature is useful for accessing the translated text, it is unnecesary and distracting when you have enabled the option to automatically copy the translated text to the clipboard as the window remains visible until the focus is changed to another app.

I have reviewed the historical issues on GitHub but could not find any previous discussions or answers regarding this specific request. However, I must mention that I do not understand the Chinese language but searching my translated queries didn't come with results closely related to the feature I am requesting in this issue. Nevertheless, I apologize if this issue has been raised before.

### Application Scenario

In my usage of the app, I have enabled the option to automatically copy the translated text to the clipboard and I have assigned a hotkey to trigger the translation of the selected text using the Clipboard Listening Mode. As a result, I find that showing the translation window is unnecessary for my workflow, as I primarily rely on the automatically copied text. Therefore, it would be immensely helpful if an option could be added to completely hide the window when Clipboard Listening Mode is enabled. This way, I can continue using the app seamlessly without any unnecessary distractions.

**Comment by Pylogmon** [comment]
I understand that you mean to disable the translation window when using the selection translation feature, and instead have the translation results directly copied to the clipboard. This functionality is unrelated to the clipboard monitoring mode. Based on your description, it seems that you are not using the clipboard monitoring mode but rather the selection translation feature. The clipboard monitoring mode can be accessed through a button at the top of the translation panel, and there is no shortcut key assigned to enable it.

**Comment by RYSKZ** [comment]
Yes, sorry, you are right. I was actually referring to the translation by selection function, not the clipboard monitoring mode. Currently, I have the translation results automatically copied to the clipboard, so I don't use the translation window at all and when it pops up after selecting text and pressing the hotkey it is distracting. I have not seen any option in the application to disable this behavior and keep the window hidden all the time.

**Comment by Pylogmon** [comment]
Ok, understandable use-case, I'll consider adding this functionality.

**Comment by RYSKZ** [comment]
Great. Thank you for considering it and keep up the excellent work!
