### ISSUE TITLE
[BUG]: 截图翻译，使用快捷键有bug，不是直接识别翻译，而是显示的OCR数据

### ISSUE THREAD

**Issue by justinzhuying** [pot-app/pot-desktop#301]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

[BUG]: 截图翻译，使用快捷键有bug，不是直接识别翻译，而是显示的OCR数据

### Reproduction

[BUG]: 截图翻译，使用快捷键有bug，不是直接识别翻译，而是显示的OCR数据

### Platform

Windows

### System Version

1.8.3

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
应该不是bug，如果你使用的是默认的tesseract接口，请在设置中指定识别的语言，否则识别会非常慢，而且首次使用会下载数据集，需要花费一些时间，请耐心等待。鉴于tesseract的识别效果，我更推荐使用其他在线OCR接口。

**Comment by justinzhuying** [comment]
好的，我试一下，用那个OCR有推荐吗，最好有免费使用额度

**Comment by Pylogmon** [comment]
所有接口都有免费额度的，识别效果百度和火山相对好一些。
