### ISSUE TITLE
anki配置

### ISSUE THREAD

**Issue by FmoX** [pot-app/pot-desktop#302]
按照了使用文档配置anki之后 进行添加 显示已添加到anki的提示但未在anki找到刚才添加的卡片

**Comment by Pylogmon** [comment]
我刚刚测试没有问题

![image](https://github.com/pot-app/pot-desktop/assets/59004461/6fbf3a8a-b096-426a-84f4-50c9b330749e)

**Comment by FmoX** [comment]
请问pot牌组和笔记模板是自动生成的吗 我好像都没有

**Comment by Pylogmon** [comment]
是的

**Comment by FmoX** [comment]
https://files.catbox.moe/tcul9l.mp4
或者是我的操作还是配置有问题吗

**Comment by Pylogmon** [comment]
奇怪了，看起来好像没什么问题

**Comment by Pylogmon** [comment]
在代理软件里面设置让127.0.0.1不走代理可不可以呢？

**Comment by FmoX** [comment]
> 在代理软件里面设置让127.0.0.1不走代理可不可以呢？

感谢 有效果 已解决
