### ISSUE TITLE
[BUG]: text when clicking on the tray icon is in Chinese when I use the application language in Brazilian Portuguese.

### ISSUE THREAD

**Issue by Havokdan** [pot-app/pot-desktop#304]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

Text when clicking on the tray icon is in Chinese when I use the application language in Brazilian Portuguese. In version 1.9.0. When I switch to English, the language in the tray is accordingly.

### Reproduction

1 - Install 1.9.0 version in Windows;
2 - Change the application interface language to Brazilian Portuguese;
3 - Restart the application;
4 - Click on the icon in the tray and the text will be in Chinese (at least I believe it is Chinese).

### Platform

Windows

### System Version

Windows 10 x64

### Window System(Linux Only)

None

### Software Version

1.9.0

### Additional Information

If nothing to add.

**Comment by Pylogmon** [comment]
Please check the translation is accurate, if not, please reply under PR.
