### ISSUE TITLE
[BUG]: 划词翻译窗口超出显示器边界

### ISSUE THREAD

**Issue by rockxsj** [pot-app/pot-desktop#308]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

![image](https://github.com/pot-app/pot-desktop/assets/3021207/0b8f6d9b-5381-4680-a231-34677a7be3a5)

### Reproduction

在浏览器靠上的地方热键唤起划词翻译就会复现

### Platform

Windows

### System Version

Windows 11 专业版 22621.1928

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
几块屏幕，分别是什么尺寸？

**Comment by rockxsj** [comment]
> 几块屏幕，分别是什么尺寸？

笔记本自带的14寸和外接的27寸。   试了下外接屏幕上才有这个问题，笔记本自带的没这个问题。

**Comment by Pylogmon** [comment]
请问问题是否仍然存在

**Comment by rockxsj** [comment]
> 请问问题是否仍然存在
解决了
