### ISSUE TITLE
[BUG]: Mac M1 无法安装，提示软件已损坏，在隐私与安全中并没有发现该软件

### ISSUE THREAD

**Issue by arsize** [pot-app/pot-desktop#309]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

<img width="260" alt="image" src="https://github.com/pot-app/pot-desktop/assets/24858265/0b6c5575-a7c4-4a86-aed9-4a3f9e59dea0">
提示如上：

### Reproduction

点击取消后，去系统隐私与安全，没有发现该软件，无法点击仍要打开。

### Platform

MacOS

### System Version

macos:13.4.1 

### Window System(Linux Only)

None

### Software Version

19.1

**Comment by Pylogmon** [comment]
如果在 隐私与安全性 中找不到以上选项，或启动时提示文件损坏。打开 Terminal.app，并输入以下命令，然后重启 pot 即可：

```bash
sudo xattr -d com.apple.quarantine /Applications/pot.app
```

这在官网和readme都写的很清楚。
