### ISSUE TITLE
[Feature]: 无法使用arm64.deb

### ISSUE THREAD

**Issue by free-150** [pot-app/pot-desktop#311]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

在 Ubuntu jammy 安装xxx_arm64.deb
```shell
sudo dpkg -i xxx_arm64.deb
# 提示依赖问题：
sudo apt install libxdo3 libxdo-dev
```
安装后无法运行，没有任何界面。

### Application Scenario

无法达到预期的运行效果

### References

另希望可以添加 arm64 的 AppImage

**Comment by free-150** [comment]
使用
```shell
sudo apt install ./xxx_arm64.deb
```
还是一样的，安装后程序里有应用图标但运行不了

**Comment by Pylogmon** [comment]
从终端启动看看有啥报错

**Comment by free-150** [comment]
没有报什么错。还是希望增加 arm64 的 AppImage。

**Comment by Pylogmon** [comment]
那运行之后是什么反应，托盘图标出现了吗？

**Comment by free-150** [comment]
没反应也没托盘图标

**Comment by Pylogmon** [comment]
Tauri的AppImage打包脚本好像还不支持Arm

**Comment by Pylogmon** [comment]
最新版本更改了构建环境，麻烦下载测试一下，应该没问题了。

**Comment by free-150** [comment]
还是用不了，在同硬件的xfce桌面下可以用。目前在ubuntu gnome wayland 下还是无法启动。

**Comment by Pylogmon** [comment]
截图，启动时什么是什么表现

**Comment by free-150** [comment]
启动时不报任何提示和弹窗，在命令行也一样。
估计包没问题，可能是我设备的问题。
我安装另一个翻译软件 Crow Translate 的 deb 也是一样无法启动。
> https://crow-translate.github.io/

但我使用它给出的命令安装却可以运行
```shell
sudo add-apt-repository ppa:jonmagon/crow-translate
sudo apt update
sudo apt install crow-translate
```
