### ISSUE TITLE
[Bug] Dock栏图标没有隐藏

### ISSUE THREAD

**Issue by neo233233233** [pot-app/pot-desktop#314]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

mac端的pot（至少在m系列芯片上），在初次运行时，会弹出pot的设置页面的对话框，并且会显示app正在运行

一旦关闭或隐藏pot设置窗口，就再也无法打开设置窗口，并且会在软件运行时显示软件未运行，

并且禁止卸载（即显示正在运行），除非使用第三方软件强行杀进程或关机

以及设置快捷键后，一旦使用，即程序崩溃，不可打开

### Reproduction

打开软件
显示弹窗
隐藏/关闭/缩小窗口
问题出现，再也无法打开设置页面+显示软件未运行

### Platform

MacOS

### System Version

macos13.4.1

### Window System(Linux Only)

None

### Software Version

[1.10.1](https://github.com/pot-app/pot-desktop/releases/tag/1.10.1)

**Comment by Pylogmon** [comment]
请问有没有截图或者视频，软件在mac下的测试很少，但现有的测试并没有发现这么严重的问题。

**Comment by neo233233233** [comment]
> 请问有没有截图或者视频，软件在mac下的测试很少，但现有的测试并没有发现这么严重的问题。

有的，这个是录屏

https://u.pcloud.link/publink/show?code=XZmElAVZDS12r2YA0UVFejsjDjmOnf7SpuDy

**Comment by Pylogmon** [comment]
上面没有托盘图标吗？dock栏的图标应该是隐藏了的。

**Comment by neo233233233** [comment]
> 上面没有托盘图标吗？dock栏的图标应该是隐藏了的。

并未设置隐藏，我再录一段完整点的展示吧

**Comment by neo233233233** [comment]
勘误一下，找到问题了，我的托盘管理工具直接把pot盖了，不能同时运行
抱歉，草率了

**Comment by Pylogmon** [comment]
后台运行的时候所有操作是通过快捷键和托盘菜单完成的，dock栏不应该留有图标，这也是个问题。

**Comment by neo233233233** [comment]
不过好像这勉强也算一些小的可以微调的点，我的托盘管理工具叫hidden bar，只有设置隐藏了才会托管折叠图标，但他在没有满标+未纳入pot的情况下，好像可以直接把pot盖了= =
