### ISSUE TITLE
[Feature]: 支持 Mathpix

### ISSUE THREAD

**Issue by xiajunwen1007** [pot-app/pot-desktop#315]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

Mathpix在ocr识别文本混合数学公式时效果很好，不知道能否支持相关api。

### Application Scenario

mathpix是数学公式识别领域最好用的能够处理复杂的文本加公式

### References

文档：https://docs.mathpix.com/#introduction
官网：https://mathpix.com

**Comment by Pylogmon** [comment]
能不能提供key来测试，可以发我邮箱
pylogmon@outlook.com

**Comment by xiajunwen1007** [comment]
抱歉我暂时还没有key，刚刚看好像注册要25$，后续每次识别也要钱，对我来说可能太贵了
