### ISSUE TITLE
[BUG]: 勾选隐藏输入栏，会把语言栏也隐藏

### ISSUE THREAD

**Issue by willson83** [pot-app/pot-desktop#317]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

如果勾选隐藏输入栏，会把语言栏也隐藏了。如果不勾选隐藏输入栏，只勾选隐藏语言栏，界面无变化，并不会隐藏语言栏。应该是隐藏输入栏的功能把语言栏也包括进去了

### Reproduction

在设置，应用设置中，单独勾选隐藏输入栏或隐藏语言栏可看出问题。

### Platform

Windows

### System Version

win10 21H2

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
感谢反馈，已修复
