### ISSUE TITLE
[Feature]: 希望支持windows本地的OCR，速度快很多

### ISSUE THREAD

**Issue by hgaogao** [pot-app/pot-desktop#319]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

希望可以默认支持[windows本地的OCR接口](https://learn.microsoft.com/en-us/uwp/api/windows.media.ocr?view=winrt-22621)
因为我看到[powertoys上面的OCR还挺快](https://github.com/TheJoeFin/Text-Grab)的,准确性也还不错,希望可以集成到软件里面

### Application Scenario

接口申请起来有点繁琐，而且速度也不是很快，所以希望支持本地的OCR

### References

[windows本地的OCR接口](https://learn.microsoft.com/en-us/uwp/api/windows.media.ocr?view=winrt-22621)
[调用本地OCR接口的项目](https://github.com/TheJoeFin/Text-Grab)

**Comment by Pylogmon** [comment]
在线OCR速度都是很快的，因为要做跨平台，Windows系统OCR其他平台没法用，后续可能会通过插件来支持。

**Comment by hgaogao** [comment]
作为用户来说，如果可以开箱即用的话就很完美了，我记得macOS也是有本地OCR接口的，希望可以通过插件系统也一起支持，或者等别的大佬来一起实现😁

**Comment by hiroi-sora** [comment]
我是离线OCR软件 [Umi-OCR](https://github.com/hiroi-sora/Umi-OCR) 的开发者，Umi-OCR 支持通过读写剪贴板的方式与翻译软件联动。

刚发现pot支持命令行调用，赞👍Umi-OCR 后续可能会增加与pot的命令行联动方式。

另，Umi-OCR也支持命令行调用OCR 。如果需要获取返回值，还有独立的离线引擎组件 [PaddleOCR-json](https://github.com/hiroi-sora/PaddleOCR-json) 。作者有兴趣可以看看~ @Pylogmon

**Comment by Pylogmon** [comment]
> 刚发现pot支持命令行调用翻译，赞👍Umi-OCR 后续可能会增加与pot的命令行联动方式。

太好了！`pot translate` 命令在没有选择文本的时候是会读取剪切板的，可以通过这个来联动。

> 另，Umi-OCR也支持命令行调用OCR 。如果需要获取返回值，还有独立的离线引擎组件 [PaddleOCR-json](https://github.com/hiroi-sora/PaddleOCR-json) 。作者有兴趣可以看看~

PaddleOCR-json还不支持linux，所以我在考虑从浏览器端下手。

**Comment by hiroi-sora** [comment]
我尝试写了通过命令行传输识别文本的方式，感觉效果一般，因为命令行没法传换行符。还是用剪贴板来传文本的效果好一点。

目前Umi-OCR已支持通过剪贴板+按键事件的方式与Pot联动，简要步骤如下：

![image](https://github.com/pot-app/pot-desktop/assets/56373419/a778def8-6414-4536-9d61-d2f22195669a)

1. 安装最新版本的 Pot 和 [Umi-OCR](https://github.com/hiroi-sora/Umi-OCR#%E4%B8%8B%E8%BD%BD)
2. Umi-OCR打开高级模式（设置页底部勾选`高级选项`，然后重启Umi-OCR软件）
3. Umi-OCR在`快捷识图`设置中，勾选`自动复制结果` 和 `自动复制后发送按键`
4. Umi-OCR在`自动复制后发送按键`中录制一组按键，如 `ctrl+shift+T`
5. Pot 设置相同的划词翻译快捷键 `ctrl+shift+T`

完成以上设置，后续使用Umi-OCR进行截图OCR，Umi就会将识别文本写入剪贴板，并发送按键唤起Pot进行翻译。

**Comment by Pylogmon** [comment]
@hiroi-sora 我基于 PaddleOCR-json 开发了插件

https://github.com/pot-app/pot-app-recognize-plugin-paddle
