### ISSUE TITLE
[BUG]:M1 MAC 安装失败（手动安装）

### ISSUE THREAD

**Issue by hoppop-web** [pot-app/pot-desktop#320]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

安装包安装后，软件无法打开。
安装包：pot_1.10.1_aarch64.dmg
打开报错：" “pot.app”已损坏，无法打开。 你应该将它移到废纸篓。"

### Reproduction

安装包安装后，软件无法打开。
打开报错：“pot.app”已损坏，无法打开。 你应该将它移到废纸篓。

### Platform

MacOS

### System Version

ventura 13.5

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
不是bug，官网文档和readme都说了原因和解决方法。

**Comment by hoppop-web** [comment]
抱歉，没仔细看，真是很抱歉。
