### ISSUE TITLE
[BUG]: 使用ocr功能时出现错误怎么办求救

### ISSUE THREAD

**Issue by qingpingwan** [pot-app/pot-desktop#321]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

<img width="343" alt="image" src="https://github.com/pot-app/pot-desktop/assets/116857184/f45d6945-5156-43d9-9029-6a22e38d36e8">

使用默认的ocr功能出现这个错误了😢😢

### Reproduction

下载后没有乱动ocr选项的

### Platform

Windows

### System Version

win11

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
首次使用需要下载数据，OCR语言选择自动检测的话会下载全部语言的数据，建议在OCR设置里面指定一下语言，很快就下好了。

**Comment by qingpingwan** [comment]
我发现现在截图ocr可以使用了，但是截图翻译不能使用😭
求救大家😭

**Comment by Pylogmon** [comment]
你那个截图不是报错，是正常的流程信息，等一会就好了

**Comment by qingpingwan** [comment]
我发现了使用ocr识别时速度很快，大概几秒钟。
但是直接使用ocr翻译时翻译一个句子需要将近30s的等待。
不知道是这两个功能相同但调用了不同api吗，速度相差好大啊😭
