### ISSUE TITLE
设置了快捷键，但是在按下相应组合案件后无任何反映

### ISSUE THREAD

**Issue by jjshe** [pot-app/pot-desktop#325]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

![image](https://github.com/pot-app/pot-desktop/assets/20296577/2d6e237f-37c8-403c-bf16-76aec2b0315e)
系统是ubantu 22.04 安装包是 pot_1.11.0_amd64.deb，反复设置快捷键后，不能成功唤醒

### Reproduction

在按下相应组合案件后无任何反映

### Platform

Linux

### System Version

ubantu 22.04 

### Window System(Linux Only)

None

### Software Version

 pot_1.11.0_amd64.deb

**Comment by Pylogmon** [comment]
看你的截图，你应该是在Wayland环境下，Wayland下应用内的快捷键设置我是禁用了的，我不知道你是怎么设置的，请看官网文档Wayland部分，通过系统设置来设置快捷键。

**Comment by jjshe** [comment]
![image](https://github.com/pot-app/pot-desktop/assets/20296577/6c2e4100-64c9-4f69-8fee-b2f449eb3280)
文档实在是看不懂。在哪里设置自定义快捷键？
![image](https://github.com/pot-app/pot-desktop/assets/20296577/2571446e-556c-44bb-9ead-c4782b3164ec)

**Comment by Pylogmon** [comment]
Ubuntu的系统设置，有自定义快捷键相关的设置

![image](https://github.com/pot-app/pot-desktop/assets/59004461/319813eb-6a1e-4c2e-8c4d-4d9748cd81ca)

**Comment by jjshe** [comment]
ok!搞定了多谢了。
