### ISSUE TITLE
系統OCR無法使用

### ISSUE THREAD

**Issue by lp43** [pot-app/pot-desktop#328]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

Tesseract在1.11.0版被強制拿掉後，改由系統OCR取代，但系統OCR在我的電腦根本沒有任何反應。

### Reproduction

1. Windows視窗下方工具列右側，滑鼠右鍵點擊Pot Icon，跳出選單視窗
2. 點擊［截圖OCR］
3. 拖拉選取出欲翻譯之英文，跳出OCR視窗
4. 視窗左下角OCR方式選擇［系統OCR］
5. 點擊視窗下方右側［重新辨識］
6. 視窗右側辨識結果框毫無反應（註：以前使用Tesseract時有反應）

### Platform

Windows

### System Version

作業系統版本：Windows 10 專業版
版本：2004
安裝於：2021/4/29
OS組建：19041.928
系統類型：64位元作業系統
處理器：Intel(R) Core(TM) 7-9700 CPU @ 3.OOGHz 3.00GHz

### Window System(Linux Only)

None

### Software Version

Pot版本：1.11.1

### Additional Information

圖片示意：
![图片](https://github.com/pot-app/pot-desktop/assets/59004461/a5ca7006-6178-43e9-ab67-dbe47a0e3a26)

**Comment by Pylogmon** [comment]
切换语言试试，如果你系统不是英文，默认是没有安装英语语言包的。
