### ISSUE TITLE
[BUG]: mac m2pro 想使用辅助功能控制电脑 操作无效

### ISSUE THREAD

**Issue by Cyria7** [pot-app/pot-desktop#330]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [x] I have searched through the historical issues but could not find an answer.

### Description

下载安装后始终弹出pot.app想要使用辅助功能来控制这台电脑，在系统设置-隐私与安全-辅助功能中打开允许pot控制本电脑的选项仍旧弹出“想要使用辅助功能来控制这台电脑”弹窗

### Reproduction

安装即可

### Platform

MacOS

### System Version

MacBook pro m2pro ventura13.5

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
去设置里面在辅助功能权限里面把pot手动删了之后再添加就可以了，有可能每次软件更新之后还得这么操作一次，我现在没有mac设备没有办法解决，只能这样了。

**Comment by Cyria7** [comment]
解决了，非常感谢
