### ISSUE TITLE
[Feature]: 希望翻译接口添加openl

### ISSUE THREAD

**Issue by ZGLinus** [pot-app/pot-desktop#332]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

希望在应用里面添加OpenL的翻译接口。

### Application Scenario

OpenL可以免翻使用gfw阻挡的部分翻译。
![image](https://github.com/pot-app/pot-desktop/assets/69845097/1e16d45d-3e40-4ebb-a39d-d2d861f7f27e)

### References

OpenL文档地址
https://docs.openl.club/#/

**Comment by Pylogmon** [comment]
并不免费，而且价格很贵，不打算支持。

**Comment by ZGLinus** [comment]
可以通过签到获取免费字符。
