### ISSUE TITLE
[Feature]: 热键功能不支持鼠标键

### ISSUE THREAD

**Issue by Mayday646** [pot-app/pot-desktop#335]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

热键功能不支持鼠标键, 例如侧键 中键

### Application Scenario

配合划词翻译 单手就可以操作, 不需要总是按键盘热键,而且 键盘热键容易与其他应用冲突

**Comment by Pylogmon** [comment]
不打算支持鼠标快捷键，你可以配合其他软件来实现。
