### ISSUE TITLE
[Feature]: flatpak支持

### ISSUE THREAD

**Issue by shtingeri** [pot-app/pot-desktop#336]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

支持flatpak，从而支持更多发行版，不必专门为每个发行版打包

### Application Scenario

Linux发行版众多，一一打包耗时耗力

**Comment by Pylogmon** [comment]
不会打flatpak，不过一般来说如果有各个发行版自己的包格式，当然优先使用发行版自己的包格式，flatpak可以作为可选的选项，但是不可能只提供flatpak来代替其他包，我提供最常见的deb包完全可以满足打包需要，对于打包者来说解包来打包其他发行版的格式也很方便。如果有需要你可以自己打包flatpak，投递flathub，但是如果不打算长期维护软件包，请不要投递flathub。

**Comment by ga1aksy** [comment]
现在PR有了
https://github.com/flathub/flathub/pull/4651

**Comment by Pylogmon** [comment]
> 现在PR有了 [flathub/flathub#4651](https://github.com/flathub/flathub/pull/4651)

太好了！如果需要在仓库中添加文件，你可以开一个PR
https://github.com/flathub/flathub/pull/4651#discussion_r1377565185

另外，关于pot-app.com,因为最近在备案，所以无法访问，应该不影响的吧。
