### ISSUE TITLE
[Feature]: 添加功能：复制完文字，按快捷键弹出独立窗口后软件自动粘贴内容到翻译窗口。

### ISSUE THREAD

**Issue by bio-er** [pot-app/pot-desktop#337]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

按下快捷键弹出独立窗口后，软件能自动将内容粘贴至翻译窗口【非剪贴板监听】

### Application Scenario

-

**Comment by Pylogmon** [comment]
划词翻译在没有选择文本的情况下是会自动读取剪切板的

**Comment by bio-er** [comment]
> 划词翻译在没有选择文本的情况下是会自动读取剪切板的

我指的不是【划词翻译】，而是【独立翻译窗口】，我在第三方软件复制了东西，按下独立翻译窗口的快捷键调出独立窗口，此时能否直接在窗口填充我复制的内容？或者做个开关。

**Comment by Pylogmon** [comment]
独立翻译窗口说到底他的作用是输入翻译，不会考虑这种用例，这种情况请使用划词翻译。
