### ISSUE TITLE
[BUG]: Contributors section not displaying in readme

### ISSUE THREAD

**Issue by ArslanYM** [pot-app/pot-desktop#343]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

Contributors section not displaying in readme

### Reproduction

Check the contributors section in README.md

### Platform

Windows

### System Version

11

### Window System(Linux Only)

None

### Additional Information

![contributors sections isnt working in readme](https://github.com/pot-app/pot-desktop/assets/104521101/08a16084-c3dc-4a41-98cd-0a18f43799b4)

**Comment by Pylogmon** [comment]
Perhaps this is just a problem with your internet connection? It is displaying normally on my computer.

![image](https://github.com/pot-app/pot-desktop/assets/59004461/9df0bc80-c760-4a55-b0e4-1c73202f2790)

**Comment by ArslanYM** [comment]
Yes, My bad.
