### ISSUE TITLE
[Feature]: 字体

### ISSUE THREAD

**Issue by reflyable** [pot-app/pot-desktop#344]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

希望可以调整翻译区和UI的字体

### Application Scenario

默认字体有点丑

### References

翻译区的字体比较容易修改，UI的字体简单修改`theme.typography.fontFamily`似乎不奏效，没有精力进一步探究了

**Comment by Pylogmon** [comment]
不好实现，也没有必要，pot的字体应该是跟系统字体统一的

**Comment by chawyehsu** [comment]
Just a note for anyone encountering the same issue, it looks terrible on Windows with MacType on, you may exclude `pot.exe` to get it work with the default font..
![image](https://github.com/pot-app/pot-desktop/assets/5764917/c34712cc-c1d5-4d74-9442-aef7608e508b)
