### ISSUE TITLE
开发文档中介绍的windows系统下snip直接开启pot不可用

### ISSUE THREAD

**Issue by chinaywx** [pot-app/pot-desktop#345]
我下载snip后在文本扩展中并没有找到pot的开启选项，在插件商店中也没有找到，可能需要自己设计脚本，但在windows中如何设置启动pot的脚本呢？

**Comment by Pylogmon** [comment]
既然你看了文档，那你第二第三步为什么不照做呢？
![图片](https://github.com/pot-app/pot-desktop/assets/59004461/601667cd-2881-42e3-bd8f-213a7f5c2dac)
