### ISSUE TITLE
[BUG]: 辅助功能权限 macOS

### ISSUE THREAD

**Issue by ZhuZheart98** [pot-app/pot-desktop#346]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

我已经按照程序的要求，授予了辅助功能权限，但是每次打开都提示  《“pot”想使用辅助功能来控制这台电脑。》，重新授予之后，pot也没有打开

### Reproduction

打开pot

### Platform

MacOS

### System Version

13.1 (22C65)

### Window System(Linux Only)

None

### Additional Information

<img width="481" alt="截屏2023-07-31 15 41 38" src="https://github.com/pot-app/pot-desktop/assets/35882447/2b712b14-2cbc-4888-ae12-3f40d0fb9011">
<img width="469" alt="截屏2023-07-31 15 41 51" src="https://github.com/pot-app/pot-desktop/assets/35882447/005fa574-85d4-4f5b-b7e7-5315ac0c1aad">

**Comment by Pylogmon** [comment]
从辅助功能列表中删除pot后重新添加。

**Comment by ZhuZheart98** [comment]
可以了，谢谢
