### ISSUE TITLE
[Feature]: please request build APPimage format in linux

### ISSUE THREAD

**Issue by newyorkthink** [pot-app/pot-desktop#351]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

APPimage format thay may it can run every linux disto

### Application Scenario

build APPIMAG format file

**Comment by Pylogmon** [comment]
I won't provide AppImage packages until Tauri's AppImage bundler supports all architectures (x86_64, i386, aarch64, armv7).

**Comment by Pylogmon** [comment]
I only provide the AppImage package for the x64 architecture.

https://pot-app.com/download
