### ISSUE TITLE
[BUG]: linux i3wm cannot show small window use pot-desktop , it just open in next tab window

### ISSUE THREAD

**Issue by newyorkthink** [pot-app/pot-desktop#352]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

[BUG]: linux i3wm cannot show small window use pot-desktop , it just open in next tab window

### Reproduction

[BUG]: linux i3wm cannot show small window use pot-desktop , it just open in next tab window

### Platform

Linux

### System Version

[BUG]: linux i3wm cannot show small window use pot-desktop , it just open in next tab window

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
At present, pot cannot be specially adapted to WM. If you want to implement window floating in WM, please add your own window rules to implement it. You can refer to the configuration method of Hyprland in README.
