### ISSUE TITLE
快捷键设置（macOS）

### ISSUE THREAD

**Issue by ZhuZheart98** [pot-app/pot-desktop#353]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

快捷键设置（macOS），能不能设置两个同样的按键作为快捷键。比如command+C+C。这样使得快捷键更为方便。

### Application Scenario

这样使得快捷键更为方便。比如command+C+C。复制的时候与翻译的时候按同一套快捷键就行，只要控制按的次数，app就知道，是需要复制，还是需要翻译。

**Comment by Pylogmon** [comment]
这不是标准的快捷键，你可以借助第三方软件来实现，pot本身不会支持这种快捷键。

**Comment by ZhuZheart98** [comment]
好的，谢谢

**Comment by m565664180** [comment]
可否请教下, 哪些 第三方软件 能够设置 CTRL + CC 这类的快捷键呢
