### ISSUE TITLE
[Feature]: title简体中文的系统自带OCR识别，多余空格，每个字后边都带一个空格

### ISSUE THREAD

**Issue by changecool** [pot-app/pot-desktop#354]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

如题，能不能像删除行一样，删除这些空格

### Application Scenario

如题，能不能像删除行一样，删除这些空格

**Comment by Pylogmon** [comment]
已修复
