### ISSUE TITLE
[BUG]: Trojan

### ISSUE THREAD

**Issue by Havokdan** [pot-app/pot-desktop#358]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

![pot](https://github.com/pot-app/pot-desktop/assets/6549729/d7fb9d7f-0a84-4397-8890-771d0f00f7b0)

### Reproduction

Periodic system scan. Kaspersky Standard.

### Platform

Windows

### System Version

Windows 10 x64

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
I have encountered the same problem reported by Windows Defender, and some people have encountered the same problem in Tauri's issue. I don't know the reason yet.

**Comment by Havokdan** [comment]
It still happens to me, removes the "unistall.exe" file and the application's installer, removes the application's shortcuts too, however, its executable remains in the installation folder and it is possible to use it.

**Comment by Pylogmon** [comment]
#381
