### ISSUE TITLE
[BUG]: 设置界面部分文字丢失

### ISSUE THREAD

**Issue by awayukii** [pot-app/pot-desktop#359]
### Please confirm the following before submitting a new issue.

- [x] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

设置界面似乎通过快速切换功能选项会导致界面部分文字丢失。

![2023-08-10-225930_hyprshot](https://github.com/pot-app/pot-desktop/assets/107755412/2c6477ac-7855-416b-a94f-788d1d4b7499)

### Reproduction

通过快速点击左侧各个功能选项即可复现下图。
![2023-08-10-231048_hyprshot](https://github.com/pot-app/pot-desktop/assets/107755412/68b4472c-38c9-4d00-8903-59648a1688a0)

### Platform

Linux

### System Version

OS: Arch Linux x86_64
Kernel: 6.4.9-arch1-1 
WM: Hyprland 
Shell: bash 5.1.16

### Window System(Linux Only)

Wayland

### Software Version

pot:1.13.1  Tauri:1.4.1

### Additional Information

包来源Archlinuxcn

**Comment by Pylogmon** [comment]
这个问题我也发现了，但是是最近一个月才出现的问题，我猜是新版本webkit2gtk引入的bug。
