### ISSUE TITLE
[BUG]: Windows下划词窗口无法拖动

### ISSUE THREAD

**Issue by cccpism** [pot-app/pot-desktop#36]
### 问题描述

在独立窗口实时翻译后，无论左上角的固定按钮是否开启，当尝试拖动翻译窗口时，翻译窗口都会自动关闭

### 如何复现

在独立窗口实时翻译后，无论左上角的固定按钮是否开启，当尝试拖动翻译窗口时，翻译窗口都会自动关闭

### 操作系统

Windows (Default)

### 窗口系统(Linux Only)

None

**Comment by Pylogmon** [comment]
这个是已知问题，由于Windows下拖动或改变窗口大小的时候，会导致webview失去焦点，由于窗口绑定了失去焦点自动关闭的事件，所以会直接关闭，这个后续tauri升级之后会解决，不过由于已经实现了在鼠标位置出现窗口以及自定义窗口大小，我觉得这个问题暂时还是可以忍受的，不过这个应该是只在划词翻译的窗口中有问题，独立窗口应该是不存在这个问题的，请再确认一下

**Comment by cccpism** [comment]
> 这个是已知问题，由于Windows下拖动或改变窗口大小的时候，会导致webview失去焦点，由于窗口绑定了失去焦点自动关闭的事件，所以会直接关闭，这个后续tauri升级之后会解决，不过由于已经实现了在鼠标位置出现窗口以及自定义窗口大小，我觉得这个问题暂时还是可以忍受的，不过这个应该是只在划词翻译的窗口中有问题，独立窗口应该是不存在这个问题的，请再确认一下

啊对，这个是口误，是划词翻译的窗口不能拖动，正常的设置界面是可以拖动的。

**Comment by Pylogmon** [comment]
虽然问题没有解决，但是现在翻译窗口点击置顶让其不自动关闭之后就可以拖动了。

**Comment by bylevel** [comment]
我提了一个 PR #163 来修复这个问题。
