### ISSUE TITLE
[BUG]: Debian12系统使用2块显示器时无法使用

### ISSUE THREAD

**Issue by zyu0211** [pot-app/pot-desktop#362]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

只使用笔记本自带的显示器时，能正常工作，但是拓展第二块显示器时，OCR功能无法使用。

### Reproduction

1、将第二块屏幕设置为复制屏幕模式，OCR功能正常，能够识别出截取的图片上文字。
复制模式：
![image](https://github.com/pot-app/pot-desktop/assets/93979574/0ec9f026-4747-44fc-bf7f-53b0e81c200c)
效果：正常使用
![image](https://github.com/pot-app/pot-desktop/assets/93979574/f3878cad-b40b-4d0d-a207-69010cfc3513)

2、当将第二块屏幕设置为拓展模式时，使用截图OCR时，不能截取显示器当前的界面，而是会显示上一次OCR截图正常时的画面，且OCR识别不了。
拓展模式：
![image](https://github.com/pot-app/pot-desktop/assets/93979574/ac076807-c854-4404-8ff2-61547beae566)
效果：无法使用
![Screenshot_20230811_164849](https://github.com/pot-app/pot-desktop/assets/93979574/d47e3bcc-40c9-4e91-8aa2-0088dd5424d1)

### Platform

Linux

### System Version

操作系统： Debian GNU/Linux 12
KDE Plasma 版本： 5.27.5
KDE 程序框架版本： 5.103.0
Qt 版本： 5.15.8
内核版本： 6.1.0-10-amd64 (64 位)
图形平台： X11

### Window System(Linux Only)

None

### Software Version

1.14.0 和 1.13.1

**Comment by Pylogmon** [comment]
OCR只会在鼠标所在的屏幕启动，不知道你所说的是不是这个问题。

**Comment by lutianen** [comment]
**Me too**

**Comment by zyu0211** [comment]
> OCR只会在鼠标所在的屏幕启动，不知道你所说的是不是这个问题。

是拓展屏幕时，启动OCR，我的鼠标所在的窗口，会显示上一次OCR正常工作时的画面，而不是当前的画面。并且截取图片去识别时，就出现上面的错误。

**Comment by Pylogmon** [comment]
我现在有一个解决办法，可以像Wayland的解决方案那样，用flameshot来截图,完整命令如下：

```bash
rm ~/.cache/com.pylogmon.pot/pot_screenshot_cut.png && flameshot gui -s -p ~/.cache/com.pylogmon.pot/pot_screenshot_cut.png && pot screenshot_ocr without_screenshot
```

你可以不用pot软件内的快捷键设置，在系统设置中设置一个自定义快捷键，填入这段命令。

**Comment by zyu0211** [comment]
> 

可以使用了，谢谢！

**Comment by hotspringGG** [comment]
> 我现在有一个解决办法，可以像Wayland的解决方案那样，用flameshot来截图,完整命令如下：
> 
> ```shell
> rm ~/.cache/com.pylogmon.pot/pot_screenshot_cut.png && flameshot gui -s -p ~/.cache/com.pylogmon.pot/pot_screenshot_cut.png && pot screenshot_ocr without_screenshot
> ```
> 
> 你可以不用pot软件内的快捷键设置，在系统设置中设置一个自定义快捷键，填入这段命令。

这么处理会有个bug, flameshot截图完之后窗口会正常出现但要手动从任务栏打开，不会弹出到顶层

**Comment by Pylogmon** [comment]
你是Gnome环境吗，tauri的窗口在Gnome下会无法获取焦点，这有可能是Gnome的问题。

**Comment by hotspringGG** [comment]
> 你是Gnome环境吗，tauri的窗口在Gnome下会无法获取焦点，这有可能是Gnome的问题。

不是 我和题主一样是KDE

**Comment by Pylogmon** [comment]
https://github.com/pot-app/pot-desktop/issues/45#issuecomment-1518691559

**Comment by hotspringGG** [comment]
关闭组织焦点抢占后正常
