### ISSUE TITLE
[Feature]: 请添加对Google OCR的支持

### ISSUE THREAD

**Issue by JamesW99** [pot-app/pot-desktop#363]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

请添加对Google OCR的支持

### Application Scenario

对海外用户来说，国内的接口响应速度太慢，那些自托管的结果又不是非常理想。

### References

google ocr每个月有提供1000条免费额度
https://bobtranslate.com/service/ocr/google.html#_7-%E8%8E%B7%E5%8F%96%E7%A7%98%E9%92%A5-%E5%87%AD%E6%8D%AE

**Comment by Integral-Tech** [comment]
安装 Google OCR 插件即可支持：https://github.com/Integral-Tech/pot-app-recognize-plugin-google
