### ISSUE TITLE
[Feature]: 增加弹出位置固定的功能

### ISSUE THREAD

**Issue by KawausoJyou** [pot-app/pot-desktop#364]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

现在只能跟随鼠标位置弹出窗口，希望增加可以固定为某位置弹出的功能

### Application Scenario

不用每次寻找窗口位置

**Comment by Pylogmon** [comment]
86869f884cc47eba1f44208384707a1aeaf009c0
