### ISSUE TITLE
卡巴斯基报毒

### ISSUE THREAD

**Issue by hxqsb** [pot-app/pot-desktop#366]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

在1.14.0x64中，卡巴斯基报毒拦截

### Reproduction

更新与安装过程
![image](https://github.com/pot-app/pot-desktop/assets/92349810/3afa16c3-ccf1-482f-bcf1-a7d600d6d726)

### Platform

Windows

### System Version

Windows 11 专业工作站版22621.2134

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
#358
