### ISSUE TITLE
[Feature]: Multi screen support

### ISSUE THREAD

**Issue by hotspringGG** [pot-app/pot-desktop#367]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

OCR translate and screenshot translate is only support the main screen, But there has 2 screen on my computer. I'd like to use the translator between 2 screens.

### Application Scenario

Somebody has multi screens

### References

There are 2 solutions that I can think.
1. get the translate widget（window）[or mouse position] of the screen and take a shot of the screen
2. don't limit the choosing mouse in one screen,the selector can cross between 2 screens(But I don't know whether elecron apps can do like this,  we can refer to the "flameshot" screenshot app)

**Comment by Pylogmon** [comment]
#362
