### ISSUE TITLE
[Feature]: Multi screen support

### ISSUE THREAD

**Issue by hotspringGG** [pot-app/pot-desktop#369]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

add support for multi screens. when screenshot translate and ocr translate.

### Application Scenario

the users has 2 and more screens connected to PC.

### References

there are 2 solutions.
1.  check for mouse position and take a right shot of the right screen .
2.  make the selector can cross screens (e.g flameshot)

**Comment by Pylogmon** [comment]
为什么你要一次又一次地提交重复issue，上一个issue我已经指向了已知issue然后关闭了，你难道看不懂吗？

**Comment by hotspringGG** [comment]
> 为什么你要一次又一次地提交重复issue，上一个issue我已经指向了已知issue然后关闭了，你难道看不懂吗？

对不起，以为网卡了没交上（）
