### ISSUE TITLE
pot闪退

### ISSUE THREAD

**Issue by zcpin** [pot-app/pot-desktop#370]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

pot从windows 商店安装或者是从github下载后安装，运行后在任务栏有个图标，不管是用左键单击还是右键打开菜单，点击右键菜单里的任意菜单都会闪退

### Reproduction

![image](https://github.com/pot-app/pot-desktop/assets/13887961/2a186459-54d4-4ace-a2f6-6e7d1e953c56)

### Platform

Windows

### System Version

Windows 11 专业版 25387.1200

### Window System(Linux Only)

None

### Software Version

1.13.1

**Comment by Pylogmon** [comment]
检查是否卸载或者禁用了webview2，另外你所说的Windows商店版本是什么，可以给我个链接吗？

**Comment by zcpin** [comment]
确实是webview2 的问题，已经解决，感谢
