### ISSUE TITLE
[Feature]: 修正使用指南

### ISSUE THREAD

**Issue by Nyayurn** [pot-app/pot-desktop#375]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

[划词翻译窗口跟随鼠标位置](https://pot-app.com/docs/tutorial/config/wayland#%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91%E7%AA%97%E5%8F%A3%E8%B7%9F%E9%9A%8F%E9%BC%A0%E6%A0%87%E4%BD%8D%E7%BD%AE)中windowrule的class大小写错误, 应将pot更改为Pot

### Application Scenario

因为给的不能用)

**Comment by Pylogmon** [comment]
可能是因为你改成了x11？我在Wayland环境下测试的时候class name就是pot
