### ISSUE TITLE
[BUG]: gpt3.5-turbo模型翻译长篇文本时，只能返回800多个汉字，超出的内容会直接断掉。

### ISSUE THREAD

**Issue by wathper** [pot-app/pot-desktop#380]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

pot中使用openai的gpt3.5-turbo模型翻译长篇文本时，只能返回800多个汉字，超出的内容会直接断掉。而在其他集成了gpt3.5-turbo的模型的软件中要求gpt翻译同样的文本则能返回完整的1600多个汉字。

请问是pot有隐藏的 gpt Prompt 限制了模型回答的字数吗？
还是说有其他的原因？

### Reproduction

可多次复现

### Platform

Windows

### System Version

win10专业版22H2

### Window System(Linux Only)

None

### Software Version

 1.14.0

**Comment by Pylogmon** [comment]
确实是，设置了max-token，后续会在2.0版本中取消。
