### ISSUE TITLE
卡巴斯基报毒 PDM:Trojan.Win32.Generic

### ISSUE THREAD

**Issue by chenzhenpeng** [pot-app/pot-desktop#381]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

[pot_1.14.0_x64-setup.exe卡巴斯基报毒](url) PDM:Trojan.Win32.Generic
![微信截图_20230818142458](https://github.com/pot-app/pot-desktop/assets/20313782/2b129d1a-fa09-4357-a502-7b7b27b9729a)

### Reproduction

下载pot_1.14.0_x64-setup.exe进行安装，卡巴斯基提示 PDM:Trojan.Win32.Generic，并进行清除操作

### Platform

Windows

### System Version

Windows 11 专业版22621.2134

### Window System(Linux Only)

None

### Software Version

pot_1.14.0_x64-setup.exe

**Comment by puff-dayo** [comment]
我这边也出现了卡巴斯基的相同报毒。
不过，这边今天不少开源软件都被卡巴斯基报毒、清除了，猜测是卡巴斯基今天推送的病毒数据库有问题。
![图片](https://github.com/pot-app/pot-desktop/assets/84665734/aa0af144-6b36-4ba1-bafd-de1e499d7a13)

**Comment by puff-dayo** [comment]
我这边也出现了相同报毒，但是怀疑是因为卡巴斯基今天推送的病毒数据库出了问题，因为我这边有其他几个程序也被识别成病毒了。

![图片](https://github.com/pot-app/pot-desktop/assets/84665734/ff323a33-7765-46e3-a7da-765a103de4a8)

**Comment by chq-github** [comment]
应该不是卡巴斯基8.18的病毒库问题吧......
我8.24也遇到了
已经再提交了一遍

**Comment by sbwfnhn** [comment]
同样卡巴斯基安全软件


回滚已完成
pot_1.14.0 x64-setup (1).exe
pot 1.14.0 x64-setup (1).exe D: 12520
DESK 活动用户
回滚应用程序的操作 PDM:Trojan.Win32.Generic
回滚应用程序的操作: PDM:Trojan.Win32.Generic
pot 1.14.0 x64-setup (1).exe
进程已终止
pot_1.14.0 x64-setup (1).exe D: 12520
DESK 活动用户 进程已完成
进程已完成
A cross-platform translation software pot 1.14.0 x64-setup (1).exe D: 12520
对象已删除
DESK 活动用户
已删除
已删除: PDM:Trojan.Win32.Generic
PDM:Trojan.Win32.Generic
进程已终止
A cross-platform translation software pot 1.14.0 x64-setup (1).exe D: 12520
检测到恶意对象 A cross-platform translation software pot 1.14.0 x64-setup (1).exe D: 12520
DESK 活动用户
已终止: PDM:Trojan.Win32.Generic
DESK 活动用户 检测到: PDM:Trojan.Win32.Generic
已终止
检测到
PDM:Trojan.Win32.Generic
PDM:Trojan.Win32.Generic
类型 威胁级别 精确度 对象
对象名称
木马 高
木马 信息
木马高
木马 高
木马 高
确切
确切
确切
确切
pot_1.14.0 x64-setup (1).exe pot 1.14.0 x64-setup (1).e
pot.exe
pot.exe
pot 1.14.0 x64-setup (1).exe pot 1.14.0 x64-setup (1).e
pot 1.14.0 x64-setup (1).exe pot 1.14.0 x64-setup (1).ex
pot 1.14.0 x64-setup (1)exe pot 1.14.0 64-setup (1).e
