### ISSUE TITLE
[BUG]: 开机自启动不稳定

### ISSUE THREAD

**Issue by Qian-F** [pot-app/pot-desktop#383]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

自启动不稳定

### Reproduction

~

### Platform

Windows

### System Version

win11 insider preview Build 23526.ni-prerelease.230811-1344

### Window System(Linux Only)

None

### Software Version

pot:1.14.0  Tauri:1.4.1

**Comment by Qian-F** [comment]
2.0beta版本依旧不能完成开机自启动

**Comment by Qian-F** [comment]
@Pylogmon

**Comment by Pylogmon** [comment]
关闭重设就好了吧，检查一下任务管理器里面有没有禁用

**Comment by Qian-F** [comment]
> 关闭重设就好了吧，检查一下任务管理器里面有没有禁用

试过了 任务管理器里面也是启用着

**Comment by Qian-F** [comment]
![image](https://github.com/pot-app/pot-desktop/assets/111696321/8ceef23c-5a0b-40ff-b9d1-bb6956e837de)

**Comment by CyshallChan** [comment]
我这边也遇到了这个问题

**Comment by Qian-F** [comment]
应该是这个问题
后续尝试后反馈
![image](https://github.com/pot-app/pot-desktop/assets/111696321/6e65a015-5eff-4c08-8f9e-ecd174d6cda7)

**Comment by Qian-F** [comment]
解决方法有效

**Comment by CyshallChan** [comment]
@Pylogmon 麻烦作者看一下是否可以将修改注册表操作内置到程序里呢？

**Comment by Pylogmon** [comment]
你是一直使用管理员权限运行Pot的吗？

**Comment by Qian-F** [comment]
因为管理员权限才能更新 所以一直使用管理员权限启动（确信
