### ISSUE TITLE
[Feature]: 监听剪切板,当内容改变时翻译

### ISSUE THREAD

**Issue by CylAlon** [pot-app/pot-desktop#384]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

1.监听剪切板,当内容改变时,显示窗口并翻译.
2.当选中文本时在选中区域上方一个区域显示翻译结果.

### Application Scenario

现在的使用方式是:选中文本后点击快捷键并打开翻译,或者固定窗口翻译剪切板的内容.
这个样子稍微有点麻烦,窗口显示会遮挡部分屏幕.
我只需要选中就立即在选中上方显示一个自适应窗口并翻译,这样方便许多,屏幕也不会遮挡太多.

**Comment by Pylogmon** [comment]
#415
