### ISSUE TITLE
[BUG]: 在安装时卡巴斯基报毒

### ISSUE THREAD

**Issue by chq-github** [pot-app/pot-desktop#392]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

如题，
我是从https://pot-app.com/download 页面中的Windows(x64).exe下载的。
**初步下载卡巴斯基无报毒，当安装程序执行到"安装pot.exe"时，卡巴斯基开始报毒，显示为木马病毒，如下图所示**

![image](https://github.com/pot-app/pot-desktop/assets/114080995/577673cb-624d-4218-be80-632f57440463)
**随后卡巴斯基开始清除程序已安装部分的文件，以及系统缓存文件，如下图：**
![image](https://github.com/pot-app/pot-desktop/assets/114080995/badae23f-fc8d-45a6-9f84-fc4ebb96fc17)
![image](https://github.com/pot-app/pot-desktop/assets/114080995/0a867ab9-31db-4aa0-87b7-148afca9f4d2)

希望能够尽快回复~~

### Reproduction

1.从https://pot-app.com/download 上下载Windows(x64).exe
2.请确保您用的安全软件为：Microsoft Defender+火绒个人版5.0.73.13+卡巴斯基免费版21.14.5.462
3.双击打开pot安装程序，直到安装到pot.exe安装完成之后
4.这时卡巴斯基应该就要提醒有木马病毒了

### Platform

Windows

### System Version

Windows11家庭版 23H2 22631.2191（需要加入Windows preview频道的体验计划）

### Window System(Linux Only)

None

### Software Version

pot版本：1.14.0
------------
下面是杀毒软件版本
1.Microsoft Defender
2.火绒安全个人版5.0.73.13
3.卡巴斯基免费版 21.14.5.462

### Additional Information

none

**Comment by sbwfnhn** [comment]
同样问题，卡巴斯基安全软件 个人版收费版

**Comment by handsomeliyao** [comment]
我也是这样的问题...楼主解决了嘛
