### ISSUE TITLE
[Feature]: 可以实现像slidepad那样的侧边触发吗

### ISSUE THREAD

**Issue by Skaiyin** [pot-app/pot-desktop#393]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

可以实现像[slidepad](https://slidepad.app)那样的侧边触发吗

### Application Scenario

快捷使用

**Comment by Pylogmon** [comment]
#371
