### ISSUE TITLE
[BUG]: snip.do free 插件文本扩展中无pot扩展，如何向snip中添加pot扩展

### ISSUE THREAD

**Issue by cxf-pid** [pot-app/pot-desktop#396]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

snip.do free 插件文本扩展中无pot扩展，如何向snip中添加pot扩展

### Reproduction

snip.do free 插件文本扩展中无pot扩展，如何向snip中添加pot扩展

### Platform

Windows

### System Version

snip.do free 插件文本扩展中无pot扩展，如何向snip中添加pot扩展

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
官网文档写的很清楚
![image](https://github.com/pot-app/pot-desktop/assets/59004461/f417a8d1-bba2-4adf-a278-bf6e47e1bba9)

**Comment by cxf-pid** [comment]
sorry 我的问题 没仔细看
