### ISSUE TITLE
[Feature]: 希望可以支持 双击ctrl 或者 鼠标中键 的热键设置

### ISSUE THREAD

**Issue by grecod** [pot-app/pot-desktop#397]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

热键设置中支持双击CTRL、或者鼠标中键的设置，这样可以快速调出划词翻译的窗口

### Application Scenario

CTRL是比较常用的快捷组合键，但是离它比较近的组合基本都有系统功能，使用其他键又不太方便，所以支持双击是一个不错的选择

### References

可以参考有道词典的双击CTRL功能
![微信图片_20230831153429](https://github.com/pot-app/pot-desktop/assets/33012341/031daf83-63af-42c8-9020-5fec08d55ff2)

**Comment by Pylogmon** [comment]
不打算支持非标准快捷键，pot提供完整的外部调用接口，你可以通过第三方软件来实现需求。
