### ISSUE TITLE
[Feature]: 是否可以实现预翻译，加快划词翻译的速度

### ISSUE THREAD

**Issue by grecod** [pot-app/pot-desktop#398]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

增加预翻译，加快划词翻译结果展示的速度

### Application Scenario

弹出划词翻译的窗口之后不管是一个单词还是一句话，基本都要等1~2s才能看到翻译结果
像Deepl这种相应时间都比较久，影响使用体验

### References

1、监测鼠标选择的内容，预先进行翻译，用户按下快捷键后可以更快的看到翻译结果
2、增加离线翻译也可以加快翻译速度： #388

**Comment by Pylogmon** [comment]
国内的翻译接口基本上都是不到一秒就可以出结果，离线翻译后续可能会提供插件来支持，预翻译不打算支持。
