### ISSUE TITLE
[Feature]: Beta2.0 建议在服务设置中添加停止使用的选项或按钮

### ISSUE THREAD

**Issue by lisontowind** [pot-app/pot-desktop#400]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

![image](https://github.com/pot-app/pot-desktop/assets/47842345/be1e23c5-40e8-41a3-9bd0-82e1d14ce83b)
如图，只有编辑和删除，希望添加一个是否启用的按钮。

### Application Scenario

虽然重新点击配置会记录之前的配置信息，但是略微有点误导。

**Comment by Pylogmon** [comment]
删除之后就是停用了，感觉再加一个开关感觉徒增界面复杂度。

**Comment by Pylogmon** [comment]
已添加
