### ISSUE TITLE
[BUG]: 2.0 版本命令行参数无法使用

### ISSUE THREAD

**Issue by awarewen** [pot-app/pot-desktop#401]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

I run with this command in terminal to use pot by manual:
```
grim -g "$(slurp)" ~/.cache/com.pylogmon.pot/pot_screenshot_cut.png && pot screenshot_ocr without_screenshot
```
but pot talked me this:  `pot is already running` 
![图片](https://github.com/pot-app/pot-desktop/assets/53365857/b96b3279-ec92-4dc5-9c07-20cc8f33bb83)

-  backend
![图片](https://github.com/pot-app/pot-desktop/assets/53365857/1c66c171-4e6b-48df-a3a4-54bebf443e10)

### Reproduction

Step 1: run this command in terminal 
`grim -g "$(slurp)" ~/.cache/com.pylogmon.pot/pot_screenshot_cut.png && pot screenshot_ocr without_screenshot`
or any command in that
![图片](https://github.com/pot-app/pot-desktop/assets/53365857/3e1f6dc5-1097-45b3-9c00-99115fec8cea)

Step 2: Select on screen to translated something
Step 3: got this warnning
![图片](https://github.com/pot-app/pot-desktop/assets/53365857/200dd9ad-db6b-484d-b479-fa9eedeac8f5)

### Platform

Linux

### System Version

- `hyprctl version`
 ```
Hyprland, built from branch main at commit f69c5469d79f31f77f4662731ac6255e285febed dirty (readme: refactor and update a bit).
Tag: v0.29.0-21-gf69c5469

flags: (if any)
```
- `uname -a`
```
Linux Archwen 6.1.50-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 30 Aug 2023 14:44:21 +0000 x86_64 GNU/Linux 
```

### Window System(Linux Only)

Wayland

### Software Version

```
Name            : pot-translation-bin
Version         : 2.0.0.beta.0-1
Description     : 一个跨平台的划词翻译软件
Architecture    : x86_64
URL             : https://github.com/pot-app/pot-desktop
Licenses        : GPL3
Groups          : None
Provides        : pot-translation
Depends On      : webkit2gtk  gtk3  libayatana-appindicator  xdotool  libxcb  libxrandr  tesseract  tessdata
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : pot-translation  pot-translation-git
Replaces        : None
Installed Size  : 45.11 MiB
Packager        : Unknown Packager
Build Date      : Sat 02 Sep 2023 07:16:36 PM CST
Install Date    : Sat 02 Sep 2023 07:16:40 PM CST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

### Additional Information

This information from the terminal info:

https://fars.ee/e3Pw

![图片](https://github.com/pot-app/pot-desktop/assets/53365857/6a95c17a-8268-484d-821a-adf9ed12a801)

在昨天未更新桌面前，pot 运行正常，再次感谢作者和维护者们的付出，希望 Pot 能越来越好。感谢你们让 WM 下面也能有这么好用的翻译工具，方便，快捷。谢谢！

**Comment by Pylogmon** [comment]
2.0版本删除了命令行参数，全部统一为http调用，由于还没有发布正式版所以文档没有更新，你可以通过curl向`127.0.0.1:port` 发送请求，其中`port`默认为60828，在软件设置中可以更改。

### 目前支持的接口如下：
```bash
POST "/" => 翻译指定文本(body为需要翻译的文本),
GET "/config" => 打开设置,
GET "/translate" => 翻译指定文本(同"/"),
GET "/selection_translate" => 划词翻译,
GET "/input_translate" => 输入翻译,
GET "/ocr_recognize" => 截图OCR,
GET "/ocr_translate" => 截图翻译,
GET "/ocr_recognize?screenshot=false" => 截图OCR(不使用软件内截图),
GET "/ocr_translate?screenshot=false" => 截图翻译(不使用软件内截图),
GET "/ocr_recognize?screenshot=true" => 截图OCR,
GET "/ocr_translate?screenshot=true" => 截图翻译,
```

### 示例：

- 调用划词翻译：
```bash
curl "127.0.0.1:60828/selection_translate"
```
- Wayland 下使用 grim 截图OCR：
```bash
grim -g "$(slurp)" ~/.cache/com.pot-app.pot-desktop/pot_screenshot_cut.png && curl "127.0.0.1:60828/ocr_recognize?screenshot=false"
```
- 翻译 "Hello World"：
```bash
curl "127.0.0.1:60828/translate" -X POST -d "Hello World"
```

**Comment by awarewen** [comment]
明白了，谢谢
