### ISSUE TITLE
[Feature]:2.0版本可以支持隐藏dock栏图标吗

### ISSUE THREAD

**Issue by Kurt-Shiwz** [pot-app/pot-desktop#402]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

我想隐藏dock栏图标，好像没有找到选项
![image](https://github.com/pot-app/pot-desktop/assets/7554917/eeb9d9c0-05bb-4650-b394-a4363859d06a)

### Application Scenario

有快捷建和状态栏的图标就够了，不习惯dock栏上有太多东西，分散注意力。希望可以提示一个选项，隐藏图标

**Comment by Pylogmon** [comment]
是Bug，我忘了设置激活策略，已经修复。

**Comment by uxfion** [comment]
mac 3.0.7版本有隐藏dock栏图标吗？我没有找到
