### ISSUE TITLE
[BUG]: openai error 405

### ISSUE THREAD

**Issue by Qian-F** [pot-app/pot-desktop#404]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

![image](https://github.com/pot-app/pot-desktop/assets/111696321/6579fa8a-bb8c-464d-ac52-3ed8fa9d2db3)

### Reproduction

使用[此项目](https://github.com/chatanywhere/GPT_API_free)配置报错

### Platform

Windows

### System Version

win 11

### Window System(Linux Only)

None

### Software Version

2.0beta

**Comment by Pylogmon** [comment]
在其他软件中成功过吗？

**Comment by Qian-F** [comment]
1.x版本可以使用 更新后不可用

**Comment by Pylogmon** [comment]
怎么填写的，配置发我邮箱我试试

**Comment by Qian-F** [comment]
地址填: https://api.chatanywhere.com.cn
API密钥填[这里](https://api.chatanywhere.cn/v1/oauth/free/github/render)获取的

**Comment by Pylogmon** [comment]
2.0版本把域名和路径合起来了，你需要填 https://api.chatanywhere.com.cn/v1/chat/completions

**Comment by Qian-F** [comment]
好的我去尝试一下

**Comment by Qian-F** [comment]
成功了 感谢

**Comment by zacblyhx** [comment]
> 2.0版本把域名和路径合起来了，你需要填 https://api.chatanywhere.com.cn/v1/chat/completions

大哥，地址用的你说的，免费的key是[Qian-F]发的地址获取的，2.0版本，就是成功不了

**Comment by Qian-F** [comment]
> > 2.0版本把域名和路径合起来了，你需要填 https://api.chatanywhere.com.cn/v1/chat/completions
> 
> 大哥，地址用的你说的，免费的key是[Qian-F]发的地址获取的，2.0版本，就是成功不了

我成功了 所以这是你自己的问题 和软件/KEY无关

**Comment by Pylogmon** [comment]
> 我成功了 所以这是你自己的问题 和软件/KEY无关
你用的这个服务不支持跨域，是不能开启流式输出的。
