### ISSUE TITLE
[Feature]: Option for automatically replacing source text with target text after swapping languages (Beta 2.0)

### ISSUE THREAD

**Issue by RYSKZ** [pot-app/pot-desktop#405]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

Hello,
I was wondering whether it is possible to automatically replace the source text with the target text after clicking the new button introduced in the beta version to swap source and target languages.

### Application Scenario

Many popular translation tools, such as Google Translate, DeepL and Bing, employ an automatic text swap feature when users click the language switch button. This feature is very valuable for several reasons. First, it simplifies the task of making small changes in the target language and then conveniently switching back to the source language. In addition, it helps to improve the quality of written content in a given language without the need for actual translation when using services such as DeepL, which helps to correct grammatical and stylistic errors.

### References

I have incorporated a few lines of code into [this file](https://github.com/pot-app/pot-desktop/blob/master/src/window/Translate/components/LanguageArea/index.jsx).
Specifically, I added the following lines of code at lines 23 and 24:

`
    const sourceText = useAtomValue(sourceTextAtom);
`
`
    const targetText = useAtomValue(targetTextAtom);
`

Furthermore, on line 99, I included the following code:

`sourceText.setSourceText(targetText);`

Subsequently, I proceeded to build the application. Although the build process completed without errors, when I tried to access the translation window it did not appear and when I started a selection translation it did not work. Unfortunately, the application log did not provide any useful information or error messages to help diagnose the problem, so I don't know what I am doing wrong.

**Comment by Pylogmon** [comment]
Since multiple interfaces are translated at the same time, this leads to a question: Which interface result should be put into the source text box during exchange?

My solution to this is to process each interface separately. You should notice that there is a new button in the button area of ​​each interface. The function of this button is what I call back translation, which can translate the text back to the source language.

**Comment by RYSKZ** [comment]
Yes, that's an important question, and it's something I hadn't considered before, as my current usage is primarily with DeepL, which doesn't involve handling multiple interfaces simultaneously.

If I understand your suggestion correctly, it's to process each interface separately and introduce a dedicated button, akin to the back translation feature, that allows users to switch the source and target text of each interface individually. This approach seems like a reasonable solution to address this issue.

Another option could be to swap the source text with the target text of the interface that is positioned first in the list. However, I think that this solution is less intuitive and less flexible than your proposed method of having a separate button for each translation interface.

**Comment by Pylogmon** [comment]
![image](https://github.com/pot-app/pot-desktop/assets/59004461/5ad944e2-c13a-4f9c-b586-6c42a562d315)

**Comment by RYSKZ** [comment]
But that button you are referring to does not swap the text that is written in the source area, so it won't let me edit it. What I was hoping for is the ability to replace the source text with the translated text from a specific interface. This would allow me to edit it directly without the need to manually copy and paste it into the source area, which is slow and annoying.
