### ISSUE TITLE
[BUG]: v2版的弹窗尺寸不会记忆, 也无法设置.

### ISSUE THREAD

**Issue by shuohua2000** [pot-app/pot-desktop#407]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

以前v1版的弹窗, 可以直接拖动调整大小, 下次再弹窗会使用上次的尺寸, 现在的v2版弹窗都是固定尺寸, 每次弹窗翻译都要手动调整, 太不方便了. 反馈以上, 谢谢作者!

### Reproduction

翻译弹窗

### Platform

Windows

### System Version

win10 22H2

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
设置里有记住窗口大小选项
