### ISSUE TITLE
[Feature]: 希望v2版可以保留翻译弹窗的快速下拉选择翻译服务的功能.

### ISSUE THREAD

**Issue by shuohua2000** [pot-app/pot-desktop#408]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

以前v1版的弹窗, 可以直接下拉选择翻译服务提供商. 现在只能在设置中选取固定的翻译服务. 而不能在弹窗中快捷更换了.

### Application Scenario

其实这个功能非常好用, 使用场景:
平常翻译使用Google或者Deepl, 对于需要精翻或有特殊要求的, 则使用openAI的api来翻译.
但是如果在设置选项中直接使用openAI, 则日常所有的翻译都使用openAI, 会浪费很多tokens. 这时v1版中的弹窗中下拉选择翻译服务就太有用了!
希望能够添加回来, 谢谢!

**Comment by Pylogmon** [comment]
已添加

**Comment by shuohua2000** [comment]
太棒了, 这是最完美的翻译软件!
