### ISSUE TITLE
[BUG]: 划词翻译弹出窗口不在最顶层

### ISSUE THREAD

**Issue by lifeformg** [pot-app/pot-desktop#410]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

设置快捷键以后，划词并按快捷键翻译时，弹出的翻译窗口会位于当前窗口的下面，因此看不到翻译窗口。

### Reproduction

将划词翻译快捷键设为f1，划词，按f1，屏幕上不会显示翻译窗口，移开当前置顶窗口后，可以看到弹出的翻译窗口在下面。

### Platform

Linux

### System Version

操作系统： KDE neon 5.27
KDE Plasma 版本： 5.27.7
KDE 程序框架版本： 5.108.0
Qt 版本： 5.15.10
内核版本： 6.2.0-31-generic (64 位)
图形平台： X11

### Window System(Linux Only)

X11

### Software Version

2.0.0

**Comment by Pylogmon** [comment]
应该是没有获取到焦点导致的

https://github.com/pot-app/pot-desktop/issues/45#issuecomment-1518691559

**Comment by lifeformg** [comment]
> 应该是没有获取到焦点导致的
> 
> [#45 (comment) #45（评论）](https://github.com/pot-app/pot-desktop/issues/45#issuecomment-1518691559)

确实是这个问题，解决了，感谢
