### ISSUE TITLE
[BUG]: OCR不再能使用以前的方式进行外部截图

### ISSUE THREAD

**Issue by hotspringGG** [pot-app/pot-desktop#411]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

OCR不再能使用#362的方式使用flameshot进行截图

### Reproduction

rm ~/.cache/com.pylogmon.pot/pot_screenshot_cut.png && flameshot gui -s -p ~/.cache/com.pylogmon.pot/pot_screenshot_cut.png && pot screenshot_ocr without_screenshot

### Platform

Linux

### System Version

Linux 6.3.0-kali1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.3.7-1kali1 (2023-06-29) x86_64 GNU/Linux

### Window System(Linux Only)

X11

### Software Version

v2

**Comment by hotspringGG** [comment]
![image](https://github.com/pot-app/pot-desktop/assets/78401087/af6020a4-3f30-4394-86b6-fce1b196ccf1)

**Comment by Pylogmon** [comment]
#401

**Comment by hotspringGG** [comment]
Solution:
把原来的命令换成
rm ~/.cache/com.pot-app.desktop/pot_screenshot_cut.png && flameshot gui -s -p ~/.cache/com.pot-app.desktop/pot_screenshot_cut.png && curl "127.0.0.1:60828/ocr_recognize?screenshot=false"
