### ISSUE TITLE
[BUG]: snipDo 画词翻译异常

### ISSUE THREAD

**Issue by gclm** [pot-app/pot-desktop#412]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

使用snipDo 划词翻译，出现下图错误

### Reproduction

![image](https://github.com/pot-app/pot-desktop/assets/27618687/0891935a-b33b-4280-b978-4d22d87fe3a8)

### Platform

Windows

### System Version

Windows 11 家庭中文版

### Window System(Linux Only)

None

### Software Version

v2.0.0

### Additional Information

1

**Comment by Pylogmon** [comment]
重新下载安装pot最新的snipdo扩展

**Comment by Siris-Limx** [comment]
请问最新的snipdo插件在哪里下载？plug-in list里似乎没有

**Comment by gclm** [comment]
1. 在2.0 版本的release 下载的
2. plugin list 有
![image](https://github.com/pot-app/pot-desktop/assets/27618687/6c4313b4-6b16-4f35-8712-3749d0618278)

![image](https://github.com/pot-app/pot-desktop/assets/27618687/da6e6dbb-d500-40a4-8b79-0a6dfe6e13c5)

**Comment by Pylogmon** [comment]
> 请问最新的snipdo插件在哪里下载？plug-in list里似乎没有

https://pot-app.com/docs/tutorial/config/plugin_config#%E7%8E%B0%E6%9C%89%E7%94%A8%E6%B3%95-%E5%BF%AB%E6%8D%B7%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91

**Comment by Pylogmon** [comment]
如果问题解决请关闭issue

**Comment by Hezhexi2002** [comment]
@Pylogmon 请问下载了最新的snipdo扩展之后还是会出现一样的问题是怎么回事，pot也是最新版本：
![image](https://github.com/pot-app/pot-desktop/assets/53631206/69ac4ece-1921-4219-9c89-130f3a77f462)
![image](https://github.com/pot-app/pot-desktop/assets/53631206/d0c5d1ec-5eb2-4030-bc70-6ca1a40584f4)
![image](https://github.com/pot-app/pot-desktop/assets/53631206/41786b4b-563f-4062-9962-f4ea053be798)
