### ISSUE TITLE
[Feature]: v2.0是否不支持从当前目录读取config.json文件了？

### ISSUE THREAD

**Issue by pirately** [pot-app/pot-desktop#413]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### 功能描述

**平台**：Windows11

**需求**：`1.x`版本时，可以从当前目录，即pot.exe同级别目录，读取`config.toml`。但是`v2.0`不行了。那么，可以和`1.x`版本一样，同目录读取配置文件吗？或者指定配置文件所在目录读取？

### Application Scenario

还是希望软件可以做到便携化，这样，我放到U盘里面，就可以带着走了。因为每次出差，都要和单位换不同笔记本。

**Comment by pirately** [comment]
> 2.0支持设置备份了，可以通过网盘来同步，而且软件也不提供绿色版，我觉得没有必要再添加这个功能了。

1. 利用alist挂载的阿里云盘，可以备份成功，但是读取不了
2. 虽然可以网络备份，但是每次在新环境，都要输入webdav的网址还有用户名和密码，这个肯定没有直接放目录读取方便
3. webdav备份，也不是所有人都有的。

**Comment by Pylogmon** [comment]
阿里云盘好像是有开放平台，后续我会尝试直接对接阿里云盘
当前目录我也会考虑添加，但是由于插件系统依赖于本地标准路径，所以有可能不会成功

**Comment by pirately** [comment]
> 阿里云盘好像是有开放平台，后续我会尝试直接对接阿里云盘 当前目录我也会考虑添加，但是由于插件系统依赖于本地标准路径，所以有可能不会成功

十分感谢，期待这个功能

**Comment by Pylogmon** [comment]
现在的配置系统从当前目录读取配置不太可行，所以我加了本地备份的功能，一定程度上也能解决问题。
