### ISSUE TITLE
[Feature]: 恢复剪贴板监听功能

### ISSUE THREAD

**Issue by RedwindA** [pot-app/pot-desktop#415]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

恢复之前的剪贴板监听功能

### Application Scenario

我一般将POT翻译窗口常驻在副屏，看材料时自动监听剪切板翻译很方便（因为翻译窗口甚至不允许通过鼠标右键粘贴（win 10），不使用时就关掉监听，但是2.0这个选项没有了

**Comment by Cyria7** [comment]
同样的问题，mac arm版本2.0.2版本没有检测板监听了

**Comment by Pylogmon** [comment]
我是觉得1.0的剪切板监听功能很鸡肋，必须得窗口开启才能用，我打算在2.0加一个通过托盘菜单开启的剪切板监听模式，剪切板内容改变之后会直接调用翻译窗口来翻译
