### ISSUE TITLE
[BUG]: 内存占用巨大！！望作者优化。

### ISSUE THREAD

**Issue by Hello-hao** [pot-app/pot-desktop#416]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

不明白一个简单的翻译软件占用这么大的内存，竟占用我450MB，是为什么？
隔壁友商`TT**`的同功能翻译程序使用同样的功能仅占用100多MB内存。
希望作者排查优化一下，不是我没这点内存，而是这种工具类型的软件占用这么大，感觉很不合理。
![内存占用截图](https://i.postimg.cc/K81TFkH9/RAM.png)

### Reproduction

运行程序，打开翻译或设置窗，内存就直线飙升

### Platform

Windows

### System Version

Windows 11

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
默认开启了本地语种识别引擎，需要加载语言模型，这个内存占用比较大，在翻译设置中把语种检测引擎切换为百度后重启软件可以显著降低内存占用。

**Comment by Integral-Tech** [comment]
右击 Pot 托盘图标 -> 偏好设置 -> 翻译设置，将语种检测引擎改为**百度**或**谷歌**（谷歌需要科学上网）

**Comment by nlzqg** [comment]
切换语种检测引擎为百度后，内存占用还是会跑到500M+,最多能到700M，而且还下不了，现在退回1.14，会好非常多，系统win11-22621.2215

**Comment by Pylogmon** [comment]
> 切换语种检测引擎为百度后，内存占用还是会跑到500M+,最多能到700M，而且还下不了，现在退回1.14，会好非常多，系统win11-22621.2215

切换后重启软件生效
