### ISSUE TITLE
[BUG]: PaddleOCR识别时漏字

### ISSUE THREAD

**Issue by EsuRt** [pot-app/pot-desktop#418]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

使用PaddleOCR识别时漏字，用天若OCR集成的PaddleOCR测试了下，为发现漏字，是不是参数需要调整？

![1](https://github.com/pot-app/pot-desktop/assets/15177069/5bd00fd8-fb78-4628-bee6-801ac1aa9fe8)

### Reproduction

1、框选区域
2、选择PaddleOCR

### Platform

Windows

### System Version

Windows 10 企业版 22H2 19045.3324

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
由于要考虑跨平台，内置的Paddle采用的Web实现性能和效果都很有限，后续会通过插件提供效果更好的PaddleOCR支持，如果有需要可以关注这个仓库：https://github.com/pot-app/pot-app-recognize-plugin-paddle
