### ISSUE TITLE
[Feature]: API翻译能否增加返回文本的功能

### ISSUE THREAD

**Issue by EsuRt** [pot-app/pot-desktop#419]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

API调用翻译时会直接显示界面，能否直接返回文本，供其他软件联动使用，比如在goldendict中可以设置调用其他程序的命令
，但只能接收文本类数据，导致无法显示结果。如果能返回文本，可以弥补goldendict的一些缺陷（长句无法翻译）。

![2](https://github.com/pot-app/pot-desktop/assets/15177069/e48f0801-bcf1-4742-b156-b7e090f98437)

### Application Scenario

可以弥补goldendict的一些缺陷（长句无法翻译）

**Comment by Pylogmon** [comment]
作为客户端软件，Pot的Http接口是为调用Pot而实现的，不会提供这种类似服务端的功能。
