### ISSUE TITLE
升级2.0后，配置页面和输入翻译均无法打字

### ISSUE THREAD

**Issue by Dx0123** [pot-app/pot-desktop#420]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

操作系统是DeepinV23，安装的pot_2.0.0_amd64.deb，安装完成后配置页面（代理、服务设置）和输入翻译均无法打字，但可以点击按钮、可以设置快捷键。

### Reproduction

如上

### Platform

Linux

### System Version

Deepin V23

### Window System(Linux Only)

None

**Comment by Dx0123** [comment]
会不会是老版本（1.10.1）有冲突？

**Comment by Pylogmon** [comment]
会不会是输入法的问题，没有复现这个问题。

**Comment by Dx0123** [comment]
> 会不会是输入法的问题，没有复现这个问题。

输入法肯定没问题啊，一直用着的～

**Comment by Dx0123** [comment]
> 会不会是输入法的问题，没有复现这个问题。

我发现不管如何卸载重装，我1.10.1版本和2.0版本的配置始终都在，但仍然无法输入文字。今天安装了2.0.2版本也仍然不行，输入法是fctix5

**Comment by 668168** [comment]
mac m1 也遇到各种输入框无法输入问题. 今天最新版本

**Comment by Pylogmon** [comment]
已经找到问题了，下个版本修复
