### ISSUE TITLE
[BUG]: 使用划词搜索，原文已经输入后，会重复输入一次。

### ISSUE THREAD

**Issue by yoohooyoo** [pot-app/pot-desktop#425]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

使用划词搜索，原文已经输入后，会重复输入一次。

### Reproduction

![image](https://github.com/pot-app/pot-desktop/assets/10402472/32b33687-fecc-45fb-9739-d8af0c308b57)

### Platform

Windows

### System Version

win11

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
是开了增量翻译吗

**Comment by yoohooyoo** [comment]
> 是开了增量翻译吗

确实是，关闭后正常了。感谢。
