### ISSUE TITLE
[BUG]: 2.0.0 在 GNOME 上无法截图

### ISSUE THREAD

**Issue by linsui** [pot-app/pot-desktop#426]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

之前的版本在 GNOME 上可以截图，但 2.0.0 在应用窗口上截图是全黑的。实际上似乎并不是不能截图，而是在截图之前 pot 会弹出一个全屏黑窗口挡住屏幕。所以得到的这种效果

![image](https://github.com/pot-app/pot-desktop/assets/36977733/415795dc-3c26-42d1-a425-513b8acfe1c6)

### Reproduction

在 GNOME 上截图。

### Platform

Linux

### System Version

GNOME 44.3

### Window System(Linux Only)

Wayland

### Software Version

2.0.0

**Comment by Pylogmon** [comment]
Gnome首次截图的时候会询问截图权限，可能你没有同意？你也可以使用其他截图软件代替pot内置的截图，比如Flameshot

参考：https://github.com/pot-app/pot-desktop#%E4%B8%8D%E4%BD%BF%E7%94%A8%E8%BD%AF%E4%BB%B6%E5%86%85%E6%88%AA%E5%9B%BE

**Comment by linsui** [comment]
刚刚又试了一下，2.2.0 可以截图了。看起来是修好了？ :+1: 
感觉用外部工具截图之后放到指定文件夹有点不方便。我用 GNOME 内置的截图是已经绑定了快捷键的，给 Pot 截图的话就要绑定新的快捷键将截图放到指定路径。Pot 的内置截图用起来也没有 GNOME 的方便。如果可以直接从剪贴板获取图片会比较方便。不需要新的工具，也不需要设置新快捷键。可以截图之后再打开 Pot 识别翻译，也可以从别的地方，比如网页上直接复制图片。
