### ISSUE TITLE
[BUG]: 2.0.1 Google translate service error

### ISSUE THREAD

**Issue by tony-studio** [pot-app/pot-desktop#428]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

Google translate service error

### Reproduction

1. Add Buildin Service - google - Custom URL - input: https://translate.google.com -
Test FailedReferenceError: store is not defined.

2. Selection Translate - google result -
ReferenceError: store is not defined

### Platform

Windows

### System Version

Windows 10 22H2 19045.3393

### Window System(Linux Only)

None

**Comment by fyypll** [comment]
我也发现了这个问题，删掉谷歌翻译后无法通过添加内置服务功能加回去，点击保存会提示 store is not defined
![image](https://github.com/pot-app/pot-desktop/assets/47078372/c48ea20f-8c0d-4a96-bcbb-98bf3d0a1a71)
