### ISSUE TITLE
希望独立翻译窗口能添加选项读取剪贴板能及支持便携化运行

### ISSUE THREAD

**Issue by vvyoko** [pot-app/pot-desktop#43]
### 需求描述

1,独立翻译窗口能读取剪贴板
2,程序支持便携化运行

### 应用场景

1,其实划词翻译大概就是这种功能,但第三方程序自己设置剪贴板内容,然后调用此程序翻译也算一种需求吧...
单纯的增加一个选项或者像snipdo扩展那样增加个特殊启动参数都行
比方说 $potExe clip
($potExe popclip "$PLAIN_TEXT"  直接传入翻译文件好像有字符串数量限量,换行很麻烦)
说到这在win端好像没监控60828?我想像popclip那样通过curl调用结果提示连接失败了

2,安装后发现好像就两个文件?
pot.exe 加上 Roaming\cn.pylogmon.pot\config.toml
只要打包一个exe和配置文件为zip就可以了啊(并不,我自己试了程序不会读取程序目录下的config.toml)
便携化可以放网盘或U盘中,多端同步配置.

**Comment by Pylogmon** [comment]
1.是监测剪切板内容自动获取还是说提供一个按键来讲剪切板内容写入翻译框

**Comment by Pylogmon** [comment]
2. http端口只在mac下开启了，目的只是为了实现popclip调用，win和Linux因为可以直接通过命令行参数传递，所以不需要再开启http，另外一个很重要的原因是，实测在win下通过curl调用传递的内容，中文会由于编码问题出现乱码，所以命令行参数是最优解

**Comment by Pylogmon** [comment]
这样的话应用场景很有限啊，划词翻译不就干的这事情，如果要实现这个功能，你可以试着用现成的popclip参数调用，在调用的脚本里面读取剪切板后传递给pot

**Comment by Pylogmon** [comment]
已经添加了读取程序所在目录的配置文件，但是具体能不能在u盘使用我不清楚，请自行测试，但是snipdo调用肯定是无法使用的，因为不安装无法获取pot所在路径，只能自己编辑snipdo插件来使用。

**Comment by Pylogmon** [comment]
怎么会不能传递多行文本呢，获取到的多行文本直接传就好了呀，snipdo获取到的多行文本都能直接传啊🥺

**Comment by Pylogmon** [comment]
换行符传\n呀，难道你使用的时候要手动输入再传递吗，获取到的剪切板内容保存为变量直接传递变量就可以了呀

**Comment by Pylogmon** [comment]
我试了一下，这样是可以的
```powershell
pot.exe popclip "$(Get-Clipboard -Raw)"
```

**Comment by Pylogmon** [comment]
我刚刚调试的过程中也发现了，那样只解决了换行的问题，双引号的问题还是存在，在snipdo调用中同样存在，只能说powershell中对应双引号的处理太恶心了，我试了试用curl调用，换行和双引号都没有问题，但是中文会变成?

**Comment by Pylogmon** [comment]
用curl调用的话，这样可以解决中文乱码的问题

```powershell
$params =[System.Text.Encoding]::UTF8.GetBytes($(Get-Clipboard -Raw))

curl 127.0.0.1:60828 -Method POST -Body $params
```

**Comment by Pylogmon** [comment]
Ok了，现在解决了curl的编码问题，就可以全部都用http请求来调用了，这样不光解决了引号和换行符的问题，便携版也可以直接使用插件调用了，一举多得。

**Comment by Pylogmon** [comment]
下个版本发布之前你可以先用自动构建版本来测试[https://github.com/Pylogmon/pot/actions/runs/4772798819](https://github.com/Pylogmon/pot/actions/runs/4772798819)
