### ISSUE TITLE
[Feature]: 增加原来的一些词典

### ISSUE THREAD

**Issue by ChengMoo** [pot-app/pot-desktop#435]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

原来的类似有道词典、剑桥词典、沪江小D、MOJi辞書（日）、句酷等词典查，2.0能恢复吗

### Application Scenario

这种词典查单个单词还挺好用的

**Comment by linsui** [comment]
必应词典似乎也去掉了。

**Comment by linsui** [comment]
可以更新一下 Readme 吗？上面还写着支持这些词典。

**Comment by RepentStar** [comment]
附议，就是检测到文本为单个词语时调用本地或在线词典查词，而不是翻译

**Comment by Pylogmon** [comment]
添加了有道词典和剑桥词典，其他的不打算内置，关注插件吧
