### ISSUE TITLE
[BUG]: webdav exception

### ISSUE THREAD

**Issue by rainerosion** [pot-app/pot-desktop#436]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

An exception occurs when using webdav to backup or view the backups.
![image](https://github.com/pot-app/pot-desktop/assets/11945383/1fd81a19-61e4-475b-9ab9-e074f0edd756)
![1694139824976](https://github.com/pot-app/pot-desktop/assets/11945383/5fb3b133-81ad-46b3-997e-b04e44a30a8c)

### Reproduction

backup or view backup

### Platform

Windows

### System Version

 Windows 11 Professional Edition 22621.2215

### Window System(Linux Only)

None

**Comment by rainerosion** [comment]
> Please let me know which webdav service provider you are using so that I can test it. I have only tested [NutStore](https://www.jianguoyun.com) now, and there are no issues.

[infini-cloud.net](https://infini-cloud.net/en/)

**Comment by small32** [comment]
> Please let me know which webdav service provider you are using so that I can test it. I have only tested [NutStore](https://www.jianguoyun.com) now, and there are no issues.

我是用的是群晖NAS自带的WebDav服务

**Comment by Pylogmon** [comment]
麻烦在 [这里](https://github.com/pot-app/pot-desktop/actions/runs/6283144675) 下载自动编译的版本测试问题是否修复,我只能测试 infini-cloud, 群晖我没法测。
@small32 @rainerosion @jerryluo71
