### ISSUE TITLE
[Feature]: add two options to customize the response speeds of hotkeys and translation.

### ISSUE THREAD

**Issue by 1821746019** [pot-app/pot-desktop#437]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

It takes nearly 3 seconds to wake up the translation window. When I press `enter`, it also takes 3 seconds to start the translation.

### Application Scenario

There are no options to customize the response speeds of hotkeys or translation in the latest version(2.1.0). It is exactly slow and wastes a lot of my time waiting.
---
Adding these two options to customize the response speeds would greatly improve user experience. It would make the software much more efficient and save users a lot of time waiting. I sincerely appreciate the developers for working on these useful features. Users like me would be incredibly grateful.

### References

The unit of time is preferably milliseconds

**Comment by Pylogmon** [comment]
The three seconds you said is the time to wait for the window to appear or the time to start translating after the window appears?

**Comment by 1821746019** [comment]
After pressing the hotkey to show the translation window, it will take 3 seconds to wait for the window to appear.

After entering the word and pressing the `enter` key, I need to wait for three seconds before the translation starts.

If I select a text and press the hotkey to translate it, it will take 3 seconds to wait for the window to appear, but it will start to translate immediately after the window appears.

**Comment by Pylogmon** [comment]
The shortcut keys all start immediately after the call, there is no delay set, it is possible that the language detection slows down the speed, you can switch the language detection engine in the translation settings to try.

**Comment by 1821746019** [comment]
But, the screenshot also cannot respond immediately when the hotkey is activated. It seems that It's not the fault of language detection.

**Comment by 1821746019** [comment]
![uTools_1694921882108](https://github.com/pot-app/pot-desktop/assets/107804044/d7b7536a-c2f0-43f5-9244-613fe743856b)

**Comment by Pylogmon** [comment]
Due to the implementation method, the screenshot function cannot be as fast as the native screenshot software. If necessary, you can refer to the documentation and use pot with other screenshot software.
