### ISSUE TITLE
[BUG]: 翻译切换功能异常

### ISSUE THREAD

**Issue by rainerosion** [pot-app/pot-desktop#438]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

就是图片上的这个按钮作用是什么？原文和译文之间的切换？还是其他作用？
目前发现的问题，点击按钮第一次内容切换为原文，再点击第二次内容直接空了。
目前发现谷歌翻译似乎没问题，至少第二次点击没任何反应
![image](https://github.com/pot-app/pot-desktop/assets/11945383/cb7a8d83-a4ee-4680-b332-0bd0a6663e9b)

### Reproduction

点击两次该按钮

### Platform

Windows

### System Version

Windows 11 Professional Edition 22621.2215

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
这个按钮的功能是翻译会原语言，用于检查翻译结果是否准确，再次点击没有反应是正常的，清空内容是bug，后续版本会修复。
