### ISSUE TITLE
[Feature]: Could you consider an out-of-the-box, no-installation version for Windows?

### ISSUE THREAD

**Issue by cosmic-latte** [pot-app/pot-desktop#439]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

An out-of-the-box, no-installation version would be more convenient in some scenarios.
I found after searching that no similar issue has been raised, so I don't know if this suggestion is feasible or not, thanks!

### Application Scenario

For example, on a company computer where permissions are controlled, or you can put it on a removable hard drive and take it with you.

**Comment by Pylogmon** [comment]
As a software that relies on system webview, I do not plan to provide a portable version. If you need it, you can manually copy the installed exe file. If there is webview on other computers, you can run it directly.
As for the configuration files, I provide a local backup function, you can export them and quickly import the configuration on other computers.
