### ISSUE TITLE
[BUG]: title

### ISSUE THREAD

**Issue by Kurt-Shiwz** [pot-app/pot-desktop#441]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

画词翻译异常。翻译的是剪切板的内容，不是选中的词。

### Reproduction

![image](https://github.com/pot-app/pot-desktop/assets/7554917/65e73d55-5e24-4a6a-ba59-ab60e444108d)
![image](https://github.com/pot-app/pot-desktop/assets/7554917/c5ecc7dc-c61b-4da1-ab88-661049e35d47)
![image](https://github.com/pot-app/pot-desktop/assets/7554917/5b54d626-03f1-4224-bd86-0615f6708cce)

### Platform

MacOS

### System Version

13.5.1 

### Window System(Linux Only)

None

### Software Version

2.1.0

**Comment by Pylogmon** [comment]
没取到词的话回去读取剪切板来翻译，应该是辅助功能权限失效了，去系统设置里面辅助功能列表中把pot删了重新添加。
