### ISSUE TITLE
[BUG]: mac 授权后出现遮罩

### ISSUE THREAD

**Issue by GaoHu1997** [pot-app/pot-desktop#442]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

已授权，打开配置页面闪过，出现灰色遮罩遮挡界面

### Reproduction

安装，运行软件，打开 config，界面一闪而过，出现遮罩，遮挡界面
退出，授权（包括执行命令），运行软件，打开config,出现遮罩

### Platform

MacOS

### System Version

2.1.0

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
#449
