### ISSUE TITLE
Homebrew 的包不随版本自动更新

### ISSUE THREAD

**Issue by jhongyu** [pot-app/pot-desktop#447]
Homebrew 的包自从 `1.10.1` 开始就不随版本自动更新了，看起来是 `Update Homebrew cask` 这个 action 失败导致的，有计划看一下这个问题吗？

**Comment by Pylogmon** [comment]
刚刚更新了，我也不知道那个action为什么会失败，刚刚我把runner改成macos之后运行成功了。
