### ISSUE TITLE
[BUG]: 在MAC一打開視窗全灰屏

### ISSUE THREAD

**Issue by lp43** [pot-app/pot-desktop#449]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

一安裝完軟件並打開Pot，所有功能視窗皆為灰屏不可見。

### Reproduction

以下流程為單一示意：
1.安裝Pot Translate
2.到上方系統工具列左鍵點擊Pot Icon
3.選擇Input Translate
4.跳出Pot Translate視窗，呈現視窗灰屏
![issue](https://github.com/pot-app/pot-desktop/assets/338229/c435a98e-9a39-41c0-9007-8bb6ef3dd353)

### Platform

MacOS

### System Version

macOS Catalina 10.15.7 ( 19H2026 )
MacBook Pro ( 13 - inch , Mid 2012 )
Intel Core i5
2.5 GHz
21 16 GB 1600 MHz DDR3
Intel HD Graphics 4000 1536 MB

### Window System(Linux Only)

None

### Software Version

v2.2.0

**Comment by Pylogmon** [comment]
试试这个 https://github.com/pot-app/pot-desktop/suites/16005569795/artifacts/913654672

**Comment by Pylogmon** [comment]
2.2.1已修复
