### ISSUE TITLE
[BUG]: 文字识别不够准确，而且字体间隔太大，每个字之间都有空格

### ISSUE THREAD

**Issue by imnxg** [pot-app/pot-desktop#452]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

文字识别不够准确，而且字体间隔太大，每个字之间都有空格，去除比较麻烦
![image](https://github.com/pot-app/pot-desktop/assets/73350203/48daa70a-5cac-4f00-aa6f-9b5071077a43)

### Reproduction

文字识别功能

### Platform

Windows

### System Version

Windows 11 Home Edition

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
不行咱更新一下呢，旧版的问题就不要重复提了呗
