### ISSUE TITLE
代理设置不生效

### ISSUE THREAD

**Issue by LogicDX342** [pot-app/pot-desktop#453]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

设置代理后，依然无法使用Google和DeepL翻译，并且在vpn的log中也没有看到相应的请求。
![image](https://github.com/pot-app/pot-desktop/assets/52480482/5219c501-428a-45e9-ae33-910557c97b81)

![image](https://github.com/pot-app/pot-desktop/assets/52480482/0f55e8e4-dde0-422f-8672-d258998a3a6c)
DeepL则是报错Error429：Too many request， 但是走相同代理的网页端是正常的。
另外，代理设置里也无法输入用户密码

### Reproduction

V2RayN开启本地代理，在Pot中设置好相应的ip和端口后测试谷歌翻译

### Platform

Windows

### System Version

Windows 10

### Window System(Linux Only)

None

### Software Version

2.2.0

**Comment by Pylogmon** [comment]
代理重启应用生效

**Comment by LogicDX342** [comment]
感谢，已解决
