### ISSUE TITLE
[BUG]: Translate Chinese to Eglish via Snip.Do cause Pot crash

### ISSUE THREAD

**Issue by JasonLeeForOnly** [pot-app/pot-desktop#459]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

Translate Chinese to Eglish via Snip.Do cause Pot crash turn into transparent stuck window,not every time can be recurrent.
Like the pic below
![image](https://github.com/pot-app/pot-desktop/assets/47520063/3088c0e3-4114-4bdc-9f92-47aab762e665)

### Reproduction

1.Select words,use hot key to active Snip.Do
2.Select Pot to translate
3.Stuck

### Platform

Windows

### System Version

Windows 11 Professional Edition 22621.2215

### Window System(Linux Only)

None

### Software Version

Pot Version 2.2.1
Snip.Do Version 3.0.62.0

**Comment by JasonLeeForOnly** [comment]
Now I noticed translate Chinese character '删除' will 100% cause this issues,Other character likely happend with a lower oppertunity.

**Comment by chen-jingliang** [comment]
确实存在这个BUG，关掉翻译设置/自动删除换行问题解决。
![02](https://github.com/pot-app/pot-desktop/assets/28627641/fd730bc9-3c65-4a47-bc91-fa07533ec185)
![01](https://github.com/pot-app/pot-desktop/assets/28627641/e6a3edc3-41a1-4029-b15d-26fe9bad5c9d)

**Comment by Pylogmon** [comment]
Sorry, I can't reproduce this problem. Please tell me which translation interfaces you have enabled.

**Comment by JasonLeeForOnly** [comment]
> Sorry, I can't reproduce this problem. Please tell me which translation interfaces you have enabled.

Yes,I was using DeepL and Google translation interfaces

**Comment by JasonLeeForOnly** [comment]
> 掉翻译设置/
没有启用这个选项，依然会发生这个问题。
![image](https://github.com/pot-app/pot-desktop/assets/47520063/17adebcf-e60d-4d50-8c1e-103adb22774d)

**Comment by Pylogmon** [comment]
Okay, I found the problem, and it's because the structure of the content returned by Google Translate has changed.
