### ISSUE TITLE
[BUG]: 画线翻译窗口消失

### ISSUE THREAD

**Issue by Kurt-Shiwz** [pot-app/pot-desktop#460]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

有时候，用快捷键画词时，不自动翻译，点了一下翻译后窗口就消失了；
有时候，用快捷键画词时，直接窗口就消失了；
![image](https://github.com/pot-app/pot-desktop/assets/7554917/0ff30950-a754-4171-86b7-361afaf418f1)

### Reproduction

1 选中词
2 快捷键调出翻译

### Platform

MacOS

### System Version

13.5.2

### Window System(Linux Only)

None

### Software Version

2.2.1

**Comment by Pylogmon** [comment]
#459 #437

**Comment by EliDoves** [comment]
![image](https://github.com/pot-app/pot-desktop/assets/51412618/e7ab90f8-ccc0-4255-921e-75280ecf50b2)
### Win也有这样的情况
- __复现场景：__
1. 快捷键启动输入翻译之后输入内容回车时候
2. 偶尔选中文本调出翻译会这样
- __系统：__
Windows 11, version 22H2
- __软件版本：__
2.2.1
