### ISSUE TITLE
[BUG]: 单个词语翻译时窗口消失

### ISSUE THREAD

**Issue by xjin15** [pot-app/pot-desktop#463]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

翻译单个词语时，翻译窗口消失（透明化）好几个词语就不会。应该是个比较普遍的bug吧？
如图gif所示
![划词翻译窗口消失](https://github.com/pot-app/pot-desktop/assets/78125804/c12e7316-cf71-4d92-9804-1a6943b23c7b)

### Reproduction

1. 打开chrome浏览器
2. 打开任意一个有英文的网页
3. 双击/划词选中单独一个词语
4. pot翻译
5. 窗口先出现，然后消失
6. 同样方法选中一个词语以上的翻译内容
7. 问题解决

### Platform

Windows

### System Version

版本	Windows 11 家庭中文版
版本	22H2
操作系统版本	22621.2283
体验	Windows Feature Experience Pack 1000.22662.1000.0

### Window System(Linux Only)

None

### Software Version

pot 2.2.1
Snip.Do Free v3.0.63.0

**Comment by Pylogmon** [comment]
#459
