### ISSUE TITLE
[BUG]: 使用中窗口变成透明，且无法显示，重启仍然存在问题。

### ISSUE THREAD

**Issue by RebelYoung** [pot-app/pot-desktop#468]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

如图所示，大致几个小时会出现一次，是不是什么缓存卡满了？
![image](https://github.com/pot-app/pot-desktop/assets/59256512/da15ba9d-907b-42c5-a9db-d70628f1e5de)

### Reproduction

我通常使用snipdo的插件callback它，是不是snipdo的问题？

### Platform

Windows

### System Version

版本	Windows 10 专业版
版本号	22H2
安装日期	‎2021-‎03-‎02
操作系统内部版本	19045.3448
体验	Windows Feature Experience Pack 1000.19044.1000.0

### Window System(Linux Only)

None

### Software Version

v2.2.1

**Comment by Pylogmon** [comment]
Google的接口变动导致的，已经修了 #459
