### ISSUE TITLE
[BUG]: 下载更新失败

### ISSUE THREAD

**Issue by Kurt-Shiwz** [pot-app/pot-desktop#470]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

点击检查更新后，更新app版本，下载至100%后没有反应。
![image](https://github.com/pot-app/pot-desktop/assets/7554917/3082c608-06a9-4327-829a-38f494921344)

### Reproduction

1 点击检查更新
2 等待更新完成

### Platform

MacOS

### System Version

13.5.2

### Window System(Linux Only)

None

**Comment by Pylogmon** [comment]
完成的时候是有一个通知的，手动重启应用就好了。
