### ISSUE TITLE
[Enhancement]: 提升OCR热键响应速度

### ISSUE THREAD

**Issue by Pil0tXia** [pot-app/pot-desktop#472]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

目前，在按下截图热键后，当前画面会在一两秒后才被定格、可供截取。
理想的性能，是像QQ/微信一样，在按下热键后，立刻锁定画面，以供截取。

### Application Scenario

相关配置：

![image](https://github.com/pot-app/pot-desktop/assets/41445332/0d1e31be-8792-4afd-bd45-f4b4f82bc61c)

**Comment by sjhsbhqf** [comment]
太赞同了

**Comment by Anz-03** [comment]
选词也是需要等待一两秒，没有金山词霸反应快。不过好在这个有OCR

**Comment by Pylogmon** [comment]
把paddle删除之后响应速度已经快很多了，你使用的是最新版吗。

**Comment by sjhsbhqf** [comment]
可以，我这个赞同是在上一个版本提出的，现在已经很快了，谢谢

**Comment by sjhsbhqf** [comment]
2.5.1版本
