### ISSUE TITLE
[BUG]: “安装前卸载”完成后会弹出“无法卸载”的对话框

### ISSUE THREAD

**Issue by lb-fes** [pot-app/pot-desktop#473]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

双击 pot_2.3.0_x64-setup.exe 升级版本时，选择“安装前卸载”，完成后会弹出“无法卸载”的对话框
![Snipaste_2023-09-16_09-02-02](https://github.com/pot-app/pot-desktop/assets/51531901/2f957d55-0bd0-4130-bb3d-c6906755e659)
实际上已完成卸载，返回上一步，重新点安装即可完成升级

### Reproduction

1.双击 pot_2.3.0_x64-setup.exe 升级版本
2.选择“安装前卸载”
3.完成后会弹出“无法卸载”的对话框

### Platform

Windows

### System Version

Windows 10 专业版 19045.3448

### Window System(Linux Only)

None

### Software Version

2.3.0

### Additional Information

在之前的很多个版本升级时多次复现，不太影响使用就没有提

**Comment by Pylogmon** [comment]
已修复
