### ISSUE TITLE
[Feature]: title

### ISSUE THREAD

**Issue by itangqiao** [pot-app/pot-desktop#474]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

请问怎么安装支持有道词典，而不是有道翻译，谢谢！

### Application Scenario

希望可以支持一下，谢谢！

**Comment by Pylogmon** [comment]
已经加了的，下个版本就有了

**Comment by itangqiao** [comment]
> 已经加了的，下个版本就有了

❤
