### ISSUE TITLE
[Feature]: 希望能集成 微软TTS 和 MacTTS

### ISSUE THREAD

**Issue by wisinfun** [pot-app/pot-desktop#476]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

微软TTS的试听效果最好
https://bobtranslate.com/service/tts/microsoft.html

Mac TTS的高音质也很不错
<img width="715" alt="image" src="https://github.com/pot-app/pot-desktop/assets/41355260/793fbb3d-af0c-48ea-b06c-7c2af4f4cc46">

### Application Scenario

朗读效果更好

**Comment by Pylogmon** [comment]
这种特定平台独有的接口，后续会通过插件提供

**Comment by Pylogmon** [comment]
https://github.com/TechDecryptor/pot-app-tts-plugin-microsoft
