### ISSUE TITLE
[Feature]: 希望服务设置的每个服务可以单独设置代理

### ISSUE THREAD

**Issue by Ausli** [pot-app/pot-desktop#477]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

希望服务设置的每个服务可以单独设置代理，因为使用了梯子后雅虎服务不可用；

截图：
![image](https://github.com/pot-app/pot-desktop/assets/70201547/af064396-6c5a-432b-934b-c2e5f002e713)

操作系统
Windows (Default)

### Application Scenario

使用梯子后国内服务反应会变慢甚至不可用

**Comment by Pylogmon** [comment]
这是你的代理软件分流该干的事
