### ISSUE TITLE
[BUG]: 更新时无法关闭pot，而实际上pot并未运行

### ISSUE THREAD

**Issue by zcpin** [pot-app/pot-desktop#483]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

![image](https://github.com/pot-app/pot-desktop/assets/13887961/12b15245-b890-4e01-907b-f108b67fae48)
更新的时候提示不能关闭pot，我用的是管理员打开的pot，每次更新就安装中止

### Reproduction

每次启动pot的时候，跳出更新界面会产生这样的结果，我特意使用管理员方式运行了pot结果还是一样

### Platform

Windows

### System Version

Windows 11 企业版 22621.2283

### Window System(Linux Only)

None

### Software Version
2.3.0
_No response_

**Comment by Pylogmon** [comment]
已修复
