### ISSUE TITLE
[BUG]: WebDav备份的问题

### ISSUE THREAD

**Issue by small32** [pot-app/pot-desktop#484]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

WebDav备份首次成功，第二次就报错“decode error：custom：missing field ‘exception’”，且无法恢复

### Reproduction

WebDav备份首次成功，第二次就报错“decode error：custom：missing field ‘exception’”，且无法恢复

### Platform

Windows

### System Version

Windows 10 Home Edition 22H2 19045.3448

### Window System(Linux Only)

None

### Software Version

2.4.2

### Additional Information

看了下，第一次备份成功以后，在WebDav文件夹下建立了一个pot-app的子文件夹，然后备份的设置就在里面打包了一个zip

然后下次在备份就不行了，恢复也提示上门的报错，且显示”您还没有备份“

**Comment by Pylogmon** [comment]
Track at #436
