### ISSUE TITLE
[BUG]: WebDav备份只能一次，再次备份报错

### ISSUE THREAD

**Issue by jerryluo71** [pot-app/pot-desktop#485]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

第一次备份成功后，再次使用WebDAV服务类型进行备份，则会报错“decode error: custom: miss field 'exception'” 。

### Reproduction

在备份设置中，如果选择WebDAV服务类型进行备份，则会在WebDav服务器的路径中创建一个目录pot-app，然后备份一个文件，但再次进行备份，则会报错“decode error: custom: miss field 'exception'” 。如果更换备份路径，则继续创建pot-app文件夹，并可以备份，再次选择该路径备份，则还是报错。本地备份则没有问题。

### Platform

Windows

### System Version

Windows 10 专业版 22H2

### Window System(Linux Only)

None

### Software Version

Pot 2.4.2

**Comment by Pylogmon** [comment]
Track at #436
