### ISSUE TITLE
[BUG]: 快捷键呼出翻译窗口缓慢

### ISSUE THREAD

**Issue by detiam** [pot-app/pot-desktop#487]
### Please confirm the following before submitting a new issue.

- [X] I have carefully reviewed the official website's usage documentation.
- [X] I have searched through the historical issues but could not find an answer.

### Description

呼出翻译窗口需要1-2秒时间
---
https://github.com/pot-app/pot-desktop/assets/44510779/5f71509c-1cb5-4e82-9b4a-559eeb187af6

和演示图中一点就开的效果差别较大
---

![PREVIEW](https://github.com/ccslykx/Starry/blob/master/.assets/Starry_icon_preview.gif?raw=true)

### Reproduction

1. 设置中为划词翻译设置一个快捷键。
2. 点按快捷键呼出窗口。

### Platform

Linux

### System Version

Arch Linux x86_64 rolling

### Window System(Linux Only)

X11

### Software Version

2.4.3

### Additional Information

KDE 5.27.8
Linux kernel 6.5.2-arch1-2-lily (64 bit)

**Comment by webmasterliwei** [comment]
mac上也有这个问题

**Comment by webmasterliwei** [comment]
> mac上也有这个问题
<img width="232" alt="image" src="https://github.com/pot-app/pot-desktop/assets/22438086/6cfb76c6-3ae0-4061-9a14-60fd51fcbb8b">

**Comment by Sereinme** [comment]
Windows 上同样缓慢:sob:
>处理器	AMD Ryzen 7 PRO 3700U w/ Radeon Vega Mobile Gfx   2.30 GHz
  机带 RAM	16.0 GB (13.9 GB 可用)
系统类型	64 位操作系统, 基于 x64 的处理器
版本        Windows 11 专业版
版本        22H2
操作系统版本    22621.2283

**Comment by derekxia1988** [comment]
我的情况是第一次根本就呼不出面板，需要我手动打开面板一次才能后面才能呼出

**Comment by Pylogmon** [comment]
已经找到问题了，当前的PaddleOCR实现有严重的性能问题，下个版本直接把Paddle删了，后续想办法通过插件来实现，这个问题预计下个版本会有明显改善。

**Comment by detiam** [comment]
> 已经找到问题了，当前的PaddleOCR实现有严重的性能问题，下个版本直接把Paddle删了，后续想办法通过插件来实现，这个问题预计下个版本会有明显改善。

试了下pot里的PaddleOCR确实很慢。不过我直接用esearch里的ocr不慢一下就有了，虽然esearch打开截图窗口也不快。

**Comment by detiam** [comment]
如果以后能把Paddle加回来，希望能用上gpu加速

**Comment by Pylogmon** [comment]
> > 已经找到问题了，当前的PaddleOCR实现有严重的性能问题，下个版本直接把Paddle删了，后续想办法通过插件来实现，这个问题预计下个版本会有明显改善。
> 
> 试了下pot里的PaddleOCR确实很慢。不过我直接用esearch里的ocr不慢一下就有了，虽然esearch打开截图窗口也不快。

因为Pot没有Node环境，所以只能使用浏览器环境部署，后续打算通过插件支持C++版本的Paddle。
