### ISSUE TITLE
[Feature]: 请问可以支持一下取词功能吗？就像欧路词典的取词功能一样

### ISSUE THREAD

**Issue by itangqiao** [pot-app/pot-desktop#490]
### Description

鼠标移入上面，就知道单词意思了~

### Application Scenario

<img width="1091" alt="image" src="https://github.com/pot-app/pot-desktop/assets/44393379/90fa14be-c069-4871-b585-1215ed3c576c">

**Comment by Pylogmon** [comment]
做不了
