### ISSUE TITLE
[Feature]: 网页翻译

### ISSUE THREAD

**Issue by vw911** [pot-app/pot-desktop#497]
### Description

希望能够添加网页翻译功能，类似沉浸式翻译，沉浸式翻译已经不开源了

### Application Scenario

每天有大量查看英语新闻的需求，通过网页翻译快速筛选掉不感兴趣的新闻

**Comment by Pylogmon** [comment]
实现不了的，pot毕竟不是浏览器插件，我都是两者结合试用的，开不开源有什么所谓呢？
