### ISSUE TITLE
[BUG]: 更新2.x版本后无法使用第三方OpenAI代理服务

### ISSUE THREAD

**Issue by BylethC** [pot-app/pot-desktop#498]
### Description

永远报错404或者405 Undefined，但是

1. 我设置的方法没有变，1.x的老版本能用，2.x的新版本就不能用了
2. 测试了多个第三方代理服务，包括AI Proxy, Next AI, AI LS等等，全都不行
3. 确认了第三方代理服务是正常的，因为我把这些第三方代理服务的请求地址和key，复制到其它支持自定义OpenAI API请求地址的ChatGPT客户端，都能够正常工作

只有Pot疯狂报404和405

### Reproduction

更改Pot中OpenAI的请求地址为第三方请求地址，Key填第三方的代理Key

![image](https://github.com/pot-app/pot-desktop/assets/46842736/15df83c5-33db-4d4f-9582-58fe7b51056e)

### Platform

Windows

### System Version

Windows 11 22H2 1000.22662.1000.0

### Window System (Linux Only)

None

### Software Version

2.3.0

**Comment by Pylogmon** [comment]
请求地址写完整，1.0版本是URL和path分开设置的，2.0版本把这两个设置项合并了而已

**Comment by BylethC** [comment]
> 请求地址写完整，1.0版本是URL和path分开设置的，2.0版本把这两个设置项合并了而已

原来如此，谢谢您，懂了
