### ISSUE TITLE
[BUG]: 服务设置-文字识别窗口无效

### ISSUE THREAD

**Issue by jerryluo71** [pot-app/pot-desktop#504]
### Description

在服务设置界面中，如果点击文字识别窗口，只显示一个透明的边框，里面内容无法显示。只有在Windows的bar上右键点击Pot图标选择关闭，才能关闭Pot界面。

### Reproduction

打开Pot设置，选择服务设置，然后点击文字识别，即可看到问题。

### Platform

Windows

### System Version

Windows 10 专业版 22H2

### Window System (Linux Only)

None

### Software Version

2.5.0

**Comment by Pylogmon** [comment]
![image](https://github.com/pot-app/pot-desktop/assets/59004461/ceea55a8-a4bc-493d-bd8b-9465f3072449)

手动编辑配置文件把paddle删了就好了

**Comment by sjhsbhqf** [comment]
> ![image](https://user-images.githubusercontent.com/59004461/270172794-ceea55a8-a4bc-493d-bd8b-9465f3072449.png)
> 
> 手动编辑配置文件把paddle删了就好了

C:\Users\abc123456\AppData\Roaming\com.pot-app.desktop目录中的config.json配置文件

"recognize_service_list":["baidu_accurate_ocr","system","paddle","tesseract","simple_latex_ocr"]中的"paddle",删除。

目前已经好了   谢谢开发者

**Comment by Pylogmon** [comment]
离线OCR还有啊，只不过通过插件提供了而已

**Comment by hellofan1998** [comment]
没有用这个功能，只有这俩"recognize_service_list": ["tesseract", "system"],还是不行，授权不了，显示都已经授权了，但是每次打开还是提示要去授权，多次取消重新授权，重启软件，重启电脑都无效。。

**Comment by hellofan1998** [comment]
> 没有用这个功能，只有这俩"recognize_service_list": ["tesseract", "system"],还是不行，授权不了，显示都已经授权了，但是每次打开还是提示要去授权，多次取消重新授权，重启软件，重启电脑都无效。。

系统版本 macOS 14.0 (23A344)

**Comment by hellofan1998** [comment]
> > 没有用这个功能，只有这俩"recognize_service_list": ["tesseract", "system"],还是不行，授权不了，显示都已经授权了，但是每次打开还是提示要去授权，多次取消重新授权，重启软件，重启电脑都无效。。
> 
> 系统版本 macOS 14.0 (23A344)

找到原因了，系统 bug。在设置里面，辅助功能和录屏，选中 pot 点下面的-号移除，重新添加就好了
