### ISSUE TITLE
[Feature]: 希望弹窗是否钉住能套用上次设定，只要钉住一次之后都默认钉住

### ISSUE THREAD

**Issue by celebrki** [pot-app/pot-desktop#505]
每次想钉住弹窗都要重新点一次图标.
既然可以按ESC关掉弹窗，那么”弹窗是否钉住套用上次设定“应该也不会增加麻烦。

**Comment by Pylogmon** [comment]
加了个开关
![image](https://github.com/pot-app/pot-desktop/assets/59004461/dc5143ec-3319-4edb-b833-9d67bd3c74ba)
