### ISSUE TITLE
[BUG]: mac 下划词翻译只能读取剪切板

### ISSUE THREAD

**Issue by lblbk** [pot-app/pot-desktop#507]
### Description

使用划词翻译的时候翻译的剪切版的内容，正常不应该是翻译选中的这段文字的内容吗

剪切版内容：
<img width="249" alt="Screenshot 2023-09-25 at 18 10 13" src="https://github.com/pot-app/pot-desktop/assets/26684296/c9f8e243-e08a-4fd3-b15a-313b25cafc97">

翻译情况：
<img width="456" alt="image" src="https://github.com/pot-app/pot-desktop/assets/26684296/82548685-e084-41c5-8c09-ca41c06924ca">

### Reproduction

pot 2.5.2
mac 13。2.1
 注册划词翻译快捷键 `option+Q` , 选中文字翻译，翻译的剪切版内容

### Platform

MacOS

### System Version

13.2.1

### Window System (Linux Only)

None

### Software Version

2.5.2

**Comment by Pylogmon** [comment]
把辅助功能权限删了重新给

**Comment by lblbk** [comment]
> Window

ok 这个确实可以解决 感谢

**Comment by lblbk** [comment]
@Pylogmon 这个图标问题考虑一下吗，强迫症确实有点难受🤣
