### ISSUE TITLE
[BUG] 打开后右下角显示图标 但鼠标移动想点的时候 直接闪退了

### ISSUE THREAD

**Issue by 1540781622** [pot-app/pot-desktop#512]
[BUG] 打开后右下角显示图标 但鼠标移动想点的时候 直接闪退了

新装的W10 21H2系统 之前都没事 重新装了系统后出现这个问题

**Comment by Pylogmon** [comment]
新装的系统是精简版系统吗？有没有缺少什么组件，检查一下有没有WebView2

**Comment by 1540781622** [comment]
还是不行...
https://imgur.com/Jnzhdie

**Comment by 1540781622** [comment]
0.0解决了 重新安装MicrosoftEdgeSetup后重启就可以了

**Comment by Pylogmon** [comment]
你是从哪里下载的便携版吗，安装的时候会检查webview的，这就是我为什么不提供便携版。

**Comment by 1540781622** [comment]
是下载的安装包.
