### ISSUE TITLE
[BUG]:使用快捷键进行划词翻译时无效

### ISSUE THREAD

**Issue by chen-jingliang** [pot-app/pot-desktop#513]
### Description

使用快捷键进行划词翻译时无效，只出现之前翻译的内容，退出程序重启后问题依旧。

### Reproduction

使用快捷键进行划词翻译时出现

### Platform

MacOS

### System Version

sonoma 正式版

### Window System (Linux Only)

None

### Software Version

2.5.1

**Comment by TechDecryptor** [comment]
重新给一下辅助功能权限

**Comment by Pylogmon** [comment]
辅助功能权限中把pot删了重新添加
