### ISSUE TITLE
[BUG]: 无法运行

### ISSUE THREAD

**Issue by Nyayurn** [pot-app/pot-desktop#514]
### Description

在hyprland和kde中均无法使用, 无论GDK_BACKEND是x11还是wayland都报错

### Reproduction

输入GDK_BACKEND=x11 pot回车(直接pot回车同样有问题)

### Platform

Linux

### System Version

Arch Linux

### Window System (Linux Only)

Wayland

### Software Version

2.5.1-1

### Log File

[error.log](https://github.com/pot-app/pot-desktop/files/12755844/error.log)

**Comment by Pylogmon** [comment]
> [!WARNING]  
> 在最新版本的 [Webkit2Gtk](https://archlinux.org/packages/extra/x86_64/webkit2gtk) (2.42.0) 中，由于 Nvidia 专有驱动未完全实现 DMABUF，将导致无法启动和崩溃的情况发生。<br>
> 请降级或在 `/etc/environment` （或者其他设置环境变量的地方）中加入 `WEBKIT_DISABLE_DMABUF_RENDERER=1` 环境变量关闭 DMABUF 的使用。

是不是因为这个

**Comment by Nyayurn** [comment]
> Warning 在最新版本的 [Webkit2Gtk](https://archlinux.org/packages/extra/x86_64/webkit2gtk) (2.42.0) 中，由于 Nvidia 专有驱动未完全实现 DMABUF，将导致无法启动和崩溃的情况发生。 请降级或在 `/etc/environment` （或者其他设置环境变量的地方）中加入 `WEBKIT_DISABLE_DMABUF_RENDERER=1` 环境变量关闭 DMABUF 的使用。
> 
> 是不是因为这个

是的
