### ISSUE TITLE
[Feature]: 分离划词翻译和输入翻译的设置选项

### ISSUE THREAD

**Issue by qoqiyu** [pot-app/pot-desktop#516]
### Description

请问可以把划词翻译和输入翻译的配置选项分离吗~例如我希望**划词翻译的时候可以隐藏原文、隐藏语言栏**，这样更简洁快速；而在**输入翻译的时候则显示原文和语言栏**。但现在这两个配置是合在一起的，平时为了使用频率更高的划词翻译我通常关闭原文和语言栏——可是有时突发需要输入翻译时又不得不进入设置重新打开（或者可以在翻译面板中集成开关原文和语言栏的按钮），谢谢！

![Snipaste_2023-09-29_17-50-56](https://github.com/pot-app/pot-desktop/assets/48037182/0fb05fe3-45b9-4b61-baaa-3006f2941cfb)

或者

![Snipaste_2023-09-29_17-52-04](https://github.com/pot-app/pot-desktop/assets/48037182/3825d9f5-adc9-4f9d-97bf-ec58a64c5cd1)

### Application Scenario

如上

**Comment by Pylogmon** [comment]
2.0版本将所有翻译窗口统一为一个，不支持分离。
