### ISSUE TITLE
[BUG]: 2.6.0版本，x64和x86均安装报错

### ISSUE THREAD

**Issue by ajmz** [pot-app/pot-desktop#517]
### Description

已经卸载包括配置文件在内的旧版本，并且重启了系统。

![2023-09-30_014239](https://github.com/pot-app/pot-desktop/assets/30185045/4558e56a-b25b-4b95-8cd5-f8c3b03f7b9f)

### Reproduction

之前的版本都可正常安装。

### Platform

Windows

### System Version

Windows 11  22631.2361

### Window System (Linux Only)

None

### Software Version

2.6.0

**Comment by Pylogmon** [comment]
我没有复现你的问题，你试试这个办法？https://answers.microsoft.com/en-us/windows/forum/all/there-is-a-problem-with-this-windows-installer/36faa78f-f670-e011-8dfc-68b599b31bf5

**Comment by Pylogmon** [comment]
请在终端运行

```powershell
msiexec /i 安装包绝对路径 /l*v msilog.txt
```
后上传得到的日志文件 `msilog.txt`

**Comment by Pylogmon** [comment]
已改回exe安装包
