### ISSUE TITLE
[BUG]: OCR无法在非主显示器上被调用

### ISSUE THREAD

**Issue by RedwindA** [pot-app/pot-desktop#519]
### Description

如题，OCR只有在主显示器上可用

### Reproduction

点击文字识别或者图像翻译，并在多个显示器之间移动光标，可以发现只有主显示器的光标变为十字

### Platform

Windows

### System Version

win10 专业版 19045.3448

### Window System (Linux Only)

None

### Software Version

2.6.0

**Comment by Pylogmon** [comment]
请通过快捷键调用，OCR是通过鼠标所在位置判断在哪块屏幕上启动的
