### ISSUE TITLE
[BUG]: macOS Sonoma 14.0 闪退

### ISSUE THREAD

**Issue by danny-su** [pot-app/pot-desktop#520]
### Description

macOS Sonoma 14.0 闪退
老版本没有问题， 2.6.0打开后直接闪退

### Reproduction

直接打开

### Platform

MacOS

### System Version

macOS Sonoma 14.0

### Window System (Linux Only)

None

### Software Version

2.6.0

**Comment by Pylogmon** [comment]
https://github.com/tauri-apps/tauri/issues/7925
已修复
