### ISSUE TITLE
[BUG]: title 从2.5.1升级到2.6.0一直卡死到100%

### ISSUE THREAD

**Issue by Anz-03** [pot-app/pot-desktop#521]
### Description

![image](https://github.com/pot-app/pot-desktop/assets/106299500/8265c380-9488-4004-ad20-b2feecae2d86)
是不是只能卸载重装？

### Reproduction

只要从软件自带的updater更新就会这样

### Platform

Windows

### System Version

Windows 10

### Window System (Linux Only)

None

### Software Version

2.5.1

**Comment by Anz-03** [comment]
右键管理员运行就行了。我关了Windows自带的管理员提示，以为这个软件默认就是管理员权限运行的。结果这个软件也不报错。

**Comment by Pylogmon** [comment]
这个已经修复了，但是升级到2.6还需要管理员权限，更新日志写了的，2.6版本之后升级就不需要管理员权限了
