### ISSUE TITLE
M2 pot 闪退

### ISSUE THREAD

**Issue by JaydonZhao** [pot-app/pot-desktop#524]
问题描述
M2 Mac上打开 pot 闪退
如何复现
1、解压缩pot_2.6.0_aarch64.app.tar.gz
2、打开pot.app

操作系统
macOS Ventura 13.5

pot:2.6.0_aarch64.app.tar.gz

补充信息
打开pot.app的瞬间，菜单栏会瞬间出现闪现一下pot的图标

**Comment by Pylogmon** [comment]
#520
