### ISSUE TITLE
Mac 使用热键OCR返回空白

### ISSUE THREAD

**Issue by liuchanghuaX1** [pot-app/pot-desktop#525]
### Description

<img width="798" alt="image" src="https://github.com/pot-app/pot-desktop/assets/40064819/7f9d46fb-d75b-4060-b86c-2e7467ae1d79">

### Reproduction

macOS 使用热键截图翻译，已经授权录屏权限了，但是还是会不断弹出录屏权限申请，无法选择其他内容，点击空白处再截图，内容就为空白。

### Platform

MacOS

### System Version

macOS 14.0

### Window System (Linux Only)

None

### Software Version

2.6.1

**Comment by Pylogmon** [comment]
你这个是不是之前版本删除paddle导致的 #504

**Comment by liuchanghuaX1** [comment]
> 你这个是不是之前版本删除paddle导致的 #504

是的。已解决问题。感谢。
