### ISSUE TITLE
[BUG]: 使用快捷键文字识别，弹出空白窗口

### ISSUE THREAD

**Issue by ZhangHaHei** [pot-app/pot-desktop#526]
### Description

2.6.0版本和2.6.1版本都是这样
使用快捷键文字识别，弹出空白窗口

### Reproduction

按快捷键，选中区域后，弹出透明空白窗口

### Platform

Windows

### System Version

版本	Windows 10 专业版 版本号	22H2 操作系统内部版本	19045.3448 体验	Windows Feature Experience Pack 1000.19044.1000.0

### Window System (Linux Only)

None

### Software Version

2.6.1 2.6.0

**Comment by Pylogmon** [comment]
#504

**Comment by ZhangHaHei** [comment]
> #504
多谢

**Comment by intbingbing** [comment]
haihaihai

**Comment by Pylogmon** [comment]
> haihaihai

请不要在issue中回复没用的信息
