### ISSUE TITLE
[BUG]: title内存占用太大了吧

### ISSUE THREAD

**Issue by baird19** [pot-app/pot-desktop#532]
### Description

![image](https://github.com/pot-app/pot-desktop/assets/128969944/b79e0619-8247-40d3-a857-7f3e2fbe2b21)

### Reproduction

![image](https://github.com/pot-app/pot-desktop/assets/128969944/07e54108-401e-4d59-8674-34f53354dc73)

### Platform

Windows

### System Version

win11

### Window System (Linux Only)

None

### Software Version

2.6.1

**Comment by Pylogmon** [comment]
#416
