### ISSUE TITLE
[BUG]: “pot.app”已损坏，无法打开。 你应该将它移到废纸篓。

### ISSUE THREAD

**Issue by NingLi670** [pot-app/pot-desktop#539]
### Description

在MacOS上安装2.6.3版本的pot出现错误：“pot.app”已损坏，无法打开。 你应该将它移到废纸篓。

### Reproduction

无论是通过 Brew 安装还是手动安装都会出现这个错误

### Platform

MacOS

### System Version

Apple M1 Pro    Ventura 13.5.2 

### Window System (Linux Only)

None

### Software Version

2.6.3

**Comment by Pylogmon** [comment]
文档都有写，麻烦看一眼，谢谢
https://pot-app.com/docs/tutorial/install#%E6%89%8B%E5%8A%A8%E5%AE%89%E8%A3%85
