### ISSUE TITLE
[Feature]: 为翻译引擎提供“默认”选项

### ISSUE THREAD

**Issue by Anivie** [pot-app/pot-desktop#540]
### Description

希望在服务设置 -> 翻译 中的引擎配置中能提供选项供我们选择哪些引擎唤起翻译窗口时自动调用，哪些需要额外点一个按键确认再发起请求

### Application Scenario

GPT，DeepL之类的api翻译些废话不值当，希望首选免费翻译引擎，效果不佳再上付费引擎

**Comment by Pylogmon** [comment]
你把开关关了用到了再切换不就好了
![image](https://github.com/pot-app/pot-desktop/assets/59004461/5fb039a7-b71d-4bee-80c5-19b18e4a9562)

**Comment by Anivie** [comment]
> ###
> [Oct 13, 2023](#issuecomment-1761013290)

可是免费的有两个诶，默认的话可以直接都看的说

**Comment by Pylogmon** [comment]
你把两个都打开不行吗？

**Comment by Anivie** [comment]
> 你把两个都打开不行吗？

可以的
可能我更习惯类似于默认的思维，既然您认为现有功能可以替代那就算了
