### ISSUE TITLE
可以给设置里的文字识别增加一个去除空格的功能吗

### ISSUE THREAD

**Issue by lhj5426** [pot-app/pot-desktop#551]
### Description

![image](https://github.com/pot-app/pot-desktop/assets/30548000/f34b19ec-4a40-4907-a708-0e2e48f02c4d)

### Application Scenario

![image](https://github.com/pot-app/pot-desktop/assets/30548000/b0eba1f2-8947-40e5-b2ed-764d9dec664f)
因为 离线OCR win 系统 自身的OCR OCR完之后 每一个字之间都会有空格
如果能够在 设置的 文字识别里增加一个 去除空格的功能 的话 就可以直接 让字正确挨在一起了

或者 直接给系统OCR 优化一下 直接识别完默认就删除空格 也可以 ？

**Comment by Pylogmon** [comment]
确实，系统OCR中文已经单独处理过了，没有考虑到日语也有这个问题。

**Comment by manfred-exz** [comment]
目前(2.6.8)如果切换到Tesseract.js，仍然会有空格的问题。
![image](https://github.com/pot-app/pot-desktop/assets/7065434/013ca185-465a-40e8-990b-f27c44f6726f)

是不是在通用OCR的函数那边处理空格比较好(`result = result.replaceAll(' ', '');`)
