### ISSUE TITLE
[BUG]: 四个插件翻译报错

### ISSUE THREAD

**Issue by cherub0507** [pot-app/pot-desktop#552]
### Description

![微信截图_20231016142513](https://github.com/pot-app/pot-desktop/assets/58015207/8831e6c8-e7f4-4820-b51b-bcbae4d0dd68)

如截图所示，Free Dictionary / ECDict / Lingva都报错，MOJi辞書直接没有任何反应

### Reproduction

如图所示

### Platform

Windows

### System Version

Win 11 Pro 22H2

### Window System (Linux Only)

None

### Software Version

2.6.4

**Comment by Pylogmon** [comment]
四个插件你装了三个词典，词典只能查词啊

**Comment by cherub0507** [comment]
> 四个插件你装了三个词典，词典只能查词啊

单独查词也同样报错啊

**Comment by Pylogmon** [comment]
lingva启用的时候需要填requestPath，你没填呀

**Comment by Pylogmon** [comment]
![image](https://github.com/pot-app/pot-desktop/assets/59004461/a295cd9a-44e9-43aa-8298-b4d7d5719286)
![image](https://github.com/pot-app/pot-desktop/assets/59004461/d85514dd-f085-4ac4-9bb5-528e50f38582)
![image](https://github.com/pot-app/pot-desktop/assets/59004461/48f90b1d-e872-453d-bf92-13a7cea6edae)
![image](https://github.com/pot-app/pot-desktop/assets/59004461/925eedbc-49ce-4eeb-a256-9fdae324ed85)

**Comment by cherub0507** [comment]
> lingva启用的时候需要填requestPath，你没填呀
> 
> 填 `lingva.pot-app.com`, 这是我搭的Lingva服务

按这个设置测试正常了，感谢指导~

而且终于弄明白居然是单词查询，多几个词就不行……

我还是用DeepL吧，反正有这个网络条件

**Comment by cherub0507** [comment]
另外，我不另外提issue了，就想问问生词本功能，扇贝的token / 有道的cookie怎么取得？

**Comment by Pylogmon** [comment]
我更新了README，去插件仓库看吧
