### ISSUE TITLE
[Feature]: 请求显示音标

### ISSUE THREAD

**Issue by Crazyokd** [pot-app/pot-desktop#557]
### Description

一般情况下我并不想点击播放按钮听单词如何发音，因为音标在大多数时候已经足够。
另外软件中发音的延迟也比较长。

### Application Scenario

查询单词后，显示音标

**Comment by Pylogmon** [comment]
支持的接口自然会显示
![image](https://github.com/pot-app/pot-desktop/assets/59004461/85471a80-2b20-43d9-9e01-9a582c749971)

**Comment by Crazyokd** [comment]
我一般用deepl+谷歌翻译，倒是没注意到。这个音标显示一般得是词典才有。

**Comment by Pylogmon** [comment]
google也支持查词的
![image](https://github.com/pot-app/pot-desktop/assets/59004461/78b3fcc1-adba-4261-8128-95c7b976b07c)

**Comment by Pylogmon** [comment]
发音延时长是因为默认的lingva是部署在vercel上的，不是很稳定，可以安装其他tts插件使用

**Comment by Crazyokd** [comment]
我一直用默认的😂
![image](https://github.com/pot-app/pot-desktop/assets/74645100/797a180f-8157-4547-a31e-c19065f4d798)

**Comment by Crazyokd** [comment]
> 发音延时长是因为默认的lingva是部署在vercel上的，不是很稳定，可以安装其他tts插件使用

明白了。
