### ISSUE TITLE
[Feature]: 提供窗口大小的设置

### ISSUE THREAD

**Issue by ColouredGlaze** [pot-app/pot-desktop#560]
### Description

当翻译内容多，翻译服务也有好几个的时候，显示不友好

### Application Scenario

希望可以提供设置软件宽高的配置

**Comment by Pylogmon** [comment]
提供了记住窗口大小的功能，开启后调整窗口大小即可

**Comment by ColouredGlaze** [comment]
> 提供了记住窗口大小的功能，开启后调整窗口大小即可

看到了，感谢~！
