### ISSUE TITLE
[BUG]: title

### ISSUE THREAD

**Issue by daidaihk** [pot-app/pot-desktop#564]
### Description

win 11 无法运行

![image](https://github.com/pot-app/pot-desktop/assets/97075996/215f7269-50fd-400f-968b-ece7329bc75f)

### Reproduction

处理器	AMD Ryzen 7 4800H with Radeon Graphics            2.90 GHz
机带 RAM	16.0 GB (15.4 GB 可用)
系统类型	64 位操作系统, 基于 x64 的处理器

版本	Windows 11 专业版
版本	22H2
操作系统版本	22621.2283
体验	Windows Feature Experience Pack 1000.22662.1000.0

### Platform

Windows

### System Version

版本	Windows 11 专业版 版本	22H2 操作系统版本	22621.2283 体验	Windows Feature Experience Pack 1000.22662.1000.0

### Window System (Linux Only)

None

### Software Version

pot_2.6.4_arm64-setup.exe

**Comment by Pylogmon** [comment]
下载错了，你下载x64版本啊
