### ISSUE TITLE
[Feature]: Add Persian translation feature

### ISSUE THREAD

**Issue by hosseinhrp** [pot-app/pot-desktop#566]
### Description

Hello, I am a user of Pot App and I really like it. However, I noticed that there is no plugin for Persian translation in the app. Persian is my native language and I would like to use Pot App to translate content to or from Persian. I think this feature would be useful for many other users who speak Persian or want to learn it. Thank you for your consideration.

### Application Scenario

.

**Comment by Pylogmon** [comment]
Okay, I'll add Persian support.

**Comment by Pylogmon** [comment]
Ok, I've added Persian support to the software, in addition to that, you can also help to translate software into Persian on [Weblate](https://hosted.weblate.org/engage/pot-app/)
