### ISSUE TITLE
[BUG]: macOS Sonoma在2.6.6版本会出现下面的情况

### ISSUE THREAD

**Issue by liziqiang** [pot-app/pot-desktop#567]
最新的 2.6.6 会出现下面的情况
<img width="571" alt="image" src="https://github.com/pot-app/pot-desktop/assets/208130/cc20f232-7b24-4ad4-9f10-1a52ab5a483a">

https://github.com/pot-app/pot-desktop/assets/208130/4115df2b-7c48-4da2-9c55-da8b22c0755a

_Originally posted by @liziqiang in https://github.com/pot-app/pot-desktop/issues/561#issuecomment-1774326563_

**Comment by Pylogmon** [comment]
没能复现

**Comment by liziqiang** [comment]
> 没能复现

我现在也不能复现了😂
