### ISSUE TITLE
[Feature]: 建议增加拼接翻译

### ISSUE THREAD

**Issue by Cold-Stars** [pot-app/pot-desktop#568]
### Description

在阅读文献时，会遇到选中的文字不在同一页，强制选中的话页眉页脚也会被选进去，能否新增一个快捷键，将选中的文字依次拼接起来再翻译

### Application Scenario

方便阅读pdf文献

**Comment by Pylogmon** [comment]
设置中打开增量翻译后，划词翻译后把窗口钉住，再次划词就可以实现。
