### ISSUE TITLE
[Feature]: 希望增加翻译失败的接口窗口能够自动折叠

### ISSUE THREAD

**Issue by After-diving** [pot-app/pot-desktop#570]
### Description

希望能对翻译结果做一个判断, 翻译失败或者返回为空的时候, 能够自动折叠这些窗口界面, 减少窗口界面的占用, 

### Application Scenario

单词翻译和句子翻译组合在一起翻译的时候, 在翻译单词的时候, 使用字典翻译能够更好的解释单词的释意, 但是在翻译句子的时候, 字典翻译就无法翻译或翻译失败, 但它的释意窗口并没有折叠, 会占用很大一部分窗口界面, 比较影响观感.

**Comment by Lawrenauh** [comment]
不知道 Pot 是模仿 Mac 上的 Bob，还是反过来，但是功能和界面真的太像了，但就体验上 Bob 还是好太多，比如 Bob 就有记住折叠的选项。但 Pot 足以替代 OpenAI-Translator。自从 Mac 上用上了 Bob，我基本就再也没用过其它翻译软件，希望 Pot 多多改进。目前只希望增加两个功能：1、翻译接口窗口记住手动折叠选项；2、字体有手动调整的选项（字体真的有点大，对比一下 OpenAI-Translator，相同的窗口面积显示的翻译量估计只有一半，对于大段翻译很影响观感），只用改翻译窗内的字体，界面字体不影响。
