### ISSUE TITLE
[Feature]: RTL languages

### ISSUE THREAD

**Issue by non7676** [pot-app/pot-desktop#574]
### Description

I would like to request that POT Desktop supports RTL languages, such as Persian, Arabic, Hebrew, etc.

### Application Scenario

I am a user of POT Desktop and I want to use it in Persian, my native language. However, when I select Persian as the target language, the text is displayed from left to right, which is incorrect and confusing. I want the text to be displayed from right to left, as it should be for RTL languages.

**Comment by Pylogmon** [comment]
Is this the effect you are talking about? I don't quite understand the specs on this, do I need to put the window's close button on the left?

![image](https://github.com/pot-app/pot-desktop/assets/59004461/c4680607-afe7-4024-bba4-e3904441bc30)

**Comment by non7676** [comment]
![image](https://github.com/pot-app/pot-desktop/assets/127596756/58919c74-db6a-4df5-aeda-f869a315eaae)
I appreciate your reply, but the text is still not displayed correctly from right to left. It is not justified and it breaks when there is an English word in the text. Please see the attached screenshot for an example of what I mean. I hope you can fix this issue soon, as it affects the usability of POT Desktop for Persian users. Thank you for your attention and effort.

**Comment by Pylogmon** [comment]
我知道他没有从右到左显示，我又不认识波斯语，我哪知道他是怎么排的？我不就在问你我图片上的显示正确吗？回答我的问题好吗？好好看看我在问什么，别跟我说那些废话，OK？
