### ISSUE TITLE
[BUG]: OCR.Space除了英文以外的識別問題

### ISSUE THREAD

**Issue by Yusei-StarDust** [pot-app/pot-desktop#575]
### Description

OCR.Space應該支援識別多國語言，不過實際上除了英文以外好像都識別不出來(error sending request for url (https://api.ocr.space/parse/image): operation timed out)，還是說還需要在哪裡進行什麼設置……？

### Reproduction

1. 新增OCR.Space的擴充套件並輸入Api Key
2. 輸入文字識別的快捷鍵跳出識別窗口
3. 文字識別服務選擇OCR.Space，語言不選擇自動檢測而是選擇簡體/繁體中文或日文，然後重新識別
4. 除了英文外都會跳出error sending request for url (https://api.ocr.space/parse/image): operation timed out

### Platform

Windows

### System Version

Windows 10 22H2 19045.3570

### Window System (Linux Only)

None

### Software Version

2.6.7([plugin].com.pot-app.ocrspace是1.2.0)

**Comment by Pylogmon** [comment]
目前的OCR Space实现默认使用Engine 2，Engine2不会处理语言选项，无论你选择什么语言都是由OCRSpace来自动检测语言的，所以在你切换语言的时候实际上发送的是一模一样的请求，出现这种报错有可能是网络问题，后续我会提供选择Engine的选项，不同的OCREngine有什么不同可以参考[OCRSpace文档](https://ocr.space/OCRAPI)中的Select the best OCR Engine部分。

**Comment by Yusei-StarDust** [comment]
原來如此，感謝您的解惑。

**Comment by Pylogmon** [comment]
https://github.com/pot-app/pot-app-recognize-plugin-template/commit/29db35c4773847d7bbd3d6e73ed027c805e5878c
