### ISSUE TITLE
[Feature]: 增加音标显示

### ISSUE THREAD

**Issue by ovulatingwife** [pot-app/pot-desktop#578]
### Description

翻译时只有发音，没有音标显示，谷歌翻译引擎有时有音标，有时没有音标
![image](https://github.com/pot-app/pot-desktop/assets/91519026/11c58091-efa8-4695-90e2-41f375023cc2)

### Application Scenario

有时候不方便打开声音但是想知道音标来确定发音

**Comment by Pylogmon** [comment]
词典类的接口基本上都是有这些的，添加几个词典接口就好了，翻译接口是不会返回这些东西的，Google的接口有时候不显示音标那就是接口没有返回相关内容嘛，这个没有办法的。
