### ISSUE TITLE
[BUG]: 安装卡巴斯基安全软件的设备无法使用

### ISSUE THREAD

**Issue by sbwfnhn** [pot-app/pot-desktop#579]
### Description

安装都安装不上，退出卡巴斯基安全软件免强安装上，只要一启动卡巴斯基安全软件，直接杀掉删除程序。
不能在杀毒软件下使用的程序，应该算是最大的bug.

### Reproduction

windows安装卡巴斯基安全软件，有免费试用期。

### Platform

Windows

### System Version

windows 10

### Window System (Linux Only)

None

### Software Version

21H2

**Comment by Pylogmon** [comment]
误报而已，加入白名单就好了。
