### ISSUE TITLE
[BUG]: 说明文档，官网都无法访问呀

### ISSUE THREAD

**Issue by iamdalaba** [pot-app/pot-desktop#580]
### Description

https://pot-app.com/docs/tutorial/api/translate/openai  打不开

### Reproduction

https://pot-app.com/docs/tutorial/api/translate/openai

### Platform

Windows

### System Version

win11

### Window System (Linux Only)

None

### Software Version

11

**Comment by Pylogmon** [comment]
官网在备案，过段时间就好了

**Comment by Pylogmon** [comment]
可以访问了
