### ISSUE TITLE
[BUG]: Bad Auto Detect

### ISSUE THREAD

**Issue by ArtexJay** [pot-app/pot-desktop#582]
### Description

Auto Detect isn't very good. It will always default to the primary language instead of actually auto detecting the language that is scanned.

![image](https://github.com/pot-app/pot-app-plugin-list/assets/32932497/353dfa99-158d-4700-a7ec-e46821f0ec95)

### Reproduction

Use text Recognition and scan the foreign language. Keep it on auto detect, click recognize.

### Platform

Windows

### System Version

Windows 11 23h2

### Window System (Linux Only)

None

### Software Version

2.6.7

**Comment by Pylogmon** [comment]
Offline OCR does not support automatic detection. All offline OCR automatic detection options fallback to a specified language.

**Comment by ArtexJay** [comment]
> Offline OCR does not support automatic detection. All offline OCR automatic detection options fallback to a specified language.

Then please provide instructions on how to use the "online" OCR so that auto-detection can work properly.
Also consider adding a note saying "Offline OCR does not support automatic detection. All offline OCR automatic detection options fallback to a specified language" and a link to show how someone can use the online OCR so that auto-detect actually works.

If not just remove the option for it.
