### ISSUE TITLE
[Feature]: open ai 润色或者总结可以放在单独的快捷键。

### ISSUE THREAD

**Issue by iamdalaba** [pot-app/pot-desktop#583]
### Description

![image](https://github.com/pot-app/pot-desktop/assets/3396454/e9acbba1-a2d7-40f8-a9d7-a4561bf4f336)

默认使用的是翻译，如果每次都润色和总结，效率很低。

### Application Scenario

对话中，总结。大部分时间翻译。

**Comment by Pylogmon** [comment]
没这个必要，说到底pot是个翻译软件。
