### ISSUE TITLE
[BUG]: Error: Language not supported

### ISSUE THREAD

**Issue by asukaminato0721** [pot-app/pot-desktop#584]
### Description

Input any text into textarea, click "Speak"

then it will say

> Error: Language not supported

![image](https://github.com/pot-app/pot-desktop/assets/30024051/dcbe18d1-0967-4fb5-b3ed-8e36b85dbfba)

### Reproduction

as above

### Platform

Linux

### System Version

Arch linux

### Window System (Linux Only)

Wayland

### Software Version

2.6.7

### Additional Information

I notice that after click "Translate" , Speak works properly.

Then I checked the code, seems that translate will trigger language identification, but Speak won't. So it will return error message.

**Comment by Pylogmon** [comment]
Yes, speak requires a specific language. I don't consider speaking directly after input. I will check if the language is detected in a later version.
