### ISSUE TITLE
[Feature]: 添加OCR功能对多屏幕的适配

### ISSUE THREAD

**Issue by mengboys** [pot-app/pot-desktop#587]
### Description

由于我日常使用是双屏的状态，但是目前的pot并不支持对主屏以外的副屏进行OCR的功能，所以会造成当我的资料放置在副屏时，无法直接进行OCR识别，必须先将资料拖动到主屏上才能进行OCR操作，会大大减少副屏操作时的效率。
看到好像可以通过外置截图软件的方式实现副屏截图的功能，但是好像是linux端的方法。

### Application Scenario

多屏工作学习的时候提升效率

**Comment by Pylogmon** [comment]
OCR是在鼠标所在的屏幕启动的，我测试没有问题呀

**Comment by mengboys** [comment]
抱歉，我今天进行测试之后好像又可以了，有可能是我Snipaste用习惯了，所以下意识地在主屏幕摁下快捷键然后挪到副屏。
