### ISSUE TITLE
[BUG]: Arch linux 运行一段时间后卡顿.

### ISSUE THREAD

**Issue by ThisGoLive** [pot-app/pot-desktop#588]
### Description

我很确信是这个软件导致的.昨天之前没有,重启后不启动该应用就不出现问题.
昨天安装的时候,打开软件是没问题.但是今天使用就出现了.
1. 打开很慢,但是 一切正常
2. 一段时间后, alt+空格不能使用
3. 再过一段时间,mate键,以及一些其他的快捷键不能使用
4. 然后点击菜单 搜索安装的应用 只能显示 系统原生的脚本什么的
5. 右下脚的小图标,鼠标右键点击反应要等很久
整个过程浏览器是正常流畅使用的

### Reproduction

pot配置:  
1. 划词alt + T 截图OCR alt + R 截图翻译 alt + Q
2. 固定位置
3. 总是在最前
4. 失去焦点,不关闭
安装了 系统 OCR, 以及语音的 gst-libav
应用插件,没有下载其他的,都是默认的

### Platform

Linux

### System Version

Arch Linux x86_64 DE: Plasma 5.27.9, 每天更新

### Window System (Linux Only)

X11

### Software Version

archlinuxcn 源的 pot-translation-2.6.7-1-x86_64

**Comment by Pylogmon** [comment]
我也用arch，没有发现这个问题

**Comment by ThisGoLive** [comment]
@Pylogmon 
感觉应该是系统依赖的包,和该应用冲突导致的,总不能把系统的全部依赖发出了吧, 太多了.🤔

**Comment by ThisGoLive** [comment]
好像更新了几个版本系统后没这个问题了😋
