### ISSUE TITLE
[Feature]: 添加OCR及截图翻译

### ISSUE THREAD

**Issue by o000u** [pot-app/pot-desktop#59]
### 需求描述

之前很早就看到作者有添加OCR的动作，想问下老大，什么时候能上呢？
一直在期待，就差这个功能就圆满了，哈哈哈~~~

### 应用场景

截图翻译

**Comment by Pylogmon** [comment]
确实我很早就想加了，但是遇到一些问题，加上我最近也比较忙，所以暂时就先拖着了，目前仅仅修一些影响体验的bug，以及加一些简单的小功能，OCR等我忙完之后再着手实现，可能得拖到暑假也说不定，也可能更久，所以短期内不要抱有期待。🤣

**Comment by o000u** [comment]
> 确实我很早就想加了，但是遇到一些问题，加上我最近也比较忙，所以暂时就先拖着了，目前仅仅修一些影响体验的bug，以及加一些简单的小功能，OCR等我忙完之后再着手实现，可能得拖到暑假也说不定，也可能更久，所以短期内不要抱有期待。🤣

好吧T_T，，，继续满怀希望期待~~~加油！！

**Comment by LYZ10** [comment]
这个项目真的好棒！！！能让windows用户也有机会体验Bob的翻译功能，谢谢开发者大大。

**Comment by Pylogmon** [comment]
> 这个项目真的好棒！！！能让windows用户也有机会体验Bob的翻译功能，谢谢开发者大大。

谢谢🤭好用记得点个star哦

**Comment by LYZ10** [comment]
嘻嘻，必须安排呀（还要拿着个大喇叭到处喊）

**Comment by iRubbish** [comment]
本还想提个需求，发现大大已经在安排了

**Comment by justincnn** [comment]
> 本还想提个需求，发现大大已经在安排了

v2ex过来的，同期待ocr上线，其他感觉都很满足了

**Comment by shaojs321** [comment]
可以接入百度的免费ocr识别，个人账户有额度，这样只要接入百度就可以了，开发速度更快一点
