### ISSUE TITLE
[BUG]: 窗口失去焦点时自动关闭失效

### ISSUE THREAD

**Issue by awarewen** [pot-app/pot-desktop#596]
### Description

在设置了窗口失去焦点自动关闭之后，在鼠标离开Pot 弹出的翻译窗口失去焦点后，pot 的翻译窗口并不会自动关闭

### Reproduction

```
  bind = $ALT_MOD, C, exec, grim -g "$(slurp -d)" ~/.cache/com.pot-app.desktop/pot_screenshot_cut.png && curl "127.0.0.1:60828/ocr_translate?screenshot=false"

```
1. 按下快捷键之后，鼠标聚焦在 Pot 弹出的窗口
2. 鼠标离开正在聚焦的 Pot 窗口，Pot 窗口并不能按预期自动关闭
3. 使用 Esc 按键可以正常在聚焦 Pot 窗口的状态下正常关闭窗口

https://github.com/pot-app/pot-desktop/assets/53365857/7eb937b9-b309-49a5-a097-56770a52dcec

### Platform

Linux

### System Version

Arch Linux : 6.1.63-1-lts

### Window System (Linux Only)

Wayland (Hyprland:v0.32.3-41-g6d26199e)

### Software Version

2.7.0.r4.gd29d698-1

### Log File

[pot.log](https://github.com/pot-app/pot-desktop/files/13429822/pot.log)

### Additional Information

none

**Comment by Pylogmon** [comment]
看起来是在失去焦点的同时触发了Move事件，目前为了解决Windows和Gnome下窗口无法拖动的问题，在失去焦点后若触发Focus和Move事件后会取消关闭窗口，这个问题我觉得只能是给Hyprland提供一个patch版本的pot，你可以在aur单独维护一个`pot-translation-hyprland`包来解决，

具体的patch内容，注释`src/window/Translate/index.jsx`中57-63行代码即可：

```javascript
void listen('tauri://move', () => {
    info('Move');
    if (blurTimeout) {
        info('Cancel Close');
        clearTimeout(blurTimeout);
    }
});
```

**Comment by Pylogmon** [comment]
我已经添加了patch文件，你只需要在编译前执行`git am patch/hyprland.patch`即可应用patch

**Comment by ziwen1002** [comment]
kde也会有这样的问题，失去焦点时，窗口是应用切换动画被移动到后方，而不是关闭。应该也是这个原因导致。

**Comment by awarewen** [comment]
好的，刚看到，谢谢 ）

**Comment by Pylogmon** [comment]
> kde也会有这样的问题，失去焦点时，窗口是应用切换动画被移动到后方，而不是关闭。应该也是这个原因导致。

我在看看，如果kde也会有问题的话那就应该改变默认行为，给gnome打patch而不是给Hyprland打patch了。

**Comment by Pylogmon** [comment]
@ziwen1002 可以像上面那样录个视频吗，我在kde下没有复现这个问题。

**Comment by ziwen1002** [comment]
> @ziwen1002 可以像上面那样录个视频吗，我在kde下没有复现这个问题。

不好意思，近期没关注邮件所以没及时看到。

发现没有动画，单单失去焦点也不会自动关闭。

软件版本是2.7.0，我没打补丁，安装包为：https://aur.archlinux.org/packages/pot-translation-bin

系统信息：

```bash
OS: Manjaro Linux x86_64
Host: Z97X-UD3H
Kernel: 6.1.62-1-MANJARO
Uptime: 3 hours, 45 mins
Packages: 1682 (pacman), 34 (flatpak)
Shell: bash 5.2.15
Resolution: 1920x1080
DE: Plasma 5.27.9
WM: kwin
Theme: [Plasma], WhiteSur-Light [GTK2/3]
Icons: [Plasma], WhiteSur [GTK2/3]
Terminal: konsole
Terminal Font: JetBrains Mono 16
CPU: Intel i7-4790K (8) @ 4.400GHz
GPU: AMD ATI Radeon RX 580 2048SP
GPU: Intel HD Graphics
Memory: 7564MiB / 31951MiB
```

录像是11:58:07开始，之后的日志文件我也上传了。

https://github.com/pot-app/pot-desktop/assets/6780015/0b476ffa-d28d-4297-a6a6-9e6f1efe70d8

[pot.log](https://github.com/pot-app/pot-desktop/files/13483365/pot.log)

**Comment by Pylogmon** [comment]
看日志跟上面的问题一样，这么看来应该是Wayland的问题，用那个补丁可以解决。

**Comment by ziwen1002** [comment]
> 看日志跟上面的问题一样，这么看来应该是Wayland的问题，用那个补丁可以解决。

嗯嗯，好的，感谢！

**Comment by 1Jack2** [comment]
> 看起来是在失去焦点的同时触发了Move事件，目前为了解决Windows和Gnome下窗口无法拖动的问题，在失去焦点后若触发Focus和Move事件后会取消关闭窗口，这个问题我觉得只能是给Hyprland提供一个patch版本的pot

根据评论区的反馈，Wayland + Hyprland/KDE 都有该问题，是否可以在程序运行时检测桌面环境，然后决定是否触发下面代码？

```ts
void listen('tauri://move', () => {
    info('Move');
    if (blurTimeout) {
        info('Cancel Close');
        clearTimeout(blurTimeout);
    }
});
```
