### ISSUE TITLE
[Feature]:能够设置 Windows 获取划线文本的使用的快捷键，因为使用 power toy 映射了 win 和 ctrl 之后，复制快捷键改变了

### ISSUE THREAD

**Issue by skywalker512** [pot-app/pot-desktop#597]
### Description

希望能够设置 Windows 获取划线文本的使用的快捷键，因为使用 power toy 映射了 win 和 ctrl 之后，复制快捷键改变了。

### Application Scenario

因为我同时使用 Windows 和 macOS，希望统一快捷键，所以使用 power toy 映射了 win 和 ctrl。

这个时候，复制的快捷键变为了 win + c （被 power toy 映射为 CTRL + c）

但是我看到，https://github.com/pot-app/Selection/blob/1.1.0/src/windows.rs#L123 这里写的是 `{+CTRL}c{-CTRL} `

这样触发 CTRL + C（被 power toy 映射为 win + c）无法更新剪切板，这样就达不到翻译划线词的效果。

目前我是自己编译的 pot 更新比较麻烦，希望能够进行设置。

**Comment by Pylogmon** [comment]
确实没有考虑到这么深度定制的使用方式，有时间加个选项。

**Comment by skywalker512** [comment]
感谢你的回复，我使用 kanata 来做键盘映射解决了这个问题，如果你觉得有必要再添加吧。我暂时没有需求了。
