### ISSUE TITLE
[BUG]: windows下使用小狼毫输入法再输入框输入时会卡住

### ISSUE THREAD

**Issue by xuestrange** [pot-app/pot-desktop#60]
### 问题描述

如图所示， 使用小狼毫输入法在Windows下会出现这种情况，摁下第一个字母后就卡住了。

![image](https://user-images.githubusercontent.com/59390321/236628752-b243d614-6a2f-423a-bfa6-182a723b561b.png)

### 如何复现

使用小狼毫输入法在输入框中输入中文就会出现，但是输入英文就不会。

### 操作系统

Windows (Default)

### 操作系统版本

Windows 10

### 窗口系统(Linux Only)

None

### 软件版本

0.2.4

### 补充信息

关闭动态翻译也会出现这种情况。

**Comment by Pylogmon** [comment]
已复现，但是我不明白问题出在哪，目前的解决方法只有使用微软拼音了。

**Comment by Pylogmon** [comment]
经过测试，只要窗口置顶之后再输入就会出问题，我不知道是Tauri的问题还是小狼毫的问题

**Comment by xuestrange** [comment]
> 经过测试，只要窗口置顶之后再输入就会出问题，我不知道是Tauri的问题还是小狼毫的问题

😢

**Comment by xuestrange** [comment]
> 经过测试，只要窗口置顶之后再输入就会出问题，我不知道是Tauri的问题还是小狼毫的问题

那能不能设置一个选项，取消自动窗口指定

**Comment by Pylogmon** [comment]
我用PowerToy置顶了其他窗口，都沒有問題，應該是Tauri的窗口問題。

**Comment by Pylogmon** [comment]
> 那能不能设置一个选项，取消自动窗口指定

已添加

**Comment by xuestrange** [comment]
> 可以考虑下载安装小狼毫的 nightly 版本：https://github.com/rime/weasel/actions/runs/5077099967 下载 [artifact](https://github.com/rime/weasel/suites/13137621189/artifacts/714094640) 即可
> 
> 个人测试在最新版的 Pot 中是正常使用的
> 
> ![image](https://user-images.githubusercontent.com/19755727/240904082-3b696f91-f8c8-4c16-be66-7175b9a8a2d5.png)

确实是可行的，感谢

**Comment by Pylogmon** [comment]
那这是小狼毫修了还是tauri修了，我当时测了只有tauri的窗口会有这问题。

**Comment by uqiu** [comment]
@xuestrange 
可否发一下你当时安装的版本以及commit号码？
现在最新的每夜版还是有这个BUG

**Comment by xuestrange** [comment]
@uqiu 只记得是0.2.4，commit号码记不得了
不过，我记得是小狼毫0.15.0版本修复这个bug？

**Comment by uqiu** [comment]
@xuestrange 
感谢回复,我已经编译了一个能用的版本
https://github.com/pot-app/pot-desktop/issues/870#issuecomment-2487464966
