### ISSUE TITLE
[BUG]: Pot貌似无法正常读取使用Sioyek软件打开的PDF文件的文字

### ISSUE THREAD

**Issue by Mickychen00** [pot-app/pot-desktop#603]
### Description

我目前正使用[Sioyek软件](https://github.com/ahrm/sioyek)进行PDF文件的阅读，我发现可以正常复制这个阅读器的PDF文字，但是每当选中拟翻译的文字，使用快捷键呼出Pot时，Pot翻译界面的文字内容是空白的。请问这是为什么呢？

### Reproduction

![image](https://github.com/pot-app/pot-desktop/assets/28621570/2a4bd7c5-9b07-4365-92c1-c905845196a0)

### Platform

Windows

### System Version

Windows 10

### Window System (Linux Only)

None

### Software Version

2.7.0

**Comment by Pylogmon** [comment]
我这边测试没问题
![image](https://github.com/pot-app/pot-desktop/assets/59004461/6e45d9fa-b0a3-4923-82c9-642493c348ce)

**Comment by Mickychen00** [comment]
谢谢帮忙测试，但是我的确Sioyek的内容还是无法被翻译。比如我在Edge上的网页所选文字被成功捕获并翻译后，切换到Sioyek，呼出Pot快捷窗口，它捕获的还是之前的网页所选文字。

**Comment by Mickychen00** [comment]
果然，换了快捷键就可以了，我此前用的是alt+T，我使用openark软件并没有发现有冲突呀。
