### ISSUE TITLE
[Feature]:  Anki卡片的Back页面增加音标和发音朗读

### ISSUE THREAD

**Issue by lihz1990** [pot-app/pot-desktop#604]
### Description

你好。我正在pot的anki插件中实现将单词的发音和音标添加到anki卡片的背后，以提供更丰富有用的单词信息。效果如下

![image](https://github.com/pot-app/pot-desktop/assets/5841740/64e30269-115a-491a-b432-fcbc16c8f530)

**进展**

在我的开发环境中已经实现了音标的显示。

**问题和求助**

在添加音频的过程中遇到了些问题，插件中获取的音频不是.mp3或者其他文件格式，而是数字组成的数组，即 pronunciations.voice 这个字段。而anki接口接受的audio格式为`data`、`path`或`url`。 参考：https://github.com/FooSoft/anki-connect#addnote

我对JavaScript和音频文件处理都不是很熟悉，经过一番搜索也没找到很清晰简明的答案，请你帮忙指点下有没有什么办法能将数字数组格式转换成更通用的音频格式。或者在数据中保留原始的音频文件URL？烦请不吝赐教

### Application Scenario

记录单词的英标和发音有助于更好的记住单词，掌握更地道的英语发音。

**Comment by lihz1990** [comment]
感谢提点，按照这个思路写的测试代码如下，可以生成音频文件并播放。

```javascript
fs = require("fs");

fs.readFile("payload.json", 'utf8', ( err, data )=> {
    let jsonData = JSON.parse(data);
    for (let pronunciation of jsonData.pronunciations)
    {
        let voice = String.fromCharCode(...pronunciation.voice);  // 数字数组转Char字符串
        fs.writeFile(`${pronunciation.region}.mp3`, voice, encoding='ascii',  (err)=>{
            if(err) {
                console.log(err)
            }
        })
    }
})

```
写入文件时必须指定`encoding='ascii'`，如果是utf8则文件无法播放。

在项目中直接向anki接口上传voice字符串，anki侧会产生异常
> string argument should contain only ASCII characters

经抓包看到上传的数据都是被编码为Unicode的，因此导致上传数据异常的问题。继续调研了uint8Array等数据类型，暂时还没有解决语音数据上传的问题。

**Comment by lihz1990** [comment]
问题解决了，把voice进行base64编码之后上传可以解决这个问题。

稍等我完善代码之后提交PR。

**Comment by BreakALegCml** [comment]
> 问题解决了，把voice进行base64编码之后上传可以解决这个问题。
> 
> 稍等我完善代码之后提交PR。

请问目前版本已经可以向anki当中写入发音了么？
但是我的好像还没有发音  是我哪里设置不对么

**Comment by lihz1990** [comment]
> > 问题解决了，把voice进行base64编码之后上传可以解决这个问题。
> > 稍等我完善代码之后提交PR。
> 
> 请问目前版本已经可以向anki当中写入发音了么？ 但是我的好像还没有发音 是我哪里设置不对么

你用的词典带单词发音吗？我用剑桥词典是支持的，如下图。但是谷歌翻译就没有发音
![image](https://github.com/user-attachments/assets/79664302-8d64-4d91-85ea-1a1adcc3a99c)

**Comment by BreakALegCml** [comment]
> > > 问题解决了，把voice进行base64编码之后上传可以解决这个问题。
> > > 稍等我完善代码之后提交PR。
> > 
> > 
> > 请问目前版本已经可以向anki当中写入发音了么？ 但是我的好像还没有发音 是我哪里设置不对么
> 
> 你用的词典带单词发音吗？我用剑桥词典是支持的，如下图。但是谷歌翻译就没有发音 ![image](https://private-user-images.githubusercontent.com/5841740/366704634-79664302-8d64-4d91-85ea-1a1adcc3a99c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMTUwMTksIm5iZiI6MTcyNjExNDcxOSwicGF0aCI6Ii81ODQxNzQwLzM2NjcwNDYzNC03OTY2NDMwMi04ZDY0LTRkOTEtODVlYS0xYTFhZGNjM2E5OWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMDQxODM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTQ5YjVmYzg3ZjJmYjhmZTAxNmM2ZjljNjFmNDViZjBkN2YzNmNjYzJiMDdjNjdkNDU1NDgyOTgzZjkyNzYyZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.J0F2j8ENrIeqkFUucFiAeJUA4CuxGFUdz9DBKmJ-wOs)

确实，我用的google  。现在换成剑桥就有了  感谢！
