### ISSUE TITLE
[BUG]: WebDav备份失败

### ISSUE THREAD

**Issue by WilsonVincent** [pot-app/pot-desktop#618]
### Description

从2.7.1升级至2.7.2后WebDav备份失效

### Reproduction

WebDav地址：
```
https://vincent.com/dav/Vincent
```
vincent.com映射的本地服务器中的ip，自签证书。
2.7.1可以正常备份，2.7.2无法正常备份。配置无任何修改。

### Platform

Windows

### System Version

Windows11 26016

### Window System (Linux Only)

None

### Software Version

2.7.2

### Additional Information

![image](https://github.com/pot-app/pot-desktop/assets/60778141/d027d4c0-8156-4e5d-be69-bedcc08ea6e4)

**Comment by MystiPanda** [comment]
文件太大了，并不是更新引起的

**Comment by deepinsc2020** [comment]
这边测试正常
