### ISSUE TITLE
[BUG]: mac build后闪退

### ISSUE THREAD

**Issue by learnAI-CN** [pot-app/pot-desktop#619]
### Description

mac版本dev正常，build正常，但是安装软件后点击软件打不开，是闪退状态.

### Reproduction

build提示没有私钥，不知道是不是这个问题的影响

### Platform

MacOS

### System Version

macos10

### Window System (Linux Only)

None

### Software Version

2.7.1

**Comment by Pylogmon** [comment]
系统版本太低了，tauri只支持到10.15
