### ISSUE TITLE
[BUG]: wayland下无法启动

### ISSUE THREAD

**Issue by TwelveNight** [pot-app/pot-desktop#623]
### Description

archlinux+wayland+hyprland下无法启动，已经设置过环境变量 [514](https://github.com/pot-app/pot-desktop/issues/514)

### Reproduction

终端下运行`pot`

### Platform

Linux

### System Version

Arch Linux x86_64 

### Window System (Linux Only)

Wayland

### Software Version

2.7.2-1

### Log File

[pot.log](https://github.com/pot-app/pot-desktop/files/13715213/pot.log)

**Comment by TwelveNight** [comment]
> 是不是环境变量没有生效

![image](https://github.com/pot-app/pot-desktop/assets/113519679/0fff85c2-025f-4c8e-814c-b6165c4279be)
生效了，应该和桌面环境没关系，我试了下xorg的kde也启动不了

**Comment by Pylogmon** [comment]
有没有尝试过直接
```bash
WEBKIT_DISABLE_DMABUF_RENDERER=1 pot
```
这样启动

**Comment by Pylogmon** [comment]
那就还是你的环境变量没有生效。写在 `.bashrc` 里边是不管用的哦。`/etc/environment` 也需要注销生效。

**Comment by TwelveNight** [comment]
Wayland下还是不行
尝试了把环境变量加到/etc/environment里，.zshrc里，直接设置在hypland.conf里加了 `env = WEBKIT_DISABLE_DMABUF_RENDERER,1`

**Comment by Nyayurn** [comment]
> > Wayland下还是不行 尝试了把环境变量加到/etc/environment里，.zshrc里，直接设置在hypland.conf里加了 `env = WEBKIT_DISABLE_DMABUF_RENDERER,1` 直接运行`WEBKIT_DISABLE_DMABUF_RENDERER=1 pot`也不行
> 
> 报错
> 
> ```shell
> ❯ WEBKIT_DISABLE_DMABUF_RENDERER=1 pot
> 
> (pot:8598): Gtk-WARNING **: 21:46:52.577: Theme parsing error: gtk-dark.css:6691:68: Invalid name of pseudo-class
> [2023-12-19][13:46:52][TRACE][zbus::connection] Sending message: Msg { type: MethodCall, sender: UniqueName(Str(Borrowed(":1.126"))), path: ObjectPath("/org/freedesktop/DBus"), iface: InterfaceName(Str(Borrowed("org.freedesktop.DBus"))), member: MemberName(Str(Borrowed("RemoveMatch"))), body: Signature("s") }
> [2023-12-19][13:46:52][TRACE][zbus::connection] Sent message with serial: 5
> [2023-12-19][13:46:52][TRACE][tracing::span::active] <- {};
> [2023-12-19][13:46:52][TRACE][tracing::span::active] -> {};
> [2023-12-19][13:46:52][TRACE][tracing::span::active] <- {};
> [2023-12-19][13:46:52][TRACE][async_io::driver] block_on: sleep until notification
> [2023-12-19][13:46:52][TRACE][polling::epoll] new events: epoll_fd=17, res=1
> [2023-12-19][13:46:52][TRACE][polling::epoll] modify: epoll_fd=17, fd=18, ev=Event { key: 18446744073709551615, readable: true, writable: false }
> [2023-12-19][13:46:52][TRACE][async_io::reactor] react: 1 ready wakers
> [2023-12-19][13:46:52][TRACE][async_io::driver] main_loop: sleeping for 50 us
> [2023-12-19][13:46:52][TRACE][zbus::socket_reader] Message received on the socket: Msg { type: MethodReturn, sender: UniqueName(Str(Borrowed("org.freedesktop.DBus"))), reply-serial: 5 }
> [2023-12-19][13:46:52][TRACE][zbus::socket_reader] Error broadcasting message to stream for `None`: SendError(..)
> [2023-12-19][13:46:52][TRACE][zbus::socket_reader] Broadcasted to all streams: Ok(Msg { type: MethodReturn, sender: UniqueName(Str(Borrowed("org.freedesktop.DBus"))), reply-serial: 5 })
> [2023-12-19][13:46:52][TRACE][zbus::socket_reader] Waiting for message on the socket..
> [2023-12-19][13:46:52][TRACE][polling::epoll] modify: epoll_fd=17, fd=16, ev=Event { key: 0, readable: true, writable: false }
> [2023-12-19][13:46:52][TRACE][tracing::span::active] -> {};
> [2023-12-19][13:46:52][TRACE][async_io::driver] main_loop: waiting on I/O
> [2023-12-19][13:46:52][TRACE][async_io::reactor] process_timers: 0 ready wakers
> [2023-12-19][13:46:52][TRACE][tracing::span::active] <- {};
> [2023-12-19][13:46:52][TRACE][polling] Poller::wait(_, None)
> [2023-12-19][13:46:52][TRACE][tracing::span::active] -> {};
> [2023-12-19][13:46:52][TRACE][polling::epoll] wait: epoll_fd=17, timeout=None
> [2023-12-19][13:46:52][TRACE][tracing::span::active] <- {};
> [2023-12-19][13:46:52][TRACE][tracing::span] -- {};
> [2023-12-19][13:46:52][TRACE][polling::epoll] modify: epoll_fd=17, fd=19, ev=Event { key: 18446744073709551615, readable: true, writable: false }
> [2023-12-19][13:46:52][TRACE][tracing::span::active] -> {};
> [2023-12-19][13:46:52][TRACE][zbus::connection] Sending message: Msg { type: MethodCall, sender: UniqueName(Str(Borrowed(":1.126"))), path: ObjectPath("/org/freedesktop/DBus"), iface: InterfaceName(Str(Borrowed("org.freedesktop.DBus"))), member: MemberName(Str(Borrowed("RemoveMatch"))), body: Signature("s") }
> [2023-12-19][13:46:52][TRACE][zbus::connection] Sent message with serial: 6
> [2023-12-19][13:46:52][TRACE][tracing::span::active] <- {};
> [2023-12-19][13:46:52][TRACE][async_io::driver] block_on: sleep until notification
> [2023-12-19][13:46:52][TRACE][polling::epoll] new events: epoll_fd=17, res=1
> [2023-12-19][13:46:52][TRACE][polling::epoll] modify: epoll_fd=17, fd=18, ev=Event { key: 18446744073709551615, readable: true, writable: false }
> [2023-12-19][13:46:52][TRACE][async_io::reactor] react: 1 ready wakers
> [2023-12-19][13:46:52][TRACE][async_io::driver] main_loop: sleeping for 50 us
> [2023-12-19][13:46:52][TRACE][zbus::socket_reader] Message received on the socket: Msg { type: MethodReturn, sender: UniqueName(Str(Borrowed("org.freedesktop.DBus"))), reply-serial: 6 }
> [2023-12-19][13:46:52][TRACE][zbus::socket_reader] Error broadcasting message to stream for `None`: SendError(..)
> [2023-12-19][13:46:52][TRACE][zbus::socket_reader] Broadcasted to all streams: Ok(Msg { type: MethodReturn, sender: UniqueName(Str(Borrowed("org.freedesktop.DBus"))), reply-serial: 6 })
> [2023-12-19][13:46:52][TRACE][zbus::socket_reader] Waiting for message on the socket..
> [2023-12-19][13:46:52][TRACE][async_io::driver] main_loop: waiting on I/O
> [2023-12-19][13:46:52][TRACE][polling::epoll] modify: epoll_fd=17, fd=16, ev=Event { key: 0, readable: true, writable: false }
> [2023-12-19][13:46:52][TRACE][async_io::reactor] process_timers: 0 ready wakers
> [2023-12-19][13:46:52][TRACE][tracing::span::active] -> {};
> [2023-12-19][13:46:52][TRACE][polling] Poller::wait(_, None)
> [2023-12-19][13:46:52][TRACE][polling::epoll] wait: epoll_fd=17, timeout=None
> [2023-12-19][13:46:52][TRACE][polling::epoll] modify: epoll_fd=17, fd=19, ev=Event { key: 18446744073709551615, readable: true, writable: false }
> [2023-12-19][13:46:52][TRACE][tracing::span::active] <- {};
> [2023-12-19][13:46:52][TRACE][tracing::span::active] -> {};
> [2023-12-19][13:46:52][TRACE][tracing::span::active] <- {};
> [2023-12-19][13:46:52][TRACE][tracing::span] -- {};
> [2023-12-19][13:46:52][TRACE][async_io::driver] block_on: sleep until notification
> zsh: segmentation fault (core dumped)  WEBKIT_DISABLE_DMABUF_RENDERER=1 pot
> ```

俺也一样

**Comment by a1401358759** [comment]
+1

**Comment by greyishsong** [comment]
Arch Linux + KDE 在 Wayland 下也出现了同样的问题。启动命令：

```
env WEBKIT_DISABLE_DMABUF_RENDERER=1 GDK_BACKEND=x11 pot
```

最终 libEGL 出现了错误：

```
libEGL warning: egl: failed to create dri2 screen
段错误（核心已转储）
```

完整日志信息见 [Log of pot-desktop before crashing](https://gist.github.com/greyishsong/508c1605bea702571046b13bb93749f5)

**Comment by mawwalker** [comment]
> 有没有尝试过直接
> 
> ```shell
> WEBKIT_DISABLE_DMABUF_RENDERER=1 pot
> ```
> 
> 这样启动，我在KDE下使用没有问题。

我试过，这样在xorg的kde里没问题，在hyprland不行，问题与大家报的一样

**Comment by colorsakura** [comment]
sway 禁用 xwayland 后, 无法打开界面窗口.
```wrap
#0  0x00007c85292e88d4 in XDefaultScreen () at /usr/lib/libX11.so.6
#1  0x00006260c177ef53 in mouse_position::mouse_position::Mouse::get_mouse_position () at src/impl_linux.rs:15
#2  0x00006260c0c52b7a in pot::window::build_window (label=..., title=...) at src/window.rs:60
#3  0x00006260c0c534d0 in pot::window::config_window () at src/window.rs:112
#4  0x00006260c0c3afe6 in pot::tray::on_config_click () at src/tray.rs:183
#5  0x00006260c0c3a524 in pot::tray::tray_event_handler (app=0x7ffca3500050, event=...) at src/tray.rs:111
#6  0x00006260c0b56adb in core::ops::function::Fn::call<fn(&tauri::app::AppHandle<tauri_runtime_wry::Wry<tauri::EventLoopMessage>>, tauri::app::tray::SystemTrayEvent), (&tauri::app::AppHandle<tauri_runtime_wry::Wry<tauri::EventLoopMessage>>, tauri::app::tray::SystemTrayEvent)> ()
    at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:79
#7  0x00006260c077d6d3 in alloc::boxed::{impl#49}::call<(&tauri::app::AppHandle<tauri_runtime_wry::Wry<tauri::EventLoopMessage>>, tauri::app::tray::SystemTrayEvent), (dyn core::ops::function::Fn<(&tauri::app::AppHandle<tauri_runtime_wry::Wry<tauri::EventLoopMessage>>, tauri::app::tray::SystemTrayEvent), Output=()> + core::marker::Send + core::marker::Sync), alloc::alloc::Global> (self=0x6260c4f9e0a8, args=...)
    at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2021
#8  0x00006260c075b3be in tauri::app::{impl#20}::build::{closure#0}<tauri_runtime_wry::Wry<tauri::EventLoopMessage>, tauri_utils::assets::EmbeddedAssets>
    (tray_id=45071, event=0x7ffca3500ce8) at /home/iFlygo/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-1.5.2/src/app.rs:1692
#9  0x00006260c077d4c1 in alloc::boxed::{impl#49}::call<(u16, &tauri_runtime::SystemTrayEvent), (dyn core::ops::function::Fn<(u16, &tauri_runtime::SystemTrayEvent), Output=()> + core::marker::Send), alloc::alloc::Global> (self=0x6260c4fe0b70, args=...)
    at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2021
#10 0x00006260c095d14d in tauri_runtime_wry::handle_event_loop<tauri::EventLoopMessage>
    (event=..., event_loop=0x7ffca3502f20, control_flow=0x7ffca3501e30, context=..., web_context=0x7ffca35033d0)
    at /home/iFlygo/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-runtime-wry-0.14.1/src/lib.rs:2866
#11 0x00006260c0960b80 in tauri_runtime_wry::{impl#48}::run::{closure#0}<tauri::EventLoopMessage, tauri::app::{impl#18}::run::{closure_env#0}<tauri_runtime_wry::Wry<tauri::EventLoopMessage>, pot::main::{closure_env#2}>> (event=..., event_loop=0x7ffca3502f20, control_flow=0x7ffca3501e30)
    at /home/iFlygo/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-runtime-wry-0.14.1/src/lib.rs:2282
#12 0x00006260c0a66088 in tao::platform_impl::platform::event_loop::{impl#1}::run_return::{closure#0}<tauri_runtime_wry::Message<tauri::EventLoopMessage>, tauri_runtime_wry::{impl#48}::run::{closure_env#0}<tauri::EventLoopMessage, tauri::app::{impl#18}::run::{closure_env#0}<tauri_runtime_wry::Wry<tauri::EventLoopMessage>, pot::main::{closure_env#2}>>> ()
    at /home/iFlygo/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.16.5/src/platform_impl/linux/event_loop.rs:1034
#13 0x00006260c0a9f191 in glib::auto::main_context::MainContext::with_thread_default<i32, tao::platform_impl::platform::event_loop::{impl#1}::run_return::{closure_env#0}<tauri_runtime_wry::Message<tauri::EventLoopMessage>, tauri_runtime_wry::{impl#48}::run::{closure_env#0}<tauri::EventLoopMessage, tauri::app::{impl#18}::run::{closure_env#0}<tauri_runtime_wry::Wry<tauri::EventLoopMessage>, pot::main::{closure_env#2}>>>> (self=0x7ffca3502e58, func=...)
    at /home/iFlygo/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.15.12/src/main_context.rs:156
#14 0x00006260c0a6531e in tao::platform_impl::platform::event_loop::EventLoop<tauri_runtime_wry::Message<tauri::EventLoopMessage>>::run_return<tauri_runtime_wry::Message<tauri::EventLoopMessage>, tauri_runtime_wry::{impl#48}::run::{closure_env#0}<tauri::EventLoopMessage, tauri::app::{impl#18}::run::{closure_env#0}<tauri_runtime_wry::Wry<tauri::EventLoopMessage>, pot::main::{closure_env#2}>>> (self=0x7ffca3502f20, callback=...)
    at /home/iFlygo/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.16.5/src/platform_impl/linux/event_loop.rs:958
#15 0x00006260c0a666dd in tao::platform_impl::platform::event_loop::EventLoop<tauri_runtime_wry::Message<tauri::EventLoopMessage>>::run<tauri_runtime_wry::Message<tauri::EventLoopMessage>, tauri_runtime_wry::{impl#48}::run::{closure_env#0}<tauri::EventLoopMessage, tauri::app::{impl#18}::run::{closure_env#0}<tauri_runtime_wry::Wry<tauri::EventLoopMessage>, pot::main::{closure_env#2}>>> (self=<error reading variable: Cannot access memory at address 0x0>, callback=...)
    at /home/iFlygo/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.16.5/src/platform_impl/linux/event_loop.rs:912
#16 0x00006260c0bf7aa9 in tao::event_loop::EventLoop<tauri_runtime_wry::Message<tauri::EventLoopMessage>>::run<tauri_runtime_wry::Message<tauri::EventLoopMessage>, tauri_runtime_wry::{impl#48}::run::{closure_env#0}<tauri::EventLoopMessage, tauri::app::{impl#18}::run::{closure_env#0}<tauri_runtime_wry::Wry<tauri::EventLoopMessage>, pot::main::{closure_env#2}>>> (self=..., event_handler=...)
    at /home/iFlygo/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.16.5/src/event_loop.rs:179
--Type <RET> for more, q to quit, c to continue without paging--
#17 0x00006260c0960522 in tauri_runtime_wry::{impl#48}::run<tauri::EventLoopMessage, tauri::app::{impl#18}::run::{closure_env#0}<tauri_runtime_wry::Wry<tauri::EventLoopMessage>, pot::main::{closure_env#2}>> (self=..., callback=...)
    at /home/iFlygo/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-runtime-wry-0.14.1/src/lib.rs:2256
#18 0x00006260c07576c8 in tauri::app::App<tauri_runtime_wry::Wry<tauri::EventLoopMessage>>::run<tauri_runtime_wry::Wry<tauri::EventLoopMessage>, pot::main::{closure_env#2}> (self=..., callback=...) at /home/iFlygo/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-1.5.2/src/app.rs:875
#19 0x00006260c09b1ec4 in pot::main () at src/main.rs:45
```

**Comment by TwelveNight** [comment]
已解决

**Comment by xymeng16** [comment]
> Arch Linux + KDE 在 Wayland 下也出现了同样的问题。启动命令：
> 
> ```
> env WEBKIT_DISABLE_DMABUF_RENDERER=1 GDK_BACKEND=x11 pot
> ```
> 
> 最终 libEGL 出现了错误：
> 
> ```
> libEGL warning: egl: failed to create dri2 screen
> 段错误（核心已转储）
> ```
> 
> 完整日志信息见 [Log of pot-desktop before crashing](https://gist.github.com/greyishsong/508c1605bea702571046b13bb93749f5)

同样的错误，日志也类似。环境Arch+Wayland+Hyprland-git
