### ISSUE TITLE
能在小窗口上加个截图翻译的按钮吗  附截图 那样就完完美了  

### ISSUE THREAD

**Issue by haha0803** [pot-app/pot-desktop#629]
### Description

能在小窗口上加个截图翻译的按钮吗  附截图 那样就完完美了  
![Snipaste_2023-12-22_11-46-59](https://github.com/pot-app/pot-desktop/assets/55041233/3e349380-cc82-464c-a9f4-1c1e1f1185cc)

### Application Scenario

翻译软件界面 就这个按钮方便很多   可以连续的点截图然后翻译  不用在按快捷键
![Snipaste_2023-12-22_11-54-05](https://github.com/pot-app/pot-desktop/assets/55041233/51586bb9-373b-447e-b875-6ca1f2bd08f0)

**Comment by detiam** [comment]
小问一下 这截图里是什么软件啊

**Comment by haha0803** [comment]
> 小问一下这个截图里是什么软件啊
https://getquicker.net/Sharedaction?code=04393db9-f4bc-4871-7fb6-08db2506d1ed             
![Uploading Snipaste_2023-12-23_08-19-21.png…]()
 链接在这里

**Comment by Pylogmon** [comment]
不打算加
