### ISSUE TITLE
[BUG]: 在27寸4k分辨率的win11上 显示砂纸200缩放后，UI很差

### ISSUE THREAD

**Issue by toyo2333** [pot-app/pot-desktop#630]
### Description

在27寸4k分辨率的win11上 显示砂纸200缩放后，UI很差

### Reproduction

在27寸4k分辨率的win11上 显示砂纸200缩放后，UI很差

### Platform

Windows

### System Version

win11 latest

### Window System (Linux Only)

None

### Software Version

latest

### Log File

在27寸4k分辨率的win11上 显示砂纸200缩放后，UI很差

### Additional Information

在27寸4k分辨率的win11上 显示砂纸200缩放后，UI很差

**Comment by Pylogmon** [comment]
你用很差这种词来描述，也没有截图，你觉得我应该从何入手来修复你所说的Bug？

**Comment by toyo2333** [comment]
算了，我觉得这个可能是一个审美层面的问题。close了。
