### ISSUE TITLE
[Feature]: 恢复备份不覆盖当前快捷键

### ISSUE THREAD

**Issue by Chandler-Lu** [pot-app/pot-desktop#633]
### Description

支持恢复备份时不覆盖当前的快捷键设置

### Application Scenario

在跨平台备份时，由于 Windows 和 macOS 存在一定的键位差别，不希望 win 端的配置完全覆盖 mac 端的配置。

**Comment by Pylogmon** [comment]
因为插件各个平台之间是有差异的，所以不推荐使用跨平台的备份，webdav备份支持备份多次，你可以对Mac和Windows分别进行备份
