### ISSUE TITLE
[BUG]: 下载1.6.0版本的pot，自启动有问题

### ISSUE THREAD

**Issue by HeyAlaia** [pot-app/pot-desktop#634]
### Description

windows重启后，pot设置自启动，启动的版本为1.6.0版本，但是电脑上的pot已经升级为最新版本了，我手动退出pot，手动重新启动，启动的版本是最新版本

### Reproduction

从老版本pot升级到最新版，设置开机自动启动，就会出现对应的问题

### Platform

Windows

### System Version

Windows 11 专业工作站版 23H2

### Window System (Linux Only)

None

### Software Version

2.7.3

**Comment by Pylogmon** [comment]
v1版本到v2版本改动较大，包括appid，应用内更新会识别不到旧版路径导致安装到默认路径，系统内会同时存在两个版本的pot，建议手动卸载旧版后再安装v2版本

**Comment by HeyAlaia** [comment]
> v1版本到v2版本改动较大，包括appid，应用内更新会识别不到旧版路径导致安装到默认路径，系统内会同时存在两个版本的pot，建议手动卸载旧版后再安装v2版本
好的 在控制面板中确实查看到了老版本和新版本共存的pot，手动卸载老版本确实正常启动了
