### ISSUE TITLE
[BUG]: 快捷键无法打开翻译界面

### ISSUE THREAD

**Issue by kdurant** [pot-app/pot-desktop#635]
### Description

快捷键无法调出界面，必须重启软件后才行

### Reproduction

1. 开启软件
2. 使用快捷键`<Ctrl-Alt-F>`调出**输入翻译**界面
3. 输入"hello wolrd"，按下`Enter`，显示翻译结果后，手动关闭界面/丢失焦点
4. 再次使用快捷键，无法显示界面。但`文字识别`和`截图翻译`可以调出界面

### Platform

Linux

### System Version

Ubuntu22.04.1

### Window System (Linux Only)

X11

### Software Version

2.7.3

**Comment by Pylogmon** [comment]
Gnome下获取不到焦点是已知问题，暂时没有办法解决，建议开启窗口默认置顶来使用。

**Comment by kdurant** [comment]
好吧，那只能这样了
