### ISSUE TITLE
[BUG]: 输入翻译时没有输入框

### ISSUE THREAD

**Issue by Tmq244** [pot-app/pot-desktop#636]
### Description

快捷键调出输入翻译的时候没有输入框

### Reproduction

快捷键调出输入翻译的时候没有输入框

### Platform

Windows

### System Version

Windows11

### Window System (Linux Only)

None

### Software Version

2.7.3

**Comment by Pylogmon** [comment]
你应该是开启了隐藏原文选项，目前隐藏原文选项对于划词翻译和输入翻译没有做区分，如果需要输入翻译还是把隐藏原文选项关了使用，这个后续会做区分优化。

**Comment by Tmq244** [comment]
谢谢了，已经解决了
