### ISSUE TITLE
[Feature]: 添加是否写入结果到txt文件的选项

### ISSUE THREAD

**Issue by xuestrange** [pot-app/pot-desktop#64]
### 需求描述

添加一个选项，准确来说是两个，在查完一个词，以后可以把单词和查出来的意思写入到一个文件中，这样就可以把这个文件导入到其他的单词软件进行学习，例如欧路词典。

句子也是同样的道理，希望能添加一个选项，把句子和相应的意思写入到一个文件中，这样也可以导入到其他文件，或者自己整理学习复杂句。

建议导出为txt或excel格式，两列，一列为单词，一列为意思。句子同理。

### 应用场景

论文写作，需要借鉴别人的句式和写作方法，保留为txt方便自己整理，并导入到其他软件中学习。
Anki并不常用。其他记单词软件的查词结果更丰富，如果导入到欧路词典，那就可以在欧陆词典中使用牛津词典学习pot查出来的单词，例句更丰富。

### 参考资料

定义文件保存路径，不断追加就可以了（不存在就自动创建）。
这个功能我觉得比Anki还要实用些。

**Comment by Pylogmon** [comment]
不同的软件需要的文件格式不一样，这样实现我觉得是比较鸡肋，已经有了翻译后自动复制的功能，你可以选择翻译后自动复制原文+译文然后自己粘贴，至于欧陆词典，我在之前查资料的时候记得见到过他们有开放api可以直接导入，但是我现在找不到了，我再找找看看能不能直接集成。

**Comment by Pylogmon** [comment]
http://my.eudic.net/OpenAPI/doc_api_study

**Comment by xuestrange** [comment]
> 不同的软件需要的文件格式不一样，这样实现我觉得是比较鸡肋，已经有了翻译后自动复制的功能，你可以选择翻译后自动复制原文+译文然后自己粘贴，至于欧陆词典，我在之前查资料的时候记得见到过他们有开放api可以直接导入，但是我现在找不到了，我再找找看看能不能直接集成。

复制是挺好的，但是直接集成就算了，还平白无故增加你的工作量。

虽然导出为txt看起来很鸡肋，但是非常方便个人的后续处理

**Comment by xuestrange** [comment]
像是很多单词软件，都提供了导入txt单词表的功能，比如墨墨背单词

**Comment by Pylogmon** [comment]
txt相当于就是搞了查词的历史记录，有时间搞一下。

**Comment by Pylogmon** [comment]
源文本和翻译的结果都有可能是多行的，这样的情况下txt文件没法排版呀。

**Comment by xuestrange** [comment]
> 源文本和翻译的结果都有可能是多行的，这样的情况下txt文件没法排版呀。

现在不建议添加这个功能了😃，如果作者想做的话，建议只添加单词，不添加句子，因为单词txt文件可以导入到其他单词软件中学习，而句子则不能

**Comment by xuestrange** [comment]
> > 源文本和翻译的结果都有可能是多行的，这样的情况下txt文件没法排版呀。
> 
> 现在不建议添加这个功能了😃，如果作者想做的话，建议只添加单词，不添加句子，因为单词txt文件可以导入到其他单词软件中学习，而句子则不能

这个实现起来倒也不复杂，用户指定一个路径文件，用户查词后点击添加就可以不断地在文件后边追加了。

**Comment by xuestrange** [comment]
现在有一个新的需求：界面的重新规划，目前来看，这个界面的图标是不是太大了，导致显示文本的区域面积太小了，不知道作者是否有这个规划（如调整字号，调整字体等 😄 )

**Comment by Pylogmon** [comment]
图标和文字大小相当，我觉得并不大。

**Comment by Pylogmon** [comment]
> 如调整字号，调整字体等

这方面调整整体的缩放比较好，就像浏览器调整100%、120%那样的缩放，现在tauri还不支持缩放，但是看issue已经在支持了，tauri正式支持之后我会添加缩放功能。

**Comment by LakeishaKowalczyk** [comment]
@xuestrange @Pylogmon 
你好，请问这个功能在哪里呢？想要批量导出最近两天的历史记录，但是找不到功能入口．
已经把设置界面来回看了几遍，也搜索过 Issues 了
