### ISSUE TITLE
[Feature]: title窗口位置更随鼠标时候,窗口以鼠标在左上角为基准出现

### ISSUE THREAD

**Issue by linzzzzllll** [pot-app/pot-desktop#640]
### Description

[Feature]: title窗口位置更随鼠标时候,窗口以鼠标在左上角为基准出现

### Application Scenario

[Feature]: title窗口位置更随鼠标时候,窗口以鼠标在左上角为基准出现

### References

[Feature]: title窗口位置更随鼠标时候,窗口以鼠标在左上角为基准出现

**Comment by Pylogmon** [comment]
什么意思，目前就是这样的呀，窗口在鼠标右下方出现，当窗口有可能超出屏幕的时候会变为左面或右面
