### ISSUE TITLE
[Feature]: 翻译服务在翻译面板的翻译策略改进

### ISSUE THREAD

**Issue by arpir** [pot-app/pot-desktop#645]
### Description

1. 假设我现在添加5个翻译服务到列表中的，并且全部启用，在翻译的时候默认就会翻译5次（5个不同的服务）!!!
2. 能否改进开关服务的策略？添加到列表中的服务都会在翻译面板中显示，但是只有开启的服务才会展开翻译，而没有开启的服务则收起来的，当点击的时候会自动展开，然后用这个服务翻译（没有开启的服务默认收起来，点击的时候会翻译并展开）。
3. 因为通常来说我们使用的也就几个固定的翻译，它们的翻译质量水平不会突然变化太大，比如常用DeepL，当DeepL翻译不满意的时候我才会去看看其他服务翻译的结果。这样减少了翻译发送的请求也减轻了用户的认知负载（界面更简洁）。而且平常使用OpenAI API作为翻译备选的话也不会频繁的发送请求。

### Application Scenario

改进开关服务的策略，添加到列表中的服务都会在翻译面板中显示，但是只有开启的服务才会展开翻译，而没有开启的服务则收起来的，当点击的时候会自动展开，然后用这个服务翻译。

1. 添加到服务列表中的翻译服务都会在翻译面板中显示；
2. 只有开启的服务才会默认展开翻译；
3. 没有开启的服务默认收起来，点击的时候才会翻译并展开。
4. 再次点击展开/折叠翻译服务块。

**Comment by Pylogmon** [comment]
现在不开启的服务不会翻译，点击下拉菜单切换即可翻译，一样的效果，而且还不会占用空间。

**Comment by arpir** [comment]
> 现在不开启的服务不会翻译，点击下拉菜单切换即可翻译，一样的效果，而且还不会占用空间。

不对啊，我安装已经是最新的版本了。现在不开启翻译直接在面板里面不会出现，如果同时开启多个它们又会同时翻译。还是你没明白我说的意思?

**Comment by arpir** [comment]
> > 现在不开启的服务不会翻译，点击下拉菜单切换即可翻译，一样的效果，而且还不会占用空间。
> 
> 不对啊，我安装已经是最新的版本了。现在不开启翻译直接在面板里面不会出现，如果同时开启多个它们又会同时翻译。还是你没明白我说的意思?

![](https://jsd.cdn.zzko.cn/gh/arpir/Pics@main/PicGo/202401070649710.png)
![](https://jsd.cdn.zzko.cn/gh/arpir/Pics@main/PicGo/202401070651266.png)

**Comment by Pylogmon** [comment]
点击接口名称切换
![image](https://github.com/pot-app/pot-desktop/assets/59004461/5e6ffcee-f431-4726-8320-c896a0810731)

**Comment by arpir** [comment]
原来是这样啊😂

Pylogmon ***@***.***> 于2024年1月7日周日 10:05写道：
