### ISSUE TITLE
app退回成了旧版本，且已配置的接口丢失

### ISSUE THREAD

**Issue by Juneone96** [pot-app/pot-desktop#650]
### Description

前端时间升级到了新版（ui更新后的那一版），并且配置了相应接口正常使用。今天打开突然又变回老版了，且上面的接口记录都丢失，也无法检查更新
![image](https://github.com/pot-app/pot-desktop/assets/140543869/a7b0baa7-3a96-466e-9196-be9646ca8753)

### Reproduction

anki_enable = false
app_language = "zh_cn"
auto_check = true
auto_copy = 2
auto_start = true
caiyun_token = "ubjlllet0nl6quf5rzrp"
default_interface_list = ["bing_dict","cambridge_dict","bing","tencent","transmart","caiyun","xiaoniu","tatoeba","lingva","palm","deepl"]
dynamic_translate = true
eudic_enable = false
hide_window = false
second_language = "en"
shortcut_persistent = "Alt+S"
shortcut_screenshot = "Alt+D"
shortcut_screenshot_translate = "Alt+F"
shortcut_translate = "Alt+A"
target_language = "zh_cn"
tencent_secretid = "AKIDzzkERORZlgMmwq6CeroVxf6GEwYu2GBD"
tencent_secretkey = "wf9NL2TfaEbLp20hBPyHK7dsq32mGUS9"
xiaoniu_apikey = "d96ce66f5d1da0cb6a591c58ca1553e6"

### Platform

Windows

### System Version

Windows 11 家庭中文版 23H2

### Window System (Linux Only)

None

### Software Version

1.14.0

**Comment by Pylogmon** [comment]
1.0版本和2.0版本配置文件并不兼容，直接升级是无法覆盖安装的，你现在的情况应该是新版安装到了系统默认路径，旧版没有卸载，手动卸载旧版之后找到新版使用就行。
