### ISSUE TITLE
[BUG]: title PC文字识别很慢？还有文字很小的时候特别慢有时候识别不了导致翻译不出来i

### ISSUE THREAD

**Issue by linzzzzllll** [pot-app/pot-desktop#654]
### Description

用的是百度的OCR

### Reproduction

PC文字识别很慢？还有文字很小的时候特别慢有时候识别不了导致翻译不出来i

### Platform

Windows

### System Version

PC文字识别很慢？还有文字很小的时候特别慢有时候识别不了导致翻译不出来i

### Window System (Linux Only)

None

### Software Version

PC文字识别很慢？还有文字很小的时候特别慢有时候识别不了导致翻译不出来i

### Log File

PC文字识别很慢？还有文字很小的时候特别慢有时候识别不了导致翻译不出来i

### Additional Information

PC文字识别很慢？还有文字很小的时候特别慢有时候识别不了导致翻译不出来i

**Comment by Pylogmon** [comment]
换其他OCR接口
