### ISSUE TITLE
[BUG]: openAI的请求地址使用国内中转，无法翻译

### ISSUE THREAD

**Issue by Adufun** [pot-app/pot-desktop#655]
### Description

**openAI的请求地址使用的国内中转，在内网环境下无法翻译，外网环境正常翻译。
在同内网环境下，其他网页翻译插件却能使用openAI**

![P}TVLVIG%IPRNMIXHUK4@ON](https://github.com/pot-app/pot-desktop/assets/61834743/a5036667-70b2-4724-9cc7-f1c03d6fedb6)
![N4XCJ656F} 0Z2G7S7W0$HI](https://github.com/pot-app/pot-desktop/assets/61834743/22a07be1-90d2-4895-940d-452cdc9a2029)
![EFV(JYRQVXGH YG)ADEOR~5](https://github.com/pot-app/pot-desktop/assets/61834743/4129899c-25e4-4514-9a25-5dc91d471ceb)

### Reproduction

1

### Platform

Windows

### System Version

win11 pro

### Window System (Linux Only)

None

### Software Version

2.7.3

**Comment by Pylogmon** [comment]
这是你选择的语种识别引擎的问题，你应该是选择了谷歌，跟openai没有关系
