### ISSUE TITLE
[Feature]: 增加插件功能

### ISSUE THREAD

**Issue by Shuai-S** [pot-app/pot-desktop#66]
### 需求描述

基本翻译功能完善后，可以通过插件功能来扩展额外需求，已方便不同人员的使用需求，比如词典，OCR等，根据个人使用场景来安装不同的插件

### 应用场景

已方便不同人员的使用需求

**Comment by Shuai-S** [comment]
而且可以根据个人兴趣来实现不同的插件，增加项目活跃度

**Comment by Pylogmon** [comment]
目前没有设计插件系统，要添加插件功能工作量还是有点多的，有时间再搞吧，优先级不会很高。
