### ISSUE TITLE
[BUG]: 翻译功能所有服务无法使用

### ISSUE THREAD

**Issue by HumanMus1c** [pot-app/pot-desktop#660]
### Description

更新到最新版本2.7.4之后，翻译服务全部无法使用。
点击翻译按钮与键盘回车均没有任何响应。
![image](https://github.com/pot-app/pot-desktop/assets/46023154/04592abd-a92c-4dfd-9977-0d9288089306)

### Reproduction

1.输入翻译无法使用
2.截图翻译无法使用（COR识别服务正常）

### Platform

Windows

### System Version

Windows 11 专业版 23H2 22631.2861

### Window System (Linux Only)

None

### Software Version

2.7.4

### Log File

[pot.log](https://github.com/pot-app/pot-desktop/files/13872406/pot.log)

**Comment by HumanMus1c** [comment]
![image](https://github.com/pot-app/pot-desktop/assets/46023154/0c08d2fe-50fb-42c6-b3fd-31e8c986ff0c)
都做了配置。

**Comment by Pylogmon** [comment]
我猜是你设置了语种识别引擎为google，但是没有开启代理。

**Comment by HumanMus1c** [comment]
> 我猜是你设置了语种识别引擎为google，但是没有开启代理。

谢谢，我的锅。
