### ISSUE TITLE
[Feature]: 再次请求添加双击 Ctrl 翻译的功能。

### ISSUE THREAD

**Issue by vagra** [pot-app/pot-desktop#663]
### Description

希望能够支持双击 Ctrl 翻译。

### Application Scenario

我们大部分软件使用的是标准快捷键，也就是说 Ctrl 加任意字母键；

然后呢，Pot 也是使用标准快捷键，结果呢，它就基本上不可能存在一个 Ctrl 加某个字母键，能够跟所有软件的快捷键都不冲突。
也就是说总会在某个软件中，Pot 的快捷键跟它冲突，那就会影响软件的使用。

但是呢，使用非常冷门的 Ctrl 双击作为 Pot 的快捷键的话，就没有这个冲突问题了。

这个功能我首先在 Qtranslate 里面发现的，非常好用，一旦接触，就再也看不上其它翻译软件的这个功能了。就因为这个功能，我在 QTranslate 事实死亡后还坚持用了两年，很高兴看到 Pot 作为一个崭新的翻译软件出现，但是希望它也有这个功能，真的非常好用。

### References

QTranslate
有道词典

**Comment by Pylogmon** [comment]
不要重复提交issue好吗？
