### ISSUE TITLE
[Feature]: 当再次按下快捷键时，关闭窗口。

### ISSUE THREAD

**Issue by NianBroken** [pot-app/pot-desktop#665]
### Description

例如我设置了Alt+Q是输入翻译，那么在翻译窗口处于打开状态时，当我再次按下Alt+Q则关闭窗口，而不需要我去点击右上角关闭的控件。

### Application Scenario

例如翻译完了之后，我需要立刻全屏进入写作状态，若翻译窗口依然存在，则会遮挡我的写作窗口。但失去焦点时关闭窗口又不太合适。

**Comment by Pylogmon** [comment]
Esc关闭窗口
