### ISSUE TITLE
[Feature]: 请不要让ctrl+c 自动翻译，我如何设置不让他翻译啊！

### ISSUE THREAD

**Issue by chenhui2016** [pot-app/pot-desktop#669]
### Description

我把auto copy设置到disable也不行，每次我复制东西都会出现翻译的框，我都得手动关闭，我设置了alt+s翻译就很好用，为什么ctrl c也是翻译啊？怎么设置不让他翻译呢？

### Application Scenario

我把auto copy设置到disable也不行，每次我复制东西都会出现翻译的框，我都得手动关闭，我设置了alt+s翻译就很好用，为什么ctrl c也是翻译啊？怎么设置不让他翻译呢？

**Comment by chenhui2016** [comment]
系统是Ubuntu22.04

**Comment by Pylogmon** [comment]
你开了剪切板监听啊，托盘菜单关闭
