### ISSUE TITLE
[BUG]: 开机自启有问题

### ISSUE THREAD

**Issue by CyshallChan** [pot-app/pot-desktop#671]
### Description

开机自启有问题已经很久了，我印象中就没有成功过。

### Reproduction

开机无法自启。

### Platform

Windows

### System Version

windows11 版本23H2(22631.3007)

### Window System (Linux Only)

None

### Software Version

2.7.4

### Log File

[pot.log](https://github.com/pot-app/pot-desktop/files/13964165/pot.log)

### Additional Information

尝试了卸载重装、设置里开机自启重新点按都没效果。

任务管理器中自启app也能看到有pot，右键也可以打开文件所在的位置：
![image](https://github.com/pot-app/pot-desktop/assets/22564041/9c71fcd8-25fe-4c51-979c-a9a6f96fb99d)

另外再提供一些信息：
1. 管理运行的pot；
2. uac设置的不提示。

**Comment by Pylogmon** [comment]
不要用管理员权限运行

**Comment by CyshallChan** [comment]
> 不要用管理员权限运行

我记得如果不用管理员权限好像无法在线升级？

**Comment by Pylogmon** [comment]
早就修了

**Comment by CyshallChan** [comment]
> 早就修了

好的，感谢。
