### ISSUE TITLE
[兼容WINDWOS 11 专业版]: pot_2.7.4 在Windows 11专业版 无法使用

### ISSUE THREAD

**Issue by vicktw** [pot-app/pot-desktop#675]
### Description

pot_2.7.4 在Windows 11专业版 无法使用
![20240119231637](https://github.com/pot-app/pot-desktop/assets/80954276/1484342c-468f-4856-b9eb-51f2181722dd)
![20240119231710](https://github.com/pot-app/pot-desktop/assets/80954276/13b38faf-0628-4517-9257-be5d31d27dc5)

### Application Scenario

希望更新兼容WINDOWS 11 专业版 64位的。

**Comment by Pylogmon** [comment]
你下错了

**Comment by vicktw** [comment]
> 你下错了

是哦，下arm64了。谢谢高手
