### ISSUE TITLE
[BUG]: 必应/Yandex翻译无法使用

### ISSUE THREAD

**Issue by RiftRays** [pot-app/pot-desktop#680]
### Description

必应翻译无法使用

![image](https://github.com/pot-app/pot-desktop/assets/60778141/a95cd8b2-d62f-4cff-a2f6-4b7b89f3492b)

Yandex
![image](https://github.com/pot-app/pot-desktop/assets/60778141/15a3d4ab-b4d1-4f2f-97e2-6a2c835f6078)

### Reproduction

正常使用翻译。

### Platform

Windows

### System Version

Windows 11 Pro 26020

### Window System (Linux Only)

None

### Software Version

2.7.4

### Log File

Network Error: error sending request for url (https://edge.microsoft.com/translate/auth): error trying to connect: unexpected EOF during handshake: error sending request for url (https://edge.microsoft.com/translate/auth): error trying to connect: unexpected EOF during handshake: error trying to connect: unexpected EOF during handshake: unexpected EOF during handshake

**Comment by Pylogmon** [comment]
网络问题，有些地区的网络确实是用不了的
