### ISSUE TITLE
[BUG]: 拓展屏无法截图翻译

### ISSUE THREAD

**Issue by Lingmobai17** [pot-app/pot-desktop#682]
### Description

我的笔记本外接了一块拓展屏，截图翻译只能在我笔记本屏幕截图翻译，拓展屏无法截图翻译，当我在设置里面将拓展屏设置为主屏幕时，情况恰恰相反，拓展屏能截图翻译，笔记本屏幕无法截图翻译，我尝试关掉核显与独显混合输出，只启用独显，发现并不起作用，还是不能截图翻译
![bug](https://github.com/pot-app/pot-desktop/assets/126227944/1b1c4015-2216-4ae8-b46b-ff73b141c4b8)

### Reproduction

拓展屏无法截图

### Platform

Windows

### System Version

Windows 10 家庭中文版 19045.3930

### Window System (Linux Only)

None

### Software Version

2.7.4

**Comment by Pylogmon** [comment]
截图只在鼠标所在的屏幕启动
