### ISSUE TITLE
划词翻译免快捷键

### ISSUE THREAD

**Issue by huomutech** [pot-app/pot-desktop#690]
### Description

选中文本即可翻译，免去快捷键

### Application Scenario

经常选中文本再按快捷键麻烦

### References

[百度翻译桌面版](https://fanyi.baidu.com/appdownload/download.html?tab=desktop&fr=pcproduct)

**Comment by Pylogmon** [comment]
https://pot-app.com/docs/invoke.html#%E7%8E%B0%E6%9C%89%E7%94%A8%E6%B3%95-%E5%BF%AB%E6%8D%B7%E5%88%92%E8%AF%8D%E7%BF%BB%E8%AF%91-%E6%8E%A8%E8%8D%90%E4%BD%BF%E7%94%A8
