### ISSUE TITLE
[BUG]: 修改Gemini Pro的配置无法保存，提示400

### ISSUE THREAD

**Issue by Juneone96** [pot-app/pot-desktop#705]
### Description

Gemini Pro官网能正常进入，切换了各种美国节点线路以及开关TUN模式下都会提示400
![image](https://github.com/pot-app/pot-desktop/assets/140543869/3247540f-b17f-4f1d-b148-0ce18bd87fb9)

### Reproduction

点击修改已配置好的Gemini Pro，并在修改后尝试保存

### Platform

Windows

### System Version

Windows 11 家庭中文版 23H2

### Window System (Linux Only)

None

### Software Version

2.7.6

**Comment by Pylogmon** [comment]
看看代理日志到底走的哪个节点

**Comment by Pylogmon** [comment]
如果要使用流式输出请开启系统代理使用。

**Comment by Pylogmon** [comment]
#698

**Comment by iG8R** [comment]
> 如果要使用流式输出请开启系统代理使用。

Could you please recommend any system proxy with which `pot` would work fine?

**Comment by suibianzai** [comment]
> [@Pylogmon](https://github.com/Pylogmon)
> 
> > 如果要使用流式输出请开启系统代理使用。
> 
> Could you please recommend any system proxy with which `pot` would work fine?

try clash verge. 
pot's setup - general -proxy -  https://127.0.0.1 port:7897
clash verge - click on "system proxy" (and if you don't have proper rules, just select global mode)

**Comment by suibianzai** [comment]
用https协议试试
clash选系统代理（没有适配规则就选全局），然后打开pot的代理，填写127.0.0.1 端口7897
如果不行 大概率是节点的问题 换个路线或者机场多试试

**Comment by iG8R** [comment]
@suibianzai 
Thank you very much!
