### ISSUE TITLE
[Feature]: 增加翻译窗口下，指定翻译引擎默认折叠功能（主要是为了省token钱）

### ISSUE THREAD

**Issue by Asuta** [pot-app/pot-desktop#716]
### Description

很多时候，对一些简单的句子的翻译，用一些免费翻译服务（百度  谷歌  腾讯翻译）之类的，就可以很好的完成，只有一部分很难的句子，需要像是OpenAI这种需要花钱调接口的服务

所以希望能加上“翻译引擎折叠”的功能，比如我设置了使用两个引擎“谷歌翻译”和“OpenAI的接口”，而默认激活翻译后，只打开一个“谷歌翻译”，另一个“open ai”处于折叠状态，当我觉得“谷歌翻译”不够精准的时候，再手动点一下“OpenAI”展开折叠，开始进行翻译

这样就能省掉很多token！（很多很多）

### Application Scenario

需要节省token的时候。。。。

### References

同样的功能是参考的TTime这个翻译（好像POP也有这个设计？）
[安装使用 | TTime (timerecord.cn)](https://ttime.v1.timerecord.cn/pages/1c1de2/#%E6%82%AC%E6%B5%AE%E9%92%89%E6%A8%A1%E5%BC%8F)（悬浮钉模式）（感觉这个比折叠模式更方便点）
[安装使用 | TTime (timerecord.cn)](https://ttime.v1.timerecord.cn/pages/1c1de2/#%E6%8A%98%E5%8F%A0%E6%A8%A1%E5%BC%8F)（折叠模式）

（在TTime里这两模式甚至还要充钱才能用。。。。）

**Comment by Pylogmon** [comment]
添加服务之后把右侧开关关闭，翻译的时候点击服务名称切换即可

**Comment by Asuta** [comment]
> 添加服务之后把右侧开关关闭，翻译的时候点击服务名称切换即可

哦哦  学会了   有点隐蔽啊这个。。。。。
不过这个还是要点两下  能点一下就完成就更棒了
