### ISSUE TITLE
[Feature]: 支持本地大模型翻译

### ISSUE THREAD

**Issue by caecfd** [pot-app/pot-desktop#722]
### Description

调用本机上部署的大模型进行翻译

### Application Scenario

能否实现 一个类似OpenAI Translator里面带的可以自行配置本地大模型翻译的接口，比如支持Ollama、llama-CPP之类的，这样就可以实现离线翻译，而不用依赖联网和别人的API了。

**Comment by H1DDENADM1N** [comment]
自荐下我的项目[H1DDENADM1N/CapsWriter-Offline](https://github.com/H1DDENADM1N/CapsWriter-Offline) 可以用 Transformers 离线翻译模型[Helsinki-NLP/opus-mt-zh-en](https://huggingface.co/Helsinki-NLP/opus-mt-zh-en)。虽然主要功能是语音输入，但在最新版增加了 将光标选中的中文离线翻译并覆盖原文，按下 `Alt` + `Z` ，可以将光标选中了中文离线翻译为英文。通过 `config.py` 中 `trans_and_replace_selected_shortcut` 配置。

![将光标选中了中文离线翻译](https://github.com/pot-app/pot-desktop/assets/65646535/8b279e17-d8b6-41ef-bcb0-8d2f66f50304)

**Comment by caecfd** [comment]
您好，已收到您的邮件，我会在最短的时间内给您回复，谢谢！
