### ISSUE TITLE
[BUG]: Can't get connected to Ollama on macOS

### ISSUE THREAD

**Issue by ivaquero** [pot-app/pot-desktop#726]
### Description

I updated to the latest version, but I cannot get connected to Ollama on my macOS

### Reproduction

Open Config -> Service -> Add Service

<img width="800" alt="image" src="https://github.com/pot-app/pot-desktop/assets/46377665/004c0d61-c0c4-4c36-9c0a-21e86c373f79">

### Platform

MacOS

### System Version

Sonoma

### Window System (Linux Only)

None

### Software Version

2.7.9

**Comment by Pylogmon** [comment]
Have you installed and started Ollama?

**Comment by Pylogmon** [comment]
Please try to set environment variables for Ollama:

```bash
launchctl setenv OLLAMA_ORIGINS "*"
```

**Comment by ivaquero** [comment]
Yes, I installed and started, also add `launchctl setenv OLLAMA_ORIGINS "*"`, but doesn't work
`

**Comment by ivaquero** [comment]
I ran openai-translator with ollama successfully, however, its OCR is poor, so I turnt to Pot

**Comment by Pylogmon** [comment]
Can you look at the output of `curl http://localhost:11434/api/tags` in the terminal?

**Comment by ivaquero** [comment]
```console
❯ curl http://localhost:11434/api/tags
{"models":[{"name":"gemma:7b","model":"gemma:7b","modified_at":"2024-02-26T21:47:11.244479723+08:00","size":5202317200,"digest":"430ed3535049f562814f612a653457ba9fd390cccc77a94ab88964b8d8fd18a8","details":{"parent_model":"","format":"gguf","family":"gemma","families":["gemma"],"parameter_size":"9B","quantization_level":"Q4_0"}},{"name":"gemma:latest","model":"gemma:latest","modified_at":"2024-03-02T23:50:59.688162714+08:00","size":5202317200,"digest":"430ed3535049f562814f612a653457ba9fd390cccc77a94ab88964b8d8fd18a8","details":{"parent_model":"","format":"gguf","family":"gemma","families":["gemma"],"parameter_size":"9B","quantization_level":"Q4_0"}}]}%   
```

**Comment by Pylogmon** [comment]
Did you restart `Ollama` after setting the environment variables?

**Comment by ivaquero** [comment]
Yes.

**Comment by Pylogmon** [comment]
Try setting it to `tauri://*`

**Comment by Pylogmon** [comment]
Or start ollama from the command line like this

```bash
OLLAMA_ORIGINS=tauri://* ollama serve
```

**Comment by ivaquero** [comment]
I reinstalled the Ollama just now, I'll report the results tommorrow.

**Comment by ivaquero** [comment]
依然不行

**Comment by ivaquero** [comment]
I think `launchctl setenv OLLAMA_ORIGINS` works, but I don't know what hinders the request from the other apps.

**Comment by liiyee** [comment]
same here.

**Comment by ivaquero** [comment]
Solved by resetting `OLLAMA_HOST`.
