### ISSUE TITLE
[Feature] 能否添加增量翻译的功能？

### ISSUE THREAD

**Issue by kingxiaofire** [pot-app/pot-desktop#73]
### 问题描述

非常感谢提供如此优秀的软件。
在使用过程中发现，划词翻译后，窗口不固定住就会消失，要是固定住了没有办法翻译新的内容，需要关掉正在显示的固定窗口。而能固定窗口的独立翻译没有办法划词。
因此能将二者相结合，使得划词划词也能增量翻译呢？

### 如何复现

无需复现

### 操作系统

Windows (Default)

### 操作系统版本

window10

### 窗口系统(Linux Only)

None

**Comment by Pylogmon** [comment]
已实现，发布之前可以在actions下载自动构建版本尝试
https://github.com/pot-app/pot-desktop/actions/runs/4966277564
