### ISSUE TITLE
[BUG]: Windows卸载Microsoft Edge（没有卸载Microsoft Edge WebView2）后无法启动

### ISSUE THREAD

**Issue by KawausoJyou** [pot-app/pot-desktop#751]
### Description

Windows卸载Microsoft Edge（没有卸载Microsoft Edge WebView2）后无法启动

### Reproduction

启动软件。

### Platform

Windows

### System Version

Windows 11 专业版 22631.3296

### Window System (Linux Only)

None

### Software Version

2.7.9

**Comment by Pylogmon** [comment]
什么问题你不是已经很清楚了吗
