### ISSUE TITLE
[BUG]: <openai接口下,配置第二语言貌似没生效>

### ISSUE THREAD

**Issue by alice92bob** [pot-app/pot-desktop#77]
### 问题描述

翻译设置开启 删除换行 记住语言 openai流式输出,接口使用openai,目标语言中文,第二语言英语
搜索中文并不会自动输出英语

### 如何复现

openai使用的api2d的接口openai.api2d.net

### 操作系统

Windows (Default)

### 操作系统版本

win11

### 窗口系统(Linux Only)

None

### 软件版本

pot:0.3.0  Tauri:1.3.0

### 补充信息

无

**Comment by Pylogmon** [comment]
确实
