### ISSUE TITLE
[BUG]: Cannot install on Ubuntu

### ISSUE THREAD

**Issue by Alimjoo** [pot-app/pot-desktop#794]
### Description

The following packages have unmet dependencies:
 pot : Depends: libwebkit2gtk-4.0-37 but it is not installable
E: Unable to correct problems, you have held broken packages.

### Reproduction

I have installed libwebkit2gtk-4.1, that is the only one that available in apt package manager, how to solve this problem

### Platform

Linux

### System Version

Ubunru 24

### Window System (Linux Only)

None

### Software Version

2.7.10

### Log File

 $ sudo apt install ./pot_2.7.10_amd64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'pot' instead of './pot_2.7.10_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pot : Depends: libwebkit2gtk-4.0-37 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by xtyuns** [comment]
It is not a bug of this repository , and here are some reference information: https://github.com/tauri-apps/tauri/issues/9662

**Comment by xtyuns** [comment]
手动安装方法：

```shell
wget http://archive.ubuntu.com/ubuntu/pool/main/w/webkit2gtk/libwebkit2gtk-4.0-37_2.44.2-0ubuntu0.22.04.1_amd64.deb http://archive.ubuntu.com/ubuntu/pool/main/w/webkit2gtk/libjavascriptcoregtk-4.0-18_2.44.2-0ubuntu0.22.04.1_amd64.deb
sudo dpkg -i libwebkit2gtk-4.0-37_2.44.2-0ubuntu0.22.04.1_amd64.deb libjavascriptcoregtk-4.0-18_2.44.2-0ubuntu0.22.04.1_amd64.deb
```

相关软件包信息：
https://pkgs.org/download/libwebkit2gtk-4.0-37
https://pkgs.org/download/libjavascriptcoregtk-4.0-18

**Comment by tangyunlong** [comment]
> 手动安装方法：
> 
> ```shell
> wget http://archive.ubuntu.com/ubuntu/pool/main/w/webkit2gtk/libwebkit2gtk-4.0-37_2.44.2-0ubuntu0.22.04.1_amd64.deb http://archive.ubuntu.com/ubuntu/pool/main/w/webkit2gtk/libjavascriptcoregtk-4.0-18_2.44.2-0ubuntu0.22.04.1_amd64.deb
> sudo dpkg -i libwebkit2gtk-4.0-37_2.44.2-0ubuntu0.22.04.1_amd64.deb libjavascriptcoregtk-4.0-18_2.44.2-0ubuntu0.22.04.1_amd64.deb
> rm libwebkit2gtk-4.0-37_2.44.2-0ubuntu0.22.04.1_amd64.deb libjavascriptcoregtk-4.0-18_2.44.2-0ubuntu0.22.04.1_amd64.deb
> ```
> 
> 相关软件包信息： https://pkgs.org/download/libwebkit2gtk-4.0-37 https://pkgs.org/download/libjavascriptcoregtk-4.0-18

我在安装这两个包的时候，会出现问题，报错如下：
Selecting previously unselected package libwebkit2gtk-4.0-37:amd64.
(Reading database ... 189595 files and directories currently installed.)
Preparing to unpack libwebkit2gtk-4.0-37_2.44.2-0ubuntu0.22.04.1_amd64.deb ...
Unpacking libwebkit2gtk-4.0-37:amd64 (2.44.2-0ubuntu0.22.04.1) ...
Selecting previously unselected package libjavascriptcoregtk-4.0-18:amd64.
Preparing to unpack libjavascriptcoregtk-4.0-18_2.44.2-0ubuntu0.22.04.1_amd64.deb ...
Unpacking libjavascriptcoregtk-4.0-18:amd64 (2.44.2-0ubuntu0.22.04.1) ...
dpkg: dependency problems prevent configuration of libwebkit2gtk-4.0-37:amd64:
 libwebkit2gtk-4.0-37:amd64 depends on libicu70 (>= 70.1-1~); however:
  Package libicu70 is not installed.

dpkg: error processing package libwebkit2gtk-4.0-37:amd64 (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libjavascriptcoregtk-4.0-18:amd64:
 libjavascriptcoregtk-4.0-18:amd64 depends on libicu70 (>= 70.1-1~); however:
  Package libicu70 is not installed.

dpkg: error processing package libjavascriptcoregtk-4.0-18:amd64 (--install):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.39-0ubuntu8.2) ...
Errors were encountered while processing:
 libwebkit2gtk-4.0-37:amd64
 libjavascriptcoregtk-4.0-18:amd64
 
 我的系统版本是24.04， pot的版本是3.0.5，安装pot 的时候和楼主是一样的报错
 Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pot : **Depends: libwebkit2gtk-4.0-37** but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by xtyuns** [comment]
> libwebkit2gtk-4.0-37:amd64 depends on libicu70 (>= 70.1-1~); however:
> Package libicu70 is not installed.

先执行以下命令安装依赖库
```bash
wget http://archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu70_70.1-2ubuntu1_amd64.deb
sudo dpkg -i libicu70_70.1-2ubuntu1_amd64.deb
rm libicu70_70.1-2ubuntu1_amd64.deb
```

**Comment by tangyunlong** [comment]
work!! :)

**Comment by qian160** [comment]
这里还有另外一种懒人方法。大家要是不想安装依赖的话也可以参考一下。
从release页面下载后缀为AppImage的[这个文件](https://github.com/pot-app/pot-desktop/releases/download/3.0.5/pot_3.0.5_amd64.AppImage)，下载完成后
```
sudo chmod +x ./pot_3.0.5_amd64.AppImage
```
然后
```
./pot_3.0.5_amd64.AppImage
```
即可运行。
要是还想为它创建快捷启动方式的话得手动操作一下，可以参考.desktop文件的写法。

**Comment by wcbing** [comment]
Can you reopen this, because they haven't solved the problem for over a year.

To developer：
不行可以参考[clash-verge](https://github.com/clash-verge-rev/clash-verge-rev/blob/dev/.github/workflows/release.yml#L49)的 workflow，对方已经在去年解决这个问题。
