### ISSUE TITLE
[Feature]: 添加重新启动选项

### ISSUE THREAD

**Issue by xuestrange** [pot-app/pot-desktop#80]
### 需求描述

在Windows状态栏图标右击时，增加一个选项，重新启动该软件

### 应用场景

重新启动可以获得更新，以及解决软件卡死，划词失效的问题

**Comment by Pylogmon** [comment]
信我，卡死的时候托盘图标你都点不动

**Comment by Pylogmon** [comment]
我倒是好奇，什么情况下会卡死，应该解决这个问题而不是加个鸡肋的重启键。

**Comment by xqXQzzz1** [comment]
> 我倒是好奇，什么情况下会卡死，应该解决这个问题而不是加个鸡肋的重启键。

但是确实抓不到，开着开着，就卡死了，托盘右键也没有反应
