### ISSUE TITLE
我也是，运行不了

### ISSUE THREAD

**Issue by fuxin-mail** [pot-app/pot-desktop#805]
我也是，运行不了

_Originally posted by @Xiling341 in https://github.com/pot-app/pot-desktop/issues/773#issuecomment-2053171042_
            你的解决了吗？

**Comment by xtyuns** [comment]
duplicate of #773

**Comment by fuxin-mail** [comment]
> ```
>           我也是，运行不了
> ```
> 
> _Originally posted by @Xiling341 in [#773 (comment)](https://github.com/pot-app/pot-desktop/issues/773#issuecomment-2053171042)_ 你的解决了吗？

没问题是我不会用，我不用了
