### ISSUE TITLE
[BUG]: Adobe PDF 部分情况下无法翻译

### ISSUE THREAD

**Issue by xuestrange** [pot-app/pot-desktop#81]
### 问题描述

如图所示，选中之后，按下划词翻译快捷键，没有结果出来
![symbol2](https://github.com/pot-app/pot-desktop/assets/59390321/113a4110-ffcf-4c17-91f8-d5f4429eb5d8)

### 如何复现

下载SSRN上的一篇[论文](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4376783)，这个论文大概是word写的，然后转成PDF的，然后用Adobe PDF打开，然后用pot划词翻译

### 操作系统

Windows (Default)

### 操作系统版本

win 10

### 窗口系统(Linux Only)

None

### 软件版本

pot:0.3.1  Tauri:1.3.0

**Comment by Pylogmon** [comment]
换快捷键F1试试，有可能是快捷键冲突
