### ISSUE TITLE
[Feature]: 请求增加deepseek接口

### ISSUE THREAD

**Issue by xiao-zy19** [pot-app/pot-desktop#812]
### Description

希望能够加入deepseek v2的api接口

### Application Scenario

deepseek api物美价廉，api接口为：https://api.deepseek.com/v1

**Comment by sch-lda** [comment]
deepseek是openai兼容接口，换一下endpoint、apikey和模型名就可以直接用

**Comment by yixiaip** [comment]
可以是可以，但是这玩意只能编辑一次，假如我要用通义的，原来的配置就会被覆盖掉，建议改成多次添加，并且可以修改服务名称。

**Comment by syaoranwe** [comment]
写了一个：https://github.com/syaoranwe/pot-app-translate-plugin-deepseek

**Comment by lenghonglin** [comment]
> deepseek是openai兼容接口，换一下endpoint、apikey和模型名就可以直接用

测试了，可以用

**Comment by xiao-zy19** [comment]
抱歉忘了关闭这个issue
