### ISSUE TITLE
[Feature]: 使用内部的复制按钮的时候不要触发剪切板

### ISSUE THREAD

**Issue by wwjCMP** [pot-app/pot-desktop#813]
### Description

使用内部的复制按钮的时候不要触发剪切板

### Application Scenario

影响其他的翻译服务

**Comment by xtyuns** [comment]
> 使用内部的复制按钮的时候不要触发剪切板

剪切板是操作系统的行为，没有搞懂你的意图

**Comment by wwjCMP** [comment]
> > 使用内部的复制按钮的时候不要触发剪切板
> 
> 剪切板是操作系统的行为，没有搞懂你的意图

不要触发软件对剪切板的读取

**Comment by xtyuns** [comment]
请详细地描述你在使用 Pot 过程中遇到的问题，及预期结果
