### ISSUE TITLE
[BUG]: openAI的配置界面无法修改模型

### ISSUE THREAD

**Issue by Juneone96** [pot-app/pot-desktop#815]
### Description

![image](https://github.com/pot-app/pot-desktop/assets/140543869/5d254a7c-5519-4282-90df-fce8eda08abe)
配置过的openai api现在想修改模型改不了，没有选项卡了，请问怎么解决

### Reproduction

None

### Platform

Windows

### System Version

Windows 11 家庭中文版 23H2

### Window System (Linux Only)

None

### Software Version

2.7.10

**Comment by lhj5426** [comment]
确实 想使用 诸如 KIMK  deepseekv2 CLAUDE3 这种可以 使用OPENAI格式 API的 模型 都无法自定义模型名来使用
被限制死了

**Comment by xtyuns** [comment]
@Juneone96 在服务设置中可以通过编辑操作来修改模型

@lhj5426 模型支持自定义内容
