### ISSUE TITLE
Deeplx

### ISSUE THREAD

**Issue by Fan-Bob** [pot-app/pot-desktop#819]
### Description

Hope add deeplx.....

### Application Scenario

deeplx API

### References

deeplx！！！

**Comment by xtyuns** [comment]
DeepL 配置中支持 DeepLX
![deeplx](https://github.com/pot-app/pot-desktop/assets/41326335/8bac5755-ab05-4b98-8cc8-a69af4821892)

**Comment by limbia** [comment]
![image](https://github.com/pot-app/pot-desktop/assets/34004076/bafa65e1-7a0f-4ca6-b1c0-75cf551fad6e)

想问下为啥填这个不行呀.. http://127.0.0.1:1188/translate  报错Request Error Http Status: 502 没搞明白

**Comment by Fan-Bob** [comment]
公网

**Comment by STHxiao** [comment]
是什么原因阿？
