### ISSUE TITLE
[Feature]: 希望能设置像DeepL一样的热键 CTRL+CC

### ISSUE THREAD

**Issue by m565664180** [pot-app/pot-desktop#821]
### Description

因为CTRL+CC可以在复制文本的同时触发翻译, 翻译之后很方便就可以使用粘贴了
(DeepL前重度使用者, 无奈那个软件网络真的太差...)

### Application Scenario

尝试过修改热键, 似乎目前无法达成

**Comment by xtyuns** [comment]
duplicate of #353
