### ISSUE TITLE
[BUG]: WIN7 X64下窗口无法显示......

### ISSUE THREAD

**Issue by wxlg1117** [pot-app/pot-desktop#85]
### 问题描述

WIN7 X64下窗口无法显示

### 如何复现

在win7 x64系统下:
pot_0.3.2_x64_zh-CN.msi 版安装过程就报失败.

pot_0.3.2_x64_portable.zip版解压运行系统栏出现图标,双击没反应,右键有菜单,但是点击设置也不会出现窗口.

### 操作系统

Windows (Default)

### 操作系统版本

Windows 7 X64

### 窗口系统(Linux Only)

None

**Comment by Pylogmon** [comment]
麻烦提供一下安装过程的报错信息，因为win7没有自带的webview2，所以便携版是没法运行的，必须由安装包来安装webview2

**Comment by Pylogmon** [comment]
已修复，下个版本可用，或者可以下载这个
https://github.com/pot-app/pot-desktop/suites/12948945728/artifacts/699953856

**Comment by wxlg1117** [comment]
> 已修复，下个版本可用，或者可以下载这个 https://github.com/pot-app/pot-desktop/suites/12948945728/artifacts/699953856

该版本win10上可用,但是在win7 x64上,不管根据文档设置代理格式(http: http://{host}:{port}或socks5: socks5://{host}:{port})还是不用代理,点击翻译都会报错:

`Network Error: Tls Error: 接收到的消息异常，或格式不正确。 (os error -2146893018): Tls Error: 接收到的消息异常，或格式不正确。 (os error -2146893018)`
