### ISSUE TITLE
[BUG]: 界面显示为透明形态

### ISSUE THREAD

**Issue by china5** [pot-app/pot-desktop#862]
### Description

当我点击任务栏的input translate选项时，有时候没反应，有时候是透明的一个窗口，使用快捷键截图翻译也是这种情况，这个情况我之前没遇到过，但是更新到3.0.2后就这样，直接无法使用
![pot_pAxbg8h2la](https://github.com/pot-app/pot-desktop/assets/90046795/6d7072c7-6b0b-4942-b1dc-d9fc8d2a23b1)

### Reproduction

1.任务栏图标input translate选项没反应
2.快捷键也一样

### Platform

Windows

### System Version

windows 11

### Window System (Linux Only)

None

### Software Version

3.0.2

**Comment by wpgosite** [comment]
退回3.0.1正常使用

**Comment by china5** [comment]
![Uploading pot_KW3maqGvh0.png…]()

**Comment by china5** [comment]
![pot_KW3maqGvh0](https://github.com/pot-app/pot-desktop/assets/90046795/eeaa3f49-6cb0-4ee8-993d-9870db2fac18)

**Comment by china5** [comment]
可能翻译服务太多不兼容导致的，我重新安装后不导入我之前的配置就可以正常使用3.0.5
