### ISSUE TITLE
能否像Qtranslate一样，全局选中文本都能出现按钮[Feature]: <标题>

### ISSUE THREAD

**Issue by Lao-Tz** [pot-app/pot-desktop#87]
### 需求描述

快捷键感觉有点鸡肋，而且如果快捷键设置成 CTRL+c 会一直翻译之前复制的文字，无法翻译现在选中的文字

### 应用场景

使用时

**Comment by Pylogmon** [comment]
https://pot.pylogmon.cn/docs/tutorial/config/plugin_config
