### ISSUE TITLE
第三方键盘输入卡死

### ISSUE THREAD

**Issue by QiQi777iii** [pot-app/pot-desktop#870]
### Description

在使用第三方键盘(小狼毫输入法)的时候，中文模式会导致卡死，无法继续输入文本。

### Reproduction

![image](https://github.com/pot-app/pot-desktop/assets/141505720/4acd15bd-d4c7-47e0-915d-fa04d35cfba4)
类似上述情况只能重启应用。

### Platform

Windows

### System Version

Windows 10 pro

### Window System (Linux Only)

None

### Software Version

3.0.5

**Comment by QiQi777iii** [comment]
内个文件下载不了，我下载了最新的nightly版本还是无法解决，我把pot窗口不置顶使用吧。

**Comment by 0xSparks** [comment]
去年nightly都解决了，怎么现在又不行了，没搞懂😓

**Comment by uqiu** [comment]
我fork了代码，现在正在编译去年5月份的commit，我一个一个编译过去，看看哪个能用

**Comment by uqiu** [comment]
[artifact.zip](https://github.com/user-attachments/files/17825293/artifact.zip)
基于这个commit 9c7ea6cdde68e2ffdf7e0c2fe4adf1f62f0f66bb
看起来是可以用了
你们可以试试

**Comment by qiqi777iii** [comment]
好的，等我新电脑到就试试 现在电脑坏了

**Comment by qiqi777iii** [comment]
> [artifact.zip](https://github.com/user-attachments/files/17825293/artifact.zip)
> 
> 基于这个commit 9c7ea6cdde68e2ffdf7e0c2fe4adf1f62f0f66bb
> 
> 看起来是可以用了
> 
> 你们可以试试

可以用了谢谢
