### ISSUE TITLE
谷歌 AI添加不上 

### ISSUE THREAD

**Issue by lhj5426** [pot-app/pot-desktop#877]
### Description

如图所示 我在其他程序上可以使用的 的谷歌API
到POT 就添加不上呢
![image](https://github.com/pot-app/pot-desktop/assets/30548000/a749c23a-1ab5-4474-a38b-77bfcaa01d21)
 点 保存就一直在转圈 转很长时间 也添加不上

### Application Scenario

为什么添加不上呢 为啥一直在转圈呢

### References

111

**Comment by lhj5426** [comment]
唯独 谷歌AI 添加补上呢
![image](https://github.com/pot-app/pot-desktop/assets/30548000/e165ccaa-f544-4a15-916c-34754bc31ac4)

**Comment by lhj5426** [comment]
![image](https://github.com/pot-app/pot-desktop/assets/30548000/ed15c0d5-c010-4746-af48-9e0ba8bbc5f3)
已经是最新版了 为啥点保存要一直转圈啊
你先添加上在通信不行么
![image](https://github.com/pot-app/pot-desktop/assets/30548000/3d3fff4c-74a7-41d3-91cf-a22a802788a4)

**Comment by lhj5426** [comment]
这边的配置指南也是404
![image](https://github.com/pot-app/pot-desktop/assets/30548000/e3aeb824-efd9-4007-b5c7-01313114c6ee)
 是不好使了么这边的

**Comment by lhj5426** [comment]
日 不能用流  关了流好了 
![image](https://github.com/pot-app/pot-desktop/assets/30548000/8f47d636-d24b-420d-991a-1ba9aa1f1645)

**Comment by MystiPanda** [comment]
流式输出得开系统代理

**Comment by lhj5426** [comment]
> 流式输出得开系统_代理_

搜噶 我不是系统代理   谢谢我是就 127、0、0、1 加代理端口的形式
