### ISSUE TITLE
Windows 打不开软件

### ISSUE THREAD

**Issue by testlover** [pot-app/pot-desktop#88]
### 问题描述

使用安装版和绿色版都打不开设置界面，只在右下角有个图标，里面的菜单点了都没反应

### 如何复现

使用安装版和绿色版都打不开设置界面，只在右下角有个图标，里面的菜单点了都没反应

### 操作系统

Windows (Default)

### 操作系统版本

windows 11

### 窗口系统(Linux Only)

None

### 软件版本

0.3.2

**Comment by Pylogmon** [comment]
根据你给出的这些信息我也没办法判断是什么原因，麻烦加qq或者tg群详细讨论。

**Comment by NNGTHB** [comment]
> 根据你给出的这些信息我也没办法判断是什么原因，麻烦加qq或者tg群详细讨论。

我也出现了这种情况，win10，大致就是关闭设置窗口后软件就卡死在那了，发生这种情况的概率还挺高的，这时候点Tray没有任何反应，也无法正常退出，只能在任务管理器强退软件。

![动画3](https://github.com/pot-app/pot-desktop/assets/115760745/6c9353d5-cbb4-43c9-bb23-204639a5a49a)

**Comment by dkeraaaa** [comment]
完全一样的问题，win11系统不能打开界面，点击菜单里的翻译会直接退出，其他按钮点击后无反应

**Comment by Pylogmon** [comment]
下载安装这个，启动看一下报错

[pot-debug.zip](https://github.com/pot-app/pot-desktop/files/11495908/pot-debug.zip)

**Comment by dkeraaaa** [comment]
启动后报错：failed to create webview: WebView2 error: WindowsError(Error { code: 0x80070002, message: 系统找不到指定的文件。 })


在2023年5月17日 ***@***.***> 写道：

下载安装这个，启动看一下报错

pot-debug.zip

**Comment by testlover** [comment]
我单独安装了 webview2 还是不行 
我搜了下这个错误 好像是webview2在一些类型的登录用户下 有点问题 正好我用的是域账号登录的windows 不知道是不是这个原因

https://github.com/MicrosoftEdge/WebView2Feedback/issues/1907

不知道   @dkeraaaa  是不是也是这种情况

**Comment by dkeraaaa** [comment]
我使用工具禁用了edge浏览器，解禁后可以正常使用

**Comment by Pylogmon** [comment]
你那应该是连着webview一起禁了，我是把edge卸载了的，只留着webview2也能用。

**Comment by binglin1009** [comment]
这个问题关闭了啊？
win10上也存在啊。portable的可以正常使用，但是msi的无法安装，双击后，鼠标转了几圈后，就没反应了。

portable的我设置为开机启动了。刚才提示我更新，我点击更新后，下载了msi的文件，然后弹出win10安全管理，就是那个什么权限提示，我点击确认，鼠标转了一圈，然后又弹出更新提示。百分百是安装包的问题。

**Comment by Pylogmon** [comment]
你这也不是同一个问题啊，人家是安装后打不开软件，你这是没法安装

**Comment by zfh18** [comment]
> 我单独安装了 webview2 还是不行 我搜了下这个错误 好像是webview2在一些类型的登录用户下 有点问题 正好我用的是域账号登录的windows 不知道是不是这个原因
> 
> [MicrosoftEdge/WebView2Feedback#1907](https://github.com/MicrosoftEdge/WebView2Feedback/issues/1907)
> 
> 不知道 @dkeraaaa 是不是也是这种情况

遇到了同样的问题，请问你的解决了吗？

**Comment by zfh18** [comment]
我的情况是，之前打不开软件，只有任务栏图标，后面突然发现，使用 windows 7 兼容模式可以正常打开软件使用了，不确定是否有其它影响，win10 企业版 21H2，供参考。

**Comment by l-d-y** [comment]
> 我使用工具禁用了edge浏览器，解禁后可以正常使用

我也是用了那个工具
