### ISSUE TITLE
推荐可以和Quicker配合使用

### ISSUE THREAD

**Issue by baitaotao520** [pot-app/pot-desktop#882]
### Description

![image](https://github.com/user-attachments/assets/ed7e0ae5-8309-4cb6-af1e-81e827eae09a)
嘎嘎好用
![image](https://github.com/user-attachments/assets/5a2bc8aa-5b1b-4d2b-a610-9bc0bad786b3)
通过网络请求

### Application Scenario

无

**Comment by baitaotao520** [comment]
字打错了,该回来了
![image](https://github.com/user-attachments/assets/0063d421-b80d-4209-8bb9-3c86dd7156dc)

**Comment by OdinZhang** [comment]
发请求不是够了吗，还要啥集成

**Comment by baitaotao520** [comment]
只是推荐,不是要集成
