### ISSUE TITLE
[BUG]: 插件文件夹名与potext的文件名相同

### ISSUE THREAD

**Issue by sglzp** [pot-app/pot-desktop#889]
### Description

修改potext的文件名再导入会导致插件文件夹名随之变化，会导致数据库无法连接

### Reproduction

无

### Platform

Windows

### System Version

Windows 11 Home Edition 22631.3593

### Window System (Linux Only)

None

### Software Version

3.0.5

**Comment by chergn** [comment]
[插件下载地址](https://pot-app.com/plugin.html#%E7%BF%BB%E8%AF%91)该放到界面上 
![image](https://github.com/user-attachments/assets/5dd8c7fe-00bf-4880-8df8-ecebd4a84b7b)

**Comment by sglzp** [comment]
![image](https://github.com/user-attachments/assets/40bd240f-ae76-46c8-a1c7-f996715dbf79)
