### ISSUE TITLE
增加单词本收藏和历史记录功能

### ISSUE THREAD

**Issue by NNGTHB** [pot-app/pot-desktop#89]
### 需求描述

历史记录能保留之前的查询结果。收藏夹能暂存查询单词，之后能对收藏夹中的单词进行二次编辑，能够多选并批量导出到anki

### 应用场景

使划词翻译的流程更加顺畅，增加容错，查询后不用过多思考这个单词是否值得进一步掌握（导入到anki或欧路），减少精神力消耗。

**Comment by androidcn** [comment]
目前就能搞啊，调用anki或者欧路
我在用欧路

**Comment by NNGTHB** [comment]
> l

我知道能调用anki，我主要是需要一个收藏本用来暂存，这样我就能在某次集中查词后统一导出到anki，而不是需要查一次导出一次，而且如果在anki复习的时候发现卡片需要修改或删除，这无疑是一次负反馈

**Comment by Pylogmon** [comment]
历史记录功能是有计划的，后续会支持

**Comment by Pylogmon** [comment]
这个功能有点问题，多接口同时翻译的时候，历史记录到底添加哪一条呢

**Comment by NNGTHB** [comment]
> 这个功能有点问题，多接口同时翻译的时候，历史记录到底添加哪一条呢

第一条就够了，多接口翻译更多是起到一个参考作用

**Comment by jlduu** [comment]
> 这个功能有点问题，多接口同时翻译的时候，历史记录到底添加哪一条呢

我觉得的历史记录只保留原文字的历史记录即可，而不是原文字和翻译。这样就不必关注是哪个翻译接口的，如果需要翻译的文字直接点击原文字再翻译即可。

**Comment by RedwindA** [comment]
> 这个功能有点问题，多接口同时翻译的时候，历史记录到底添加哪一条呢

我觉得应该添加全部的历史记录

或者在翻译结果界面，为每一个翻译引擎添加一个‘仅保存该引擎的结果’按钮，这样用户就可以手动保存最佳翻译，如果用户不选择，则在关闭窗口后默认存储所有引擎的结果，或者默认仅保存第一位的翻译引擎结果
