### ISSUE TITLE
[BUG]: 智谱AI的内置模型错误

### ISSUE THREAD

**Issue by Testgrehtion939** [pot-app/pot-desktop#894]
### Description

目前设置内置的模型与智谱AI官方提供的AI模型不符合。以下是我在官网上查看支持的模型：
glm-4-0520,glm-4,glm-4-alltools,
glm-3-turbo,glm-4v,glm-4-flash,glm-4-airx,glm-4-air,embedding-2,charglm-3,codegeex-4

### Reproduction

![image](https://github.com/user-attachments/assets/2d31e3ae-b460-4d61-90e6-ff58f7616401)
这是内置的模型

### Platform

Windows

### System Version

Windows 11 Pro 22631.3958

### Window System (Linux Only)

None

### Software Version

3.0.5

**Comment by xtyuns** [comment]
Merged into #931
