### ISSUE TITLE
笔记本合页休眠，重新打开后，翻译功能不启用

### ISSUE THREAD

**Issue by cherub0507** [pot-app/pot-desktop#909]
### Description

笔记本合页休眠，重新打开后，翻译功能不启用，POT退出重新启动翻译功能也不恢复

windows重新启动后，翻译功能恢复正常

### Platform

Windows

### System Version

win 11 pro x64

### Window System (Linux Only)

None

### Software Version

3.0.5

**Comment by cherub0507** [comment]
另外，截图识别后，在识别界面，点击右下角的翻译按钮，没有响应

删除所有配置文件重启，问题复现

**Comment by xtyuns** [comment]
"翻译功能不启用" 是什么现象，无法弹出翻译窗口还是翻译窗口中无内容？

**Comment by cherub0507** [comment]
> "翻译功能不启用" 是什么现象，无法弹出翻译窗口还是翻译窗口中无内容？

点击翻译按钮，各个Api窗口都没有翻译内容

**Comment by xtyuns** [comment]
需要收集一些调试信息，怎么联系你

**Comment by xtyuns** [comment]
> App对代理设置的问题

有可能，目前在调用翻译服务出错时不会展示错误信息，所以可能和网络环境配置有关



> 以上是发生在我回国期间，目前在海外使用都正常

目前无法复现 issue 就先关闭了，如果仍存在该问题，可以再次打开

**Comment by suibianzai** [comment]
> > App对代理设置的问题
> 
> 有可能，目前在调用翻译服务出错时不会展示错误信息，所以可能和网络环境配置有关
> 
> > 以上是发生在我回国期间，目前在海外使用都正常
> 
> 目前无法复现 issue 就先关闭了，如果仍存在该问题，可以再次打开

同样的问题，代理没设置正确，翻译窗口就直接无任何反应。能否对这种情况再翻译窗口增加一个报错提示或者提醒呢？这样可以直接知道是代理出问题了。
