### ISSUE TITLE
[Feature]: 添加智谱GLM-4-Flash API接口

### ISSUE THREAD

**Issue by ZhikangNiu** [pot-app/pot-desktop#916]
### Description

智谱AI免费了GLM-4-Flash的API，如果支持了的话就可以免费使用翻译功能了

### Application Scenario

智谱AI免费了GLM-4-Flash的API，如果支持了的话就可以免费使用翻译功能了

### References

https://open.bigmodel.cn/dev/api#glm-4

**Comment by ZhikangNiu** [comment]
same to https://github.com/pot-app/pot-desktop/issues/894

**Comment by xtyuns** [comment]
Merged into #931
