### ISSUE TITLE
[Feature]: 希望增加显示英文释义的功能

### ISSUE THREAD

**Issue by heifeise** [pot-app/pot-desktop#932]
### Description

如题

### Application Scenario

感觉这样更适合英语学习

**Comment by xtyuns** [comment]
请使用词典类翻译服务
![图片](https://github.com/user-attachments/assets/9bb7aead-2349-4987-b8f0-2cf3cf7edc7d)

**Comment by heifeise** [comment]
@xtyuns 抱歉，我说的是用英文解释英文，而不是显示音标。如对于explain，其英文释义为：make (an idea, situation, or problem) clear to someone by describing it in more detail or revealing relevant facts or ideas.

**Comment by xtyuns** [comment]
可以通过大语言模型+自定义提示词来实现这个需求
