### ISSUE TITLE
[BUG] 多屏幕无法判断窗口边界

### ISSUE THREAD

**Issue by JasonLeeForOnly** [pot-app/pot-desktop#94]
### 问题描述

![image](https://github.com/pot-app/pot-desktop/assets/47520063/3345ecaf-25ef-4a54-924b-c32eb93b83c7)

### 如何复现

如题：
1.偶发性无法带入选中的文本，在各类软件中都可能会复现
2.偶发性窗体弹出位置大部分被遮挡，出现的位置翻译部分被遮挡，且拖拽松开后窗体会消失，严重影响使用

### 操作系统

Windows (Default)

### 操作系统版本

Windows11

### 窗口系统(Linux Only)

None

### 软件版本

pot:0.1.18  Tauri:1.2.4

**Comment by Pylogmon** [comment]
请先升级最新版本，如果问题仍然存在再来反馈。

**Comment by Pylogmon** [comment]
拖拽消失见这里 #36 这个问题暂时没法解决，但是可以点击pin按钮就可以拖动了，这是暂时的解决办法。

至于窗体大部分遮挡的问题，请问你是多屏幕吗

**Comment by JasonLeeForOnly** [comment]
没错，是多屏幕。一块2K，一块1080

**Comment by JasonLeeForOnly** [comment]
> 拖拽消失见这里 #36 这个问题暂时没法解决，但是可以点击pin按钮就可以拖动了，这是暂时的解决办法。
> 
> 至于窗体大部分遮挡的问题，请问你是多屏幕吗

没错，是多屏幕。一块2K，一块1080

**Comment by Pylogmon** [comment]
这个问题我有发现，在第二块屏幕上无法判断屏幕边界，我暂时没有想到好的办法
