### ISSUE TITLE
[BUG]: 官网没法访问了

### ISSUE THREAD

**Issue by luguosong** [pot-app/pot-desktop#942]
### Description

![image](https://github.com/user-attachments/assets/810a5518-496c-454a-8ef8-c2fce0f6f637)

### Reproduction

官网无法访问

### Platform

Windows

### System Version

-

### Window System (Linux Only)

None

### Software Version

-

**Comment by xtyuns** [comment]
我这边可以正常打开
![image](https://github.com/user-attachments/assets/835ca4d4-9979-4561-a3cb-af03476838fe)
