### ISSUE TITLE
[Feature]: 添加lingve翻译接口

### ISSUE THREAD

**Issue by qcts33** [pot-app/pot-desktop#95]
### 需求描述

lingve是一个Google translate的一个第三方前端，也具有API调用的功能，希望能偶给予支持

### 应用场景

lingve允许自建服务，有自己的境外服务器的话就用得比较舒服

### 参考资料

https://github.com/thedaviddelta/lingva-translate

**Comment by Pylogmon** [comment]
看起来不错
