### ISSUE TITLE
[BUG]:Mac x64截图翻译，浏览器会隐藏掉，怎么解？需要怎么设置，就是要截浏览器内的内容

### ISSUE THREAD

**Issue by zsray110** [pot-app/pot-desktop#950]
### Description

一按截图翻译的快捷，浏览器就隐藏了

### Reproduction

一按截图翻译的快捷，浏览器就隐藏了

### Platform

MacOS

### System Version

macos intel

### Window System (Linux Only)

None

### Software Version

laster

**Comment by qihaogithub** [comment]
我也是这个问题

**Comment by zsray110** [comment]
好了，忘了关帖，重启了软件后会重新要求权限，系统设置里打开权限就好
