### ISSUE TITLE
[Feature]: 总是自动删除多余空格和空行

### ISSUE THREAD

**Issue by qcts33** [pot-app/pot-desktop#96]
### 需求描述

希望可以在设置中加一个选项，每次划词翻译都默认执行删除多余空格和换行的动作

### 应用场景

在PDF阅读的过程中，划词翻译的内容几乎总是有多余空格和换行，希望可以进一步简化操作

**Comment by Pylogmon** [comment]
![image](https://github.com/pot-app/pot-desktop/assets/59004461/fc19e4bb-6974-4bfe-b72e-6913bd3b5566)

**Comment by qcts33** [comment]
没注意到，sorry
