### ISSUE TITLE
在Ubuntu24.04系统上无法设置快捷键

### ISSUE THREAD

**Issue by gxx2778** [pot-app/pot-desktop#963]
### Description

我在Ubuntu24.04系统上用这个软件，遇到无法设置快捷键的问题，热建设置时我试了各自快捷键组合他都会显示“快捷键已经被注册“。所有热建设置都这样，我无法使用快捷键触发软件。

### Reproduction

100%

### Platform

Linux

### System Version

Ubuntu24.04

### Window System (Linux Only)

None

### Software Version

3.0.5

**Comment by luyanfeng** [comment]
我也是ubuntu24.04 是可以的, 你看下是不是你环境问题

**Comment by gxx2778** [comment]
> 我也是ubuntu24.04 是可以的, 你看下是不是你环境问题

我系统安装没多久，应该不是和其他软件冲突，但我试了很多都不行

**Comment by lushangkan** [comment]
> > 我也是ubuntu24.04 是可以的, 你看下是不是你环境问题
> 
> 我系统安装没多久，应该不是和其他软件冲突，但我试了很多都不行

一样

**Comment by xtyuns** [comment]
RTFM https://github.com/pot-app/pot-desktop?tab=readme-ov-file#%E5%BF%AB%E6%8D%B7%E9%94%AE%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8
