### ISSUE TITLE
[BUG]: 更新报错！

### ISSUE THREAD

**Issue by wang-bailin** [pot-app/pot-desktop#969]
### Description

提示信息：
Tauri API error: Network Error: error sending request for url (https://dl.pot-app.com/https://github.com/pot-app/pot-desktop/releases/download/3.0.6/pot_3.0.6_x64-setup.nsis.zip): error trying to connect: 远程主机强迫关闭了一个现有的连接。 (os error 10054)

### Reproduction

点击更新按钮

### Platform

Windows

### System Version

win10 ltsc最新补丁

### Window System (Linux Only)

None

### Software Version

3.0.5

**Comment by xtyuns** [comment]
这种一般是网络环境问题，检查网络环境后重试即可

**Comment by wang-bailin** [comment]
> 这种一般是网络环境问题，检查网络环境后重试即可

挂了vpn也不好使

**Comment by elarbor** [comment]
我的直接不能升级
![动画](https://github.com/user-attachments/assets/155b8db0-1cf0-4dac-ac07-ec2ee4b00f32)
点击没反应
