### ISSUE TITLE
[BUG]: Ubuntu 24.04 安装失败

### ISSUE THREAD

**Issue by SadSock** [pot-app/pot-desktop#979]
### Description

在Ubuntu24.04下安装时 出现错误

The following packages have unmet dependencies:
 pot: 依赖: libwebkit2gtk-4.0-37 but it is not installable

### Reproduction

1. 下载deb包
2. 双击安装

### Platform

Linux

### System Version

ubuntu 24.04

### Window System (Linux Only)

Wayland

### Software Version

3.0.6

### Log File

The following packages have unmet dependencies:
  pot: 依赖: libwebkit2gtk-4.0-37 but it is not installable

**Comment by wty-yy** [comment]
我也遇到此问题
```bash
> sudo apt install libwebkit2gtk-4.0-37
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libwebkit2gtk-4.0-37
E: Couldn't find any package by glob 'libwebkit2gtk-4.0-37'
```
但是ubuntu24.04支持安装libwebkit2gtk-4.1-dev，所以pot会更新到4.1版本么

**Comment by xtyuns** [comment]
Duplicate #794
