### ISSUE TITLE
热键设置-快捷键设置 这里没办法绑定游戏鼠标的侧键

### ISSUE THREAD

**Issue by zuiaiyutu** [pot-app/pot-desktop#98]
### 需求描述

热键设置-快捷键设置 这里没办法绑定游戏鼠标的侧键
但是按侧键却可以在应用设置，翻译设置，外联设置这一级别的菜单间跳转

### 应用场景

把快捷键绑定在鼠标侧键，只按一个键就可以翻译，还不需要离开鼠标

**Comment by Pylogmon** [comment]
现在还没有办法设置鼠标快捷键，菜单间的跳转是浏览器的默认行为，如果想要不离开鼠标翻译可以看看官网文档的插件翻译
