### ISSUE TITLE
[BUG]: 使用rime中文输入法 输入时会导致翻译窗口未响应

### ISSUE THREAD

**Issue by OcrSu** [pot-app/pot-desktop#982]
### Description

![PixPin_2024-11-18_16-14-54](https://github.com/user-attachments/assets/06d358ff-f185-4a9c-8abe-6e07d0aae16b)

### Reproduction
1.快捷键调用 pot划词翻译 的翻译（翻译，不是划词翻译）功能，成功调用出翻译窗口。
2. 切换到rime中文输入法 
3. 使用rime windows输入法的中文模式 输入任何汉字（按下任何拼音按钮都会导致窗口未响应）

### Platform

Windows

### System Version

Windows 10 IoT 企业版 LTSC 21H2 19044.5011

### Window System (Linux Only)

None

### Software Version

4.0.6

**Comment by xtyuns** [comment]
看起来像是代理工具导致 pot 中的网络连接失败了，代理工具以什么模式运行的，tun/system proxy？

**Comment by OcrSu** [comment]
> 看起来像是代理工具导致 pot 中的网络连接失败了，代理工具以什么模式运行的，tun/system proxy？

![image](https://github.com/user-attachments/assets/a9c45bd9-6d35-4a1c-a594-615c334476fe)

**Comment by OcrSu** [comment]
> 看起来像是代理工具导致 pot 中的网络连接失败了，代理工具以什么模式运行的，tun/system proxy？

我重新测试了一下，那个输入法问题和代理没关系，是单独的bug
我这里补个gif
![PixPin_2024-11-18_16-14-54](https://github.com/user-attachments/assets/8bbd38e7-7e91-4c50-ab2e-b4e964b0c407)

**Comment by OcrSu** [comment]
> 看起来像是代理工具导致 pot 中的网络连接失败了，代理工具以什么模式运行的，tun/system proxy？

解决了，系统代理和tun不能一起开启，关掉系统代理就好了
但是输入法问题仍然存在
