### ISSUE TITLE
[Feature]: 希望支持悬浮球选词功能，类似的项目是 TTime

### ISSUE THREAD

**Issue by gitlayzer** [pot-app/pot-desktop#984]
### Description

可以选中之后在鼠标附近出现一个小窗口然后点击小窗口触发翻译，传递选中的文本

### Application Scenario

部分段落翻译，或者快速翻译一些 App 中的英文

**Comment by xtyuns** [comment]
可以使用 snipdo 来实现这个效果: https://pot-app.com/docs/invoke.html#snipdo-windows
