### ISSUE TITLE
[Feature]: title增加鼠标取词翻译，效果类似，鼠标准心在词的中心，然后按下快捷键就翻译

### ISSUE THREAD

**Issue by ClarenChen** [pot-app/pot-desktop#998]
### Description

增加鼠标取词翻译，效果类似，鼠标准心在词的中心，然后按下快捷键就翻译

### Application Scenario

**增加鼠标取词翻译，效果类似，鼠标准心在词的中心，然后按下快捷键就翻译**

### References

增加鼠标取词翻译，效果类似，鼠标准心在词的中心，然后按下快捷键就翻译

**Comment by xtyuns** [comment]
no plan
